/**
 * TSH Global Scripture Engine
 * Contains 34 verses translated into 16 major languages.
 */

const scriptures = {
    "en": [
        { text: "Be still, and know that I am God.", ref: "Psalm 46:10" },
        { text: "The Lord will fight for you; you need only to be still.", ref: "Exodus 14:14" },
        { text: "Truly my soul finds rest in God; my salvation comes from him. Truly he is my rock and my salvation; he is my fortress, I will never be shaken.", ref: "Psalm 62:1-2" },
        { text: "Come to me, all you who are weary and burdened, and I will give you rest.", ref: "Matthew 11:28" },
        { text: "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.", ref: "John 14:27" },
        { text: "I keep my eyes always on the Lord. With him at my right hand, I will not be shaken.", ref: "Psalm 16:8" },
        { text: "No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear. But when you are tempted, he will also provide a way out so that you can endure it.", ref: "1 Corinthians 10:13" },
        { text: "Submit yourselves, then, to God. Resist the devil, and he will flee from you.", ref: "James 4:7" },
        { text: "The weapons we fight with are not the weapons of the world. On the contrary, they have divine power to demolish strongholds.", ref: "2 Corinthians 10:4" },
        { text: "It is for freedom that Christ has set us free. Stand firm, then, and do not let yourselves be burdened again by a yoke of slavery.", ref: "Galatians 5:1" },
        { text: "So if the Son sets you free, you will be free indeed.", ref: "John 8:36" },
        { text: "You are my refuge and my shield; I have put my hope in your word.", ref: "Psalm 119:114" },
        { text: "My flesh and my heart may fail, but God is the strength of my heart and my portion forever.", ref: "Psalm 73:26" },
        { text: "But he said to me, 'My grace is sufficient for you, for my power is made perfect in weakness.'", ref: "2 Corinthians 12:9" },
        { text: "But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.", ref: "Isaiah 40:31" },
        { text: "He gives strength to the weary and increases the power of the weak.", ref: "Isaiah 40:29" },
        { text: "I can do all this through him who gives me strength.", ref: "Philippians 4:13" },
        { text: "I lift up my eyes to the mountains—where does my help come from? My help comes from the Lord, the Maker of heaven and earth.", ref: "Psalm 121:1-2" },
        { text: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds.", ref: "Philippians 4:6-7" },
        { text: "So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.", ref: "Isaiah 41:10" },
        { text: "When anxiety was great within me, your consolation brought me joy.", ref: "Psalm 94:19" },
        { text: "Cast all your anxiety on him because he cares for you.", ref: "1 Peter 5:7" },
        { text: "Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.", ref: "Psalm 23:4" },
        { text: "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.", ref: "2 Timothy 1:7" },
        { text: "For though the righteous fall seven times, they rise again, but the wicked stumble when calamity strikes.", ref: "Proverbs 24:16" },
        { text: "The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness.", ref: "Lamentations 3:22-23" },
        { text: "Do not gloat over me, my enemy! Though I have fallen, I will rise. Though I sit in darkness, the Lord will be my light.", ref: "Micah 7:8" },
        { text: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", ref: "Psalm 34:18" },
        { text: "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!", ref: "2 Corinthians 5:17" },
        { text: "You, dear children, are from God and have overcome them, because the one who is in you is greater than the one who is in the world.", ref: "1 John 4:4" },
        { text: "When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you. When you walk through the fire, you will not be burned; the flames will not set you ablaze.", ref: "Isaiah 43:2" },
        { text: "God is our refuge and strength, an ever-present help in trouble.", ref: "Psalm 46:1" },
        { text: "From the ends of the earth I call to you, I call as my heart grows faint; lead me to the rock that is higher than I.", ref: "Psalm 61:2" },
        { text: "I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world.", ref: "John 16:33" }
    ],
    "es": [
        { text: "Estad quietos, y conoced que yo soy Dios.", ref: "Salmos 46:10" },
        { text: "Jehová peleará por vosotros, y vosotros estaréis tranquilos.", ref: "Éxodo 14:14" },
        { text: "En Dios solamente está acallada mi alma; De él viene mi salvación. Él solamente es mi roca y mi salvación; Es mi refugio, no resbalaré mucho.", ref: "Salmos 62:1-2" },
        { text: "Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.", ref: "Mateo 11:28" },
        { text: "La paz os dejo, mi paz os doy; yo no os la doy como el mundo la da. No se turbe vuestro corazón, ni tenga miedo.", ref: "Juan 14:27" },
        { text: "A Jehová he puesto siempre delante de mí; Porque está a mi diestra, no seré conmovido.", ref: "Salmos 16:8" },
        { text: "No os ha sobrevenido ninguna tentación que no sea humana; pero fiel es Dios, que no os dejará ser tentados más de lo que podéis resistir.", ref: "1 Corintios 10:13" },
        { text: "Someteos, pues, a Dios; resistid al diablo, y huirá de vosotros.", ref: "Santiago 4:7" },
        { text: "Porque las armas de nuestra milicia no son carnales, sino poderosas en Dios para la destrucción de fortalezas.", ref: "2 Corintios 10:4" },
        { text: "Estad, pues, firmes en la libertad con que Cristo nos hizo libres, y no estéis otra vez sujetos al yugo de esclavitud.", ref: "Gálatas 5:1" },
        { text: "Así que, si el Hijo os libertare, seréis verdaderamente libres.", ref: "Juan 8:36" },
        { text: "Mi escondedero y mi escudo eres tú; En tu palabra he esperado.", ref: "Salmos 119:114" },
        { text: "Mi carne y mi corazón desfallecen; Mas la roca de mi corazón y mi porción es Dios para siempre.", ref: "Salmos 73:26" },
        { text: "Y me ha dicho: Bástate mi gracia; porque mi poder se perfecciona en la debilidad.", ref: "2 Corintios 12:9" },
        { text: "Pero los que esperan a Jehová tendrán nuevas fuerzas; levantarán alas como las águilas.", ref: "Isaías 40:31" },
        { text: "Él da esfuerzo al cansado, y multiplica las fuerzas al que no tiene ningunas.", ref: "Isaías 40:29" },
        { text: "Todo lo puedo en Cristo que me fortalece.", ref: "Filipenses 4:13" },
        { text: "Alzaré mis ojos a los montes; ¿De dónde vendrá mi socorro? Mi socorro viene de Jehová.", ref: "Salmos 121:1-2" },
        { text: "Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios en toda oración.", ref: "Filipenses 4:6-7" },
        { text: "No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo.", ref: "Isaías 41:10" },
        { text: "En la multitud de mis pensamientos dentro de mí, Tus consolaciones alegraban mi alma.", ref: "Salmos 94:19" },
        { text: "Echando toda vuestra ansiedad sobre él, porque él tiene cuidado de vosotros.", ref: "1 Pedro 5:7" },
        { text: "Aunque ande en valle de sombra de muerte, No temeré mal alguno, porque tú estarás conmigo.", ref: "Salmos 23:4" },
        { text: "Porque no nos ha dado Dios espíritu de cobardía, sino de poder, de amor y de dominio propio.", ref: "2 Timoteo 1:7" },
        { text: "Porque siete veces cae el justo, y vuelve a levantarse.", ref: "Proverbios 24:16" },
        { text: "Por la misericordia de Jehová no hemos sido consumidos, porque nunca decayeron sus misericordias.", ref: "Lamentaciones 3:22-23" },
        { text: "Tú, enemiga mía, no te alegres de mí, porque aunque caí, me levantaré.", ref: "Miqueas 7:8" },
        { text: "Cercano está Jehová a los quebrantados de corazón; Y salva a los contritos de espíritu.", ref: "Salmos 34:18" },
        { text: "De modo que si alguno está en Cristo, nueva criatura es.", ref: "2 Corintios 5:17" },
        { text: "Hijitos, vosotros sois de Dios, y los habéis vencido.", ref: "1 Juan 4:4" },
        { text: "Cuando pases por las aguas, yo estaré contigo; y si por los ríos, no te anegarán.", ref: "Isaías 43:2" },
        { text: "Dios es nuestro amparo y fortaleza, Nuestro pronto auxilio en las tribulaciones.", ref: "Salmos 46:1" },
        { text: "Desde el cabo de la tierra clamaré a ti, cuando mi corazón desmayare.", ref: "Salmos 61:2" },
        { text: "Estas cosas os he hablado para que en mí tengáis paz. En el mundo tendréis aflicción; pero confiad, yo he vencido al mundo.", ref: "Juan 16:33" }
    ],
    "fr": [
        { text: "Arrêtez, et sachez que je suis Dieu.", ref: "Psaumes 46:10" },
        { text: "L'Éternel combattra pour vous; et vous, gardez le silence.", ref: "Exode 14:14" },
        { text: "Oui, c'est en Dieu que mon âme se confie; De lui vient mon salut. Oui, c'est lui qui est mon rocher et mon salut.", ref: "Psaumes 62:1-2" },
        { text: "Venez à moi, vous tous qui êtes fatigués et chargés, et je vous donnerai du repos.", ref: "Matthieu 11:28" },
        { text: "Je vous laisse la paix, je vous donne ma paix. Je ne vous donne pas comme le monde donne.", ref: "Jean 14:27" },
        { text: "J'ai constamment l'Éternel sous mes yeux; Quand il est à ma droite, je ne chancelle pas.", ref: "Psaumes 16:8" },
        { text: "Aucune tentation ne vous est survenue qui n'ait été humaine, et Dieu, qui est fidèle, ne permettra pas que vous soyez tentés au delà de vos forces.", ref: "1 Corinthiens 10:13" },
        { text: "Soumettez-vous donc à Dieu; résistez au diable, et il fuira loin de vous.", ref: "Jacques 4:7" },
        { text: "Car les armes avec lesquelles nous combattons ne sont pas charnelles; mais elles sont puissantes, par la vertu de Dieu, pour renverser des forteresses.", ref: "2 Corinthiens 10:4" },
        { text: "C'est pour la liberté que Christ nous a affranchis. Demeurez donc fermes, et ne vous laissez pas mettre de nouveau sous le joug de la servitude.", ref: "Galates 5:1" },
        { text: "Si donc le Fils vous affranchit, vous serez réellement libres.", ref: "Jean 8:36" },
        { text: "Tu es mon asile et mon bouclier; J'espère en ta promesse.", ref: "Psaumes 119:114" },
        { text: "Ma chair et mon coeur peuvent se consumer: Dieu sera toujours le rocher de mon coeur et mon partage.", ref: "Psaumes 73:26" },
        { text: "Et il m'a dit: Ma grâce te suffit, car ma puissance s'accomplit dans la faiblesse.", ref: "2 Corinthiens 12:9" },
        { text: "Mais ceux qui se confient en l'Éternel renouvellent leur force. Ils prennent le vol comme les aigles.", ref: "Ésaïe 40:31" },
        { text: "Il donne de la force à celui qui est fatigué, Et il augmente la vigueur de celui qui tombe en défaillance.", ref: "Ésaïe 40:29" },
        { text: "Je puis tout par celui qui me fortifie.", ref: "Philippiens 4:13" },
        { text: "Je lève mes yeux vers les montagnes... D'où me viendra le secours? Le secours me vient de l'Éternel, Qui a fait les cieux et la terre.", ref: "Psaumes 121:1-2" },
        { text: "Ne vous inquiétez de rien; mais en toute chose faites connaître vos besoins à Dieu par des prières et des supplications, avec des actions de grâces.", ref: "Philippiens 4:6-7" },
        { text: "Ne crains rien, car je suis avec toi; Ne promène pas des regards inquiets, car je suis ton Dieu.", ref: "Ésaïe 41:10" },
        { text: "Quand les pensées s'agitent en foule au dedans de moi, Tes consolations réjouissent mon âme.", ref: "Psaumes 94:19" },
        { text: "Et déchargez-vous sur lui de tous vos soucis, car lui-même prend soin de vous.", ref: "1 Pierre 5:7" },
        { text: "Quand je marche dans la vallée de l'ombre de la mort, Je ne crains aucun mal, car tu es avec moi.", ref: "Psaumes 23:4" },
        { text: "Car ce n'est pas un esprit de timidité que Dieu nous a donné, mais un esprit de force, d'amour et de sagesse.", ref: "2 Timothée 1:7" },
        { text: "Car sept fois le juste tombe, et il se relève, Mais les méchants sont précipités dans le malheur.", ref: "Proverbes 24:16" },
        { text: "Les bontés de l'Éternel ne sont pas épuisées, Ses compassions ne sont pas à leur terme; Elles se renouvellent chaque matin.", ref: "Lamentations 3:22-23" },
        { text: "Ne te réjouis pas à mon sujet, mon ennemie! Car si je suis tombée, je me relèverai.", ref: "Michée 7:8" },
        { text: "L'Éternel est près de ceux qui ont le coeur brisé, Et il sauve ceux qui ont l'esprit dans l'abattement.", ref: "Psaumes 34:18" },
        { text: "Si quelqu'un est en Christ, il est une nouvelle créature. Les choses anciennes sont passées; voici, toutes choses sont devenues nouvelles.", ref: "2 Corinthiens 5:17" },
        { text: "Vous, petits enfants, vous êtes de Dieu, et vous les avez vaincus, parce que celui qui est en vous est plus grand que celui qui est dans le monde.", ref: "1 Jean 4:4" },
        { text: "Si tu traverses les eaux, je serai avec toi; Et les fleuves, ils ne te submergeront point.", ref: "Ésaïe 43:2" },
        { text: "Dieu est pour nous un refuge et un appui, Un secours qui ne manque jamais dans la détresse.", ref: "Psaumes 46:1" },
        { text: "Du bout de la terre je crie à toi, dans l'abattement de mon coeur; Conduis-moi sur le rocher que je ne puis atteindre!", ref: "Psaumes 61:2" },
        { text: "Je vous ai dit ces choses, afin que vous ayez la paix en moi. Vous aurez des tribulations dans le monde; mais prenez courage, j'ai vaincu le monde.", ref: "Jean 16:33" }
    ],
    "de": [
        { text: "Seid stille und erkennet, dass ich Gott bin.", ref: "Psalm 46:10" },
        { text: "Der Herr wird für euch streiten, und ihr werdet stille sein.", ref: "2. Mose 14:14" },
        { text: "Meine Seele ist stille zu Gott, der mir hilft. Denn er ist mein Fels, meine Hilfe, mein Schutz.", ref: "Psalm 62:1-2" },
        { text: "Kommt her zu mir, alle, die ihr mühselig und beladen seid; ich will euch erquicken.", ref: "Matthäus 11:28" },
        { text: "Den Frieden lasse ich euch, meinen Frieden gebe ich euch. Nicht gebe ich euch, wie die Welt gibt. Euer Herz erschrecke nicht und fürchte sich nicht.", ref: "Johannes 14:27" },
        { text: "Ich habe den Herrn allezeit vor Augen; weil er mir zur Rechten ist, werde ich nicht wanken.", ref: "Psalm 16:8" },
        { text: "Bisher hat euch nur menschliche Versuchung getroffen. Aber Gott ist treu, der euch nicht versuchen lässt über eure Kraft.", ref: "1. Korinther 10:13" },
        { text: "So seid nun Gott untertan. Widersteht dem Teufel, so flieht er von euch.", ref: "Jakobus 4:7" },
        { text: "Denn die Waffen unseres Kampfes sind nicht fleischlich, sondern mächtig im Dienste Gottes, Festungen zu zerstören.", ref: "2. Korinther 10:4" },
        { text: "Zur Freiheit hat uns Christus befreit! So steht nun fest und lasst euch nicht wieder das Joch der Knechtschaft auflegen!", ref: "Galater 5:1" },
        { text: "Wenn euch nun der Sohn frei macht, so seid ihr wirklich frei.", ref: "Johannes 8:36" },
        { text: "Du bist mein Schirm und mein Schild; ich hoffe auf dein Wort.", ref: "Psalm 119:114" },
        { text: "Wenn mir gleich Leib und Seele verschmachtet, so bist du doch, Gott, allezeit meines Herzens Trost und mein Teil.", ref: "Psalm 73:26" },
        { text: "Und er hat zu mir gesagt: Lass dir an meiner Gnade genügen; denn meine Kraft ist in den Schwachen mächtig.", ref: "2. Korinther 12:9" },
        { text: "Aber die auf den Herrn harren, kriegen neue Kraft, dass sie auffahren mit Flügeln wie Adler.", ref: "Jesaja 40:31" },
        { text: "Er gibt dem Müden Kraft, und Stärke genug dem Unvermögenden.", ref: "Jesaja 40:29" },
        { text: "Ich vermag alles durch den, der mich mächtig macht.", ref: "Philipper 4:13" },
        { text: "Ich hebe meine Augen auf zu den Bergen. Woher kommt mir Hilfe? Meine Hilfe kommt vom Herrn, der Himmel und Erde gemacht hat.", ref: "Psalm 121:1-2" },
        { text: "Sorgt euch um nichts, sondern in allen Dingen lasst eure Bitten in Gebet und Flehen mit Danksagung vor Gott kundwerden.", ref: "Philipper 4:6-7" },
        { text: "Fürchte dich nicht, ich bin mit dir; weiche nicht, denn ich bin dein Gott. Ich stärke dich, ich helfe dir auch.", ref: "Jesaja 41:10" },
        { text: "Bei den vielen Sorgen in meinem Herzen erquicken deine Tröstungen meine Seele.", ref: "Psalm 94:19" },
        { text: "Alle eure Sorge werft auf ihn; denn er sorgt für euch.", ref: "1. Petrus 5:7" },
        { text: "Und ob ich schon wanderte im finstern Tal, fürchte ich kein Unglück; denn du bist bei mir.", ref: "Psalm 23:4" },
        { text: "Denn Gott hat uns nicht gegeben den Geist der Furcht, sondern der Kraft und der Liebe und der Besonnenheit.", ref: "2. Timotheus 1:7" },
        { text: "Denn ein Gerechter fällt siebenmal und steht wieder auf, aber die Gottlosen stürzen nieder im Unglück.", ref: "Sprüche 24:16" },
        { text: "Die Güte des Herrn ist's, dass wir nicht gar aus sind, seine Barmherzigkeit hat noch kein Ende, sondern sie ist alle Morgen neu.", ref: "Klagelieder 3:22-23" },
        { text: "Freue dich nicht über mich, meine Feindin! Wenn ich auch liege, so werde ich wieder aufstehen.", ref: "Micha 7:8" },
        { text: "Der Herr ist nahe denen, die zerbrochenen Herzens sind, und hilft denen, die ein zerschlagenes Gemüt haben.", ref: "Psalm 34:18" },
        { text: "Darum: Ist jemand in Christus, so ist er eine neue Kreatur; das Alte ist vergangen, siehe, Neues ist geworden.", ref: "2. Korinther 5:17" },
        { text: "Kinder, ihr seid von Gott und habt jene überwunden; denn der in euch ist, ist größer als der, der in der Welt ist.", ref: "1. Johannes 4:4" },
        { text: "Wenn du durch Wasser gehst, will ich bei dir sein, dass dich die Ströme nicht ersäufen sollen.", ref: "Jesaja 43:2" },
        { text: "Gott ist unsre Zuversicht und Stärke, eine Hilfe in den großen Nöten, die uns getroffen haben.", ref: "Psalm 46:1" },
        { text: "Vom Ende der Erde rufe ich zu dir, da mein Herz geängstet ist: Führe mich auf den Felsen, der mir zu hoch ist!", ref: "Psalm 61:2" },
        { text: "Dies habe ich mit euch geredet, damit ihr in mir Frieden habt. In der Welt habt ihr Angst; aber seid getrost, ich habe die Welt überwunden.", ref: "Johannes 16:33" }
    ],
    "zh": [
        { text: "你们要休息，要知道我是神。", ref: "诗篇 46:10" },
        { text: "耶和华必为你们争战，你们只管静默，不要作声。", ref: "出埃及记 14:14" },
        { text: "我的心默默无声，专等候神；我的救恩是从他而来。惟独他是我的磐石，我的拯救。", ref: "诗篇 62:1-2" },
        { text: "凡劳苦担重担的人可以到我这里来，我就使你们得安息。", ref: "马太福音 11:28" },
        { text: "我留下平安给你们；我将我的平安赐给你们。我所赐的，不像世人所赐的。你们心里不要忧愁，也不要胆怯。", ref: "约翰福音 14:27" },
        { text: "我将耶和华常摆在我面前，因他在我右边，我便不致摇动。", ref: "诗篇 16:8" },
        { text: "你们所遇见的试探，无非是人所能受的。神是信实的，必不叫你们受试探过于所能受的。", ref: "哥林多前书 10:13" },
        { text: "故此你们要顺服神。务要抵挡魔鬼，魔鬼就必离开你们逃跑了。", ref: "雅各书 4:7" },
        { text: "我们争战的兵器本不是属血气的，乃是在神面前有能力，可以攻破坚固的营垒。", ref: "哥林多后书 10:4" },
        { text: "基督释放了我们，叫我们得以自由。所以要站立得稳，不要再被奴仆的轭挟制。", ref: "加拉太书 5:1" },
        { text: "所以天父的儿子若叫你们自由，你们就真自由了。", ref: "约翰福音 8:36" },
        { text: "你是我的藏身之处，又是我的盾牌；我甚仰望你的话语。", ref: "诗篇 119:114" },
        { text: "我的肉体和我的心肠衰退；但神是我心里的力量，又是我的福分，直到永远。", ref: "诗篇 73:26" },
        { text: "他对我说：'我的恩典够你用的，因为我的能力是在人的软弱上显得完全。'", ref: "哥林多后书 12:9" },
        { text: "但那等候耶和华的必从新得力。他们必如鹰展翅上腾。", ref: "以赛亚书 40:31" },
        { text: "疲乏的，他赐能力；软弱的，他加力量。", ref: "以赛亚书 40:29" },
        { text: "我靠着那加给我力量的，凡事都能做。", ref: "腓立比书 4:13" },
        { text: "我要向山举目；我的帮助从何而来？我的帮助从造天地的耶和华而来。", ref: "诗篇 121:1-2" },
        { text: "应当一无挂虑，只要凡事藉着祷告、祈求，和感谢，将你们所要的告诉神。", ref: "腓立比书 4:6-7" },
        { text: "你不要害怕，因为我与你同在；不要惊惶，因为我是你的神。我必坚固你，我必帮助你。", ref: "以赛亚书 41:10" },
        { text: "我心里多忧多疑，你安慰我，就使我欢乐。", ref: "诗篇 94:19" },
        { text: "你们要将一切的忧虑卸给神，因为他顾念你们。", ref: "彼得前书 5:7" },
        { text: "我虽然行过死荫的幽谷，也不怕遭害，因为你与我同在；你的杖，你的竿，都安慰我。", ref: "诗篇 23:4" },
        { text: "因为神赐给我们，不是胆怯的心，乃是刚强、仁爱、谨守的心。", ref: "提摩太后书 1:7" },
        { text: "因为义人虽七次跌倒，仍必兴起；恶人却被祸患倾倒。", ref: "箴言 24:16" },
        { text: "我们不致消灭，是出于耶和华诸般的慈爱；是因他的怜悯不致断绝。每早晨，这都是新的。", ref: "耶利米哀歌 3:22-23" },
        { text: "我的仇敌啊，不要向我夸耀。我虽跌倒，却要起来；我虽坐在黑暗里，耶和华却作我的光。", ref: "弥迦书 7:8" },
        { text: "耶和华靠近伤心的人，拯救灵性痛悔的人。", ref: "诗篇 34:18" },
        { text: "若有人在基督里，他就是新造的人，旧事已过，都变成新的了。", ref: "哥林多后书 5:17" },
        { text: "小子们哪，你们是属神的，并且胜了他们；因为那在你们里面的，比那在世界上的更大。", ref: "约翰一书 4:4" },
        { text: "你从水中经过，我必与你同在；你趟过江河，水必不漫过你；你从火中行过，必不被烧。", ref: "以赛亚书 43:2" },
        { text: "神是我们的避难所，是我们的力量，是我们在患难中随时的帮助。", ref: "诗篇 46:1" },
        { text: "我心里发昏的时候，我要从地极呼求你。求你领我到那比我更高的磐石！", ref: "诗篇 61:2" },
        { text: "我将这些事告诉你们，是要叫你们在我里面有平安。在世上，你们有苦难；但你们可以放心，我已经胜了世界。", ref: "约翰福音 16:33" }
    ],
    "hi": [
        { text: "शांत रहो, और जान लो कि मैं ही परमेश्वर हूँ।", ref: "भजन संहिता 46:10" },
        { text: "यहोवा तुम्हारी ओर से लड़ेगा; तुम केवल शांत रहो।", ref: "निर्गमन 14:14" },
        { text: "सचमुच मेरी आत्मा परमेश्वर में शांति पाती है; मेरा उद्धार उसी से होता है। सचमुच वही मेरी चट्टान और मेरा उद्धार है।", ref: "भजन संहिता 62:1-2" },
        { text: "हे सब परिश्रम करने वालों और बोझ से दबे हुए लोगों, मेरे पास आओ, मैं तुम्हें विश्राम दूंगा।", ref: "मत्ती 11:28" },
        { text: "मैं तुम्हें शांति दिए जाता हूँ; अपनी शांति मैं तुम्हें देता हूँ। जैसे संसार देता है, वैसे मैं तुम्हें नहीं देता। तुम्हारा मन व्याकुल न हो और न डरे।", ref: "यूहन्ना 14:27" },
        { text: "मैं ने यहोवा को निरन्तर अपने सम्मुख रखा है; इसलिए कि वह मेरे दहिने हाथ रहता है, मैं कभी न डगमगाऊंगा।", ref: "भजन संहिता 16:8" },
        { text: "तुम पर कोई ऐसी परीक्षा नहीं पड़ी जो मनुष्य के सहने से बाहर हो। और परमेश्वर सच्चा है; वह तुम्हें तुम्हारे सामर्थ्य से बाहर परीक्षा में न पड़ने देगा।", ref: "1 कुरिन्थियों 10:13" },
        { text: "इसलिए परमेश्वर के अधीन हो जाओ। शैतान का सामना करो, तो वह तुम्हारे पास से भाग निकलेगा।", ref: "याकूब 4:7" },
        { text: "क्योंकि हमारे युद्ध के हथियार शारीरिक नहीं, परन्तु परमेश्वर के द्वारा गढ़ों को ढा देने के लिए सामर्थी हैं।", ref: "2 कुरिन्थियों 10:4" },
        { text: "मसीह ने हमें स्वतंत्रता के लिए स्वतंत्र किया है। इसलिए दृढ़ रहो, और फिर से दासत्व के जुए में न जुतो।", ref: "गलातियों 5:1" },
        { text: "इसलिए यदि पुत्र तुम्हें स्वतंत्र करेगा, तो तुम सचमुच स्वतंत्र हो जाओगे।", ref: "यूहन्ना 8:36" },
        { text: "तू मेरे छिपने का स्थान और मेरी ढाल है; मेरी आशा तेरे वचन पर है।", ref: "भजन संहिता 119:114" },
        { text: "मेरा शरीर और मेरा मन भले ही हार जाएं, परन्तु परमेश्वर मेरे मन की चट्टान और सदा के लिए मेरा भाग है।", ref: "भजन संहिता 73:26" },
        { text: "परन्तु उसने मुझ से कहा, 'मेरा अनुग्रह तेरे लिए बहुत है, क्योंकि मेरी सामर्थ्य निर्बलता में सिद्ध होती है।' ", ref: "2 कुरिन्थियों 12:9" },
        { text: "परन्तु जो यहोवा की बाट जोहते हैं, वे नया बल प्राप्त करेंगे। वे उकाबों के समान उड़ेंगे।", ref: "यशायाह 40:31" },
        { text: "वह थके हुए को बल देता है और निर्बल की शक्ति बढ़ाता है।", ref: "यशायाह 40:29" },
        { text: "जो मुझे सामर्थ्य देता है, उसमें मैं सब कुछ कर सकता हूँ।", ref: "फिलिप्पियों 4:13" },
        { text: "मैं अपनी आँखें पर्वतों की ओर लगाऊंगा—मेरी सहायता कहाँ से आएगी? मेरी सहायता यहोवा की ओर से आती है।", ref: "भजन संहिता 121:1-2" },
        { text: "किसी भी बात की चिन्ता मत करो, परन्तु हर एक बात में तुम्हारे निवेदन, प्रार्थना और विनती के द्वारा धन्यवाद के साथ परमेश्वर के सम्मुख उपस्थित किए जाएं।", ref: "फिलिप्पियों 4:6-7" },
        { text: "मत डर, क्योंकि मैं तेरे संग हूँ; इधर उधर मत ताक, क्योंकि मैं तेरा परमेश्वर हूँ। मैं तुझे दृढ़ करूंगा और तेरी सहायता करूंगा।", ref: "यशायाह 41:10" },
        { text: "जब मेरे मन में बहुत सी चिन्ताएं थीं, तब तेरी दी हुई शान्ति से मेरे प्राण को सुख मिला।", ref: "भजन संहिता 94:19" },
        { text: "अपनी सारी चिन्ता उसी पर डाल दो, क्योंकि उसको तुम्हारा ध्यान है।", ref: "1 पतरस 5:7" },
        { text: "चाहे मैं घोर अन्धकार की तराई में से होकर चलूं, तौभी हानि से न डरूंगा, क्योंकि तू मेरे साथ रहता है।", ref: "भजन संहिता 23:4" },
        { text: "क्योंकि परमेश्वर ने हमें कायरता की आत्मा नहीं, परन्तु सामर्थ्य, प्रेम और संयम की आत्मा दी है।", ref: "2 तीमुथियुस 1:7" },
        { text: "क्योंकि धर्मी सात बार गिरकर फिर उठ खड़ा होता है, परन्तु दुष्ट विपत्ति में गिर जाते हैं।", ref: "नीतिवचन 24:16" },
        { text: "यहोवा की करुणा कभी समाप्त नहीं होती; उसकी दया कभी खतम नहीं होती; वे प्रति भोर नई होती हैं; तेरी सच्चाई महान है।", ref: "विलापगीत 3:22-23" },
        { text: "हे मेरी बैरिन, मुझ पर आनन्द मत कर! यद्यपि मैं गिर गया हूँ, तौभी उठूंगा; यद्यपि मैं अन्धकार में बैठा हूँ, तौभी यहोवा मेरे लिए ज्योति होगा।", ref: "मीका 7:8" },
        { text: "यहोवा टूटे मन वालों के समीप रहता है और पिसे हुओं का उद्धार करता है।", ref: "भजन संहिता 34:18" },
        { text: "इसलिए यदि कोई मसीह में है, तो वह नई सृष्टि है: पुरानी बातें बीत गई हैं; देखो, सब कुछ नया हो गया है!", ref: "2 कुरिन्थियों 5:17" },
        { text: "हे बालकों, तुम परमेश्वर के हो और तुमने उन पर जय पाई है, क्योंकि जो तुम में है, वह उससे जो संसार में है, बड़ा है।", ref: "1 यूहन्ना 4:4" },
        { text: "जब तू जल में से होकर जाए, तो मैं तेरे संग संग रहूंगा; और जब तू नदियों में से होकर जाए, तो वे तुझे न डुबा सकेंगी।", ref: "यशायाह 43:2" },
        { text: "परमेश्वर हमारा शरणस्थान और बल है, संकट में अति सहज से मिलने वाला सहायक।", ref: "भजन संहिता 46:1" },
        { text: "पृथ्वी की छोर से मैं तुझे पुकारूंगा, जब मेरा मन व्याकुल होगा; मुझे उस चट्टान पर ले चल जो मुझसे बहुत ऊंची है।", ref: "भजन संहिता 61:2" },
        { text: "मैं ने ये बातें तुम से इसलिए कही हैं, कि तुम मुझ में शांति पाओ। संसार में तुम्हें क्लेश होता है। परन्तु ढाढ़स बांधो! मैं ने संसार को जीत लिया है।", ref: "यूहन्ना 16:33" }
    ],
    "ar": [
        { text: "كفوا واعلموا أني أنا الله.", ref: "المزامير 46:10" },
        { text: "الرب يقاتل عنكم وأنتم تصمتون.", ref: "الخروج 14:14" },
        { text: "إنما لله انتظرت نفسي، من قبله خلاصي. إنما هو صخرتي وخلاصي، ملجإي، لا أتزعزع كثيراً.", ref: "المزامير 62:1-2" },
        { text: "تعالوا إلي يا جميع المتعبين والثقيلي الأحمال، وأنا أريحكم.", ref: "متى 11:28" },
        { text: "سلاماً أترك لكم، سلامي أعطيكم. ليس كما يعطي العالم أعطيكم أنا. لا تضطرب قلوبكم ولا ترهب.", ref: "يوحنا 14:27" },
        { text: "جعلت الرب أمامي في كل حين، لأنه عن يميني فلا أتزعزع.", ref: "المزامير 16:8" },
        { text: "لم تصبكم تجربة إلا بشرية. ولكن الله أمين، الذي لا يدعكم تجربون فوق ما تستطيعون، بل سيجعل مع التجربة المنفذ.", ref: "1 كورنثوس 10:13" },
        { text: "فاخضعوا لله. قاوموا إبليس فيهرب منكم.", ref: "يعقوب 4:7" },
        { text: "لأن أسلحة محاربتنا ليست جسدية، بل قادرة بالله على هدم حصون.", ref: "2 كورنثوس 10:4" },
        { text: "فاثبتوا إذاً في الحرية التي حررنا المسيح بها، ولا ترتبكوا أيضاً بنير عبودية.", ref: "غلاطية 5:1" },
        { text: "فإن حرركم الابن فبالحقيقة تكونون أحراراً.", ref: "يوحنا 8:36" },
        { text: "مخبأي ومجني أنت. على كلامك رجوت.", ref: "المزامير 119:114" },
        { text: "قد فني لحمي وقلبي. صخرة قلبي ونصيبي الله إلى الدهر.", ref: "المزامير 73:26" },
        { text: "فقال لي: تكفيك نعمتي، لأن قوتي في الضعف تكمل.", ref: "2 كورنثوس 12:9" },
        { text: "وأما منتظرو الرب فيجددون قوة. يرفعون أجنحة كالنسور. يركضون ولا يتعبون، يمشون ولا يعيون.", ref: "إشعياء 40:31" },
        { text: "يعطي المعيي قدرة، ولعديم القوة يكثر شدة.", ref: "إشعياء 40:29" },
        { text: "أستطيع كل شيء في المسيح الذي يقويني.", ref: "فيلبي 4:13" },
        { text: "أرفع عيني إلى الجبال، من حيث يأتي عوني. معونتي من عند الرب صانع السماوات والأرض.", ref: "المزامير 121:1-2" },
        { text: "لا تهتموا بشيء، بل في كل شيء بالصلاة والدعاء مع الشكر، لتعلم طلباتكم لدى الله.", ref: "فيلبي 4:6-7" },
        { text: "لا تخف لأني معك. لا تتلفت لأني إلهك. قد أيدتك وأعنتك وعضدتك بيمين بري.", ref: "إشعياء 41:10" },
        { text: "عند كثرة همومي في داخلي، تعزياتك تلذذ نفسي.", ref: "المزامير 94:19" },
        { text: "ملقين كل همكم عليه، لأنه هو يعتني بكم.", ref: "1 بطرس 5:7" },
        { text: "أيضاً إذا سرت في وادي ظل الموت لا أخاف شراً، لأنك أنت معي. عصاك وعكازك هما يعزيانني.", ref: "المزامير 23:4" },
        { text: "لأن الله لم يعطنا روح الفشل، بل روح القوة والمحبة والنصح.", ref: "2 تيموثاوس 1:7" },
        { text: "لأن الصديق يسقط سبع مرات ويقوم، أما الأشرار فيعثرون بالشر.", ref: "الأمثال 24:16" },
        { text: "إنه من إحسانات الرب أننا لم نفن، لأن مراحمه لا تزول. هي جديدة في كل صباح. كثيرة أمانتك.", ref: "المراثي 3:22-23" },
        { text: "لا تشمتي بي يا عدوتي. إذا سقطت أقوم. إذا جلست في الظلمة فالرب نور لي.", ref: "ميخا 7:8" },
        { text: "قريب هو الرب من المنكسري القلوب، ويخلص المنسحقي الروح.", ref: "المزامير 34:18" },
        { text: "إذاً إن كان أحد في المسيح فهو خليقة جديدة. الأشياء العتيقة قد مضت، هوذا الكل قد صار جديداً.", ref: "2 كورنثوس 5:17" },
        { text: "أنتم من الله أيها الأولاد، وقد غلبتموهم لأن الذي فيكم أعظم من الذي في العالم.", ref: "1 يوحنا 4:4" },
        { text: "إذا اجتزت في المياه فأنا معك، وفي الأنهار فلا تغمرك. إذا مشيت في النار فلا تلذع، واللهيب لا يحرقك.", ref: "إشعياء 43:2" },
        { text: "الله لنا ملجأ وقوة. عوناً في الضيقات وجد شديداً.", ref: "المزامير 46:1" },
        { text: "من أقصى الأرض أصرخ إليك إذا غشي على قلبي. إلى صخرة أرفع مني تهديني.", ref: "المزامير 61:2" },
        { text: "قد كلمتكم بهذا ليكون لكم فيّ سلام. في العالم سيكون لكم ضيق، ولكن ثقوا: أنا قد غلبت العالم.", ref: "يوحنا 16:33" }
    ],
    "pt": [
        { text: "Aquietai-vos e sabei que eu sou Deus.", ref: "Salmos 46:10" },
        { text: "O Senhor pelejará por vós; e vós vos calareis.", ref: "Êxodo 14:14" },
        { text: "Somente em Deus, ó minha alma, espera silenciosa; dele vem a minha salvação. Só ele é a minha rocha e a minha salvação.", ref: "Salmos 62:1-2" },
        { text: "Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei.", ref: "Mateus 11:28" },
        { text: "Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize.", ref: "João 14:27" },
        { text: "Tenho posto o Senhor continuamente diante de mim; por isso que ele está à minha mão direita, nunca vacilarei.", ref: "Salmos 16:8" },
        { text: "Não vos sobreveio tentação, senão humana; mas fiel é Deus, que não vos deixará tentar acima do que podeis.", ref: "1 Coríntios 10:13" },
        { text: "Sujeitai-vos, pois, a Deus, resisti ao diabo, e ele fugirá de vós.", ref: "Tiago 4:7" },
        { text: "Porque as armas da nossa milícia não são carnais, mas sim poderosas em Deus para destruição das fortalezas.", ref: "2 Coríntios 10:4" },
        { text: "Estai, pois, firmes na liberdade com que Cristo nos libertou, e não torneis a meter-vos debaixo do jugo da servidão.", ref: "Gálatas 5:1" },
        { text: "Se, pois, o Filho vos libertar, verdadeiramente sereis livres.", ref: "João 8:36" },
        { text: "Tu és o meu refúgio e o meu escudo; espero na tua palavra.", ref: "Salmos 119:114" },
        { text: "A minha carne e o meu coração desfalecem; mas Deus é a fortaleza do meu coração, e a minha porção para sempre.", ref: "Salmos 73:26" },
        { text: "E disse-me: A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza.", ref: "2 Coríntios 12:9" },
        { text: "Mas os que esperam no Senhor renovarão as forças, subirão com asas como águias.", ref: "Isaías 40:31" },
        { text: "Dá força ao cansado, e multiplica as forças ao que não tem nenhum vigor.", ref: "Isaías 40:29" },
        { text: "Posso todas as coisas naquele que me fortalece.", ref: "Filipenses 4:13" },
        { text: "Levantarei os meus olhos para os montes, de onde vem o meu socorro. O meu socorro vem do Senhor.", ref: "Salmos 121:1-2" },
        { text: "Não estejais inquietos por coisa alguma; antes as vossas petições sejam em tudo conhecidas diante de Deus pela oração e súplica.", ref: "Filipenses 4:6-7" },
        { text: "Não temas, porque eu sou contigo; não te assombres, porque eu sou teu Deus; eu te fortaleço, e te ajudo.", ref: "Isaías 41:10" },
        { text: "Na multidão dos meus pensamentos dentro de mim, as tuas consolações recrearam a minha alma.", ref: "Salmos 94:19" },
        { text: "Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.", ref: "1 Pedro 5:7" },
        { text: "Ainda que eu andasse pelo vale da sombra da morte, não temeria mal algum, porque tu estás comigo.", ref: "Salmos 23:4" },
        { text: "Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação.", ref: "2 Timóteo 1:7" },
        { text: "Porque sete vezes cairá o justo, e se levantará; mas os ímpios tropeçarão no mal.", ref: "Provérbios 24:16" },
        { text: "As misericórdias do Senhor são a causa de não sermos consumidos, porque as suas misericórdias não têm fim; novas são cada manhã.", ref: "Lamentações 3:22-23" },
        { text: "Ó inimiga minha, não te alegres a meu respeito; ainda que eu tenha caído, levantar-me-ei.", ref: "Miquéias 7:8" },
        { text: "Perto está o Senhor dos que têm o coração quebrantado, e salva os contritos de espírito.", ref: "Salmos 34:18" },
        { text: "Assim que, se alguém está em Cristo, nova criatura é; as coisas velhas já passaram; eis que tudo se fez novo.", ref: "2 Coríntios 5:17" },
        { text: "Filhinhos, sois de Deus, e já os tendes vencido; porque maior é o que está em vós do que o que está no mundo.", ref: "1 João 4:4" },
        { text: "Quando passares pelas águas estarei contigo, e quando pelos rios, eles não te submergirão.", ref: "Isaías 43:2" },
        { text: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.", ref: "Salmos 46:1" },
        { text: "Desde o fim da terra clamarei a ti, quando o meu coração estiver desmaiado; leva-me para a rocha que é mais alta do que eu.", ref: "Salmos 61:2" },
        { text: "Tenho-vos dito isto, para que em mim tenhais paz; no mundo tereis aflições, mas tende bom ânimo, eu venci o mundo.", ref: "João 16:33" }
    ],
    "ru": [
        { text: "Остановитесь и познайте, что Я - Бог.", ref: "Псалтирь 46:10" },
        { text: "Господь будет поборать за вас, а вы будьте спокойны.", ref: "Исход 14:14" },
        { text: "Только в Боге успокаивается душа моя: от Него спасение мое. Только Он - твердыня моя и спасение мое, убежище мое: не поколеблюсь более.", ref: "Псалтирь 62:1-2" },
        { text: "Придите ко Мне все труждающиеся и обремененные, и Я успокою вас.", ref: "От Матфея 11:28" },
        { text: "Мир оставляю вам, мир Мой даю вам; не так, как мир дает, Я даю вам. Да не смущается сердце ваше и да не устрашается.", ref: "От Иоанна 14:27" },
        { text: "Всегда видел я пред собою Господа, ибо Он одесную меня; не поколеблюсь.", ref: "Псалтирь 16:8" },
        { text: "Вас постигло искушение не иное, как человеческое; и верен Бог, Который не попустит вам быть искушаемыми сверх сил.", ref: "1 Коринфянам 10:13" },
        { text: "Итак покоритесь Богу; противостаньте диаволу, и убежит от вас.", ref: "Иакова 4:7" },
        { text: "Оружия воинствования нашего не плотские, но сильные Богом на разрушение твердынь.", ref: "2 Коринфянам 10:4" },
        { text: "Итак стойте в свободе, которую даровал нам Христос, и не подвергайтесь опять игу рабства.", ref: "К Галатам 5:1" },
        { text: "Итак, если Сын освободит вас, то истинно свободны будете.", ref: "От Иоанна 8:36" },
        { text: "Ты покров мой и щит мой; на слово Твое уповаю.", ref: "Псалтирь 119:114" },
        { text: "Изнемогает плоть моя и сердце мое: Бог твердыня сердца моего и часть моя вовек.", ref: "Псалтирь 73:26" },
        { text: "Но Господь сказал мне: 'довольно для тебя благодати Моей, ибо сила Моя совершается в немощи'.", ref: "2 Коринфянам 12:9" },
        { text: "А надеющиеся на Господа обновят силы: поднимут крылья, как орлы, потекут - и не устанут, пойдут - и не утомятся.", ref: "Исаия 40:31" },
        { text: "Он дает утомленному силу, и изнемогшему дарует крепость.", ref: "Исаия 40:29" },
        { text: "Все могу в укрепляющем меня Иисусе Христе.", ref: "К Филиппийцам 4:13" },
        { text: "Воздвигаю очи мои к горам, откуда придет помощь моя. Помощь моя от Господа, сотворившего небо и землю.", ref: "Псалтирь 121:1-2" },
        { text: "Не заботьтесь ни о чем, но всегда в молитве и прошении с благодарением открывайте свои желания пред Богом.", ref: "К Филиппийцам 4:6-7" },
        { text: "Не бойся, ибо Я с тобою; не смущайся, ибо Я Бог твой; Я укреплю тебя, и помогу тебе, и поддержу тебя десницею правды Моей.", ref: "Исаия 41:10" },
        { text: "При умножении скорбей моих в сердце моем, утешения Твои услаждают душу мою.", ref: "Псалтирь 94:19" },
        { text: "Все заботы ваши возложите на Него, ибо Он печется о вас.", ref: "1 Петра 5:7" },
        { text: "Если я пойду и долиною смертной тени, не убоюсь зла, потому что Ты со мной; Твой жезл и Твой посох - они успокаивают меня.", ref: "Псалтирь 23:4" },
        { text: "Ибо дал нам Бог духа не боязни, но силы и любви и целомудрия.", ref: "2 Тимофею 1:7" },
        { text: "Ибо семь раз упадет праведник, и встанет; а нечестивые впадут в погибель.", ref: "Притчи 24:16" },
        { text: "По милости Господа мы не исчезли, ибо милосердие Его не истощилось. Оно обновляется каждое утро; велика верность Твоя!", ref: "Плач Иеремии 3:22-23" },
        { text: "Не радуйся о мне, неприятельница моя! хотя я упал, но встану; хотя я во мраке, но Господь свет для меня.", ref: "Михей 7:8" },
        { text: "Близок Господь к сокрушенным сердцем и смиренных духом спасет.", ref: "Псалтирь 34:18" },
        { text: "Итак, кто во Христе, тот новая тварь; древнее прошло, теперь все новое.", ref: "2 Коринфянам 5:17" },
        { text: "Дети! вы от Бога, и победили их; ибо Тот, Кто в вас, больше того, кто в мире.", ref: "1 Иоанна 4:4" },
        { text: "Будешь ли переходить через воды, Я с тобою, - через реки ли, они не потопят тебя; пойдешь ли через огонь, не обожжешься, и пламя не опалит тебя.", ref: "Исаия 43:2" },
        { text: "Бог нам прибежище и сила, скорый помощник в бедах.", ref: "Псалтирь 46:1" },
        { text: "От конца земли взываю к Тебе в унынии сердца моего; возведи меня на скалу, для меня недосягаемую.", ref: "Псалтирь 61:2" },
        { text: "Сие сказал Я вам, чтобы вы имели во Мне мир. В мире будете иметь скорбь; но мужайтесь: Я победил мир.", ref: "От Иоанна 16:33" }
    ],
    "ja": [
        { text: "静まって、わたしが神であることを知れ。", ref: "詩篇 46:10" },
        { text: "主があなたがたのために戦われる。あなたがたは黙っていなければならない。", ref: "出エジプト記 14:14" },
        { text: "私のたましいは黙って神を待ち望む。私の救いは神から来る。神こそ、私の岩、私の救い、私のやぐら。私は決して、揺るがされることはない。", ref: "詩篇 62:1-2" },
        { text: "すべて、疲れた人、重荷を負っている人は、わたしのところに来なさい。わたしがあなたがたを休ませてあげます。", ref: "マタイの福音書 11:28" },
        { text: "わたしは、あなたがたに平安を残します。わたしは、あなたがたにわたしの平安を与えます。わたしがあなたがたに与えるのは、世が与えるのとは違います。あなたがたは心を騒がしてはなりません。恐れてはなりません。", ref: "ヨハネの福音書 14:27" },
        { text: "私はいつも、私の前に主を置いた。主が私の右におられるので、私は揺るがされることがない。", ref: "詩篇 16:8" },
        { text: "あなたがたの会った試練はみな人の知らないようなものではありません。神は真実な方ですから、あなたがたを耐えられないほどの試練に会わせることはなさいません。", ref: "第1コリント 10:13" },
        { text: "ですから、神に従いなさい。そして、悪魔に立ち向かいなさい。そうすれば、悪魔はあなたがたから逃げ去ります。", ref: "ヤコブ 4:7" },
        { text: "私たちの戦いの武器は、肉の物ではなく、神の御前で、要塞をも破るほどに力のあるものです。", ref: "第2コリント 10:4" },
        { text: "キリストは、自由を得させるために、私たちを解放してくださいました。ですから、あなたがたは、しっかり立って、またと奴隷のくびきを負わせられないようにしなさい。", ref: "ガラテヤ 5:1" },
        { text: "ですから、もし子があなたがたを自由にするなら、あなたがたは本当に自由なのです。", ref: "ヨハネの福音書 8:36" },
        { text: "あなたは私の隠れ場、私の盾。私は、あなたのみことばを待ち望みます。", ref: "詩篇 119:114" },
        { text: "私の肉と私の心は尽き果てます。しかし神は、とこしえに私の心の岩、私の分の土地です。", ref: "詩篇 73:26" },
        { text: "しかし、主は、「わたしの恵みは、あなたに十分である。というのは、わたしの力は、弱さのうちに完全に現れるからである」と言われたのです。", ref: "第2コリント 12:9" },
        { text: "しかし、主を待ち望む者は新しく力を得、鷲のように翼をかって上ることができる。走ってもたゆまず、歩いても疲れない。", ref: "イザヤ 40:31" },
        { text: "疲れた者には力を与え、精力のない者には活気をつける。", ref: "イザヤ 40:29" },
        { text: "私は、私を強くしてくださる方によって、どんなことでもできるのです。", ref: "ピリピ 4:13" },
        { text: "私は山に向かって目を上げる。私の助けは、どこから来るのだろうか。私の助けは、天地を造られた主から来る。", ref: "詩篇 121:1-2" },
        { text: "何も思い煩わないで、あらゆるばあいに、感謝をもってささげる祈りと願いによって、あなたがたの願い事を神に知っていただきなさい。", ref: "ピリピ 4:6-7" },
        { text: "恐れるな。わたしはあなたとともにいる。たじろぐな。わたしがあなたの神だから。わたしはあなたを強め、あなたを助け、わたしの義の右の手で、あなたを守る。", ref: "イザヤ 41:10" },
        { text: "私の心のうちに思い煩いが多いとき、あなたの慰めが私のたましいを喜ばせます。", ref: "詩篇 94:19" },
        { text: "あなたがたの思い煩いを、いっさい神にゆだねなさい。神があなたがたのことを心配してくださるからです。", ref: "第1ペテロ 5:7" },
        { text: "たとい、死の陰の谷を歩くことがあっても、私はわざわいを恐れません。あなたが私とともにおられますから。あなたのむちとあなたの杖、それが私の慰めです。", ref: "詩篇 23:4" },
        { text: "神が私たちに与えてくださったものは、おくびょうの霊ではなく、力と愛と慎みとの霊です。", ref: "第2テモテ 1:7" },
        { text: "正しい者は七度倒れても、また起き上がるからだ。悪者はわざわいによって滅びる。", ref: "箴言 24:16" },
        { text: "私たちが滅びうせなかったのは、主の恵みによる。主のあわれみは尽きないからだ。それは朝ごとに新しい。「あなたの真実は力強い。」", ref: "哀歌 3:22-23" },
        { text: "私の敵よ。私のことで喜ぶな。私は倒れても、起き上がる。暗やみの中にすわっていても、主は私の光である。", ref: "ミカ 7:8" },
        { text: "主は心の打ち砕かれた者の近くにおられ、霊の砕かれた者を救われる。", ref: "詩篇 34:18" },
        { text: "だれでもキリストのうちにあるなら、その人は新しく造られた者です。古いものは過ぎ去って、見よ、すべてが新しくなりました。", ref: "第2コリント 5:17" },
        { text: "子どもたちよ。あなたがたは神から出た者です。そして彼らに勝ったのです。あなたがたのうちにおられる方が、この世のうちにいる、あの者よりも力があるからです。", ref: "第1ヨハネ 4:4" },
        { text: "あなたが水の中を過ぎるときも、わたしはあなたとともにおり、川を渡るときも、あなたは押し流されず、火の中を歩いても焼かれず、炎はあなたに燃えつかない。", ref: "イザヤ 43:2" },
        { text: "神はわれらの避け所、また力。苦しむとき、そこにある助け。", ref: "詩篇 46:1" },
        { text: "私の心が衰え果てるとき、私は地のはてからあなたに呼ばわります。どうか、私のそびえ立つ岩に私を導いてください。", ref: "詩篇 61:2" },
        { text: "わたしがこれらのことをあなたがたに話したのは、あなたがたがわたしにあって平安を持つためです。あなたがたは、世にあっては患難があります。しかし、勇敢でありなさい。わたしはすでに世に勝ったのです。", ref: "ヨハネの福音書 16:33" }
    ],
    "he": [
        { text: "הרפו ודעו כי אנוכי אלוהים.", ref: "תהילים מ\"ו:10" },
        { text: "יהוה ילחם לכם, ואתם תחרישון.", ref: "שמות י\"ד:14" },
        { text: "אך אל אלוהים דומיה נפשי, ממנו ישועתי. אך הוא צורי וישועתי, משגבי לא אמוט רבה.", ref: "תהילים ס\"ב:2-3" },
        { text: "בואו אליי כל העמלים והטעונים ואני אניח לכם.", ref: "מתי י\"א:28" },
        { text: "שלום אני משאיר לכם, את שלומי אני נותן לכם; לא כדרך שהעולם נותן אני נותן לכם. אל יבהל לבבכם ואל יירא.", ref: "יוחנן י\"ד:27" },
        { text: "שיוויתי יהוה לנגדי תמיד, כי מימיני בל אמוט.", ref: "תהילים ט\"ז:8" },
        { text: "שום ניסיון לא בא עליכם מלבד זה שהוא אנושי; ונאמן הוא האלוהים שלא יניח לכם להתנסות למעלה מיכולתכם, אלא יכין עם הניסיון גם את דרך המוצא כדי שתוכלו לעמוד בו.", ref: "הראשונה לקורינתים י':13" },
        { text: "לכן היכנעו לאלוהים. התייצבו נגד השטן ויברח מפניכם.", ref: "יעקב ד':7" },
        { text: "כי כלי נשקנו אינם גשמיים, אלא חזקים הם באלוהים להרוס מבצרים.", ref: "השנייה לקורינתים י':4" },
        { text: "למען החירות שחרר אותנו המשיח. לכן עימדו היטב ואל תירתמו שוב לעול העבדות.", ref: "גלטים ה':1" },
        { text: "לכן אם הבן ישחרר אתכם, באמת בני חורין תהיו.", ref: "יוחנן ח':36" },
        { text: "סיתרי ומגיני אתה, לדברך ייחלתי.", ref: "תהילים קי\"ט:114" },
        { text: "כלה שארי ולבבי, צור לבבי וחלקי אלוהים לעולם.", ref: "תהילים ע\"ג:26" },
        { text: "והוא אמר אלי: די לך חסדי, כי כוחי בחולשה יושלם.", ref: "השנייה לקורינתים י\"ב:9" },
        { text: "וקווי יהוה יחליפו כוח, יעלו אבר כנשרים, ירוצו ולא ייגעו, ילכו ולא ייעפו.", ref: "ישעיהו מ':31" },
        { text: "נותן ליעף כוח, ולאין אונים עוצמה ירבה.", ref: "ישעיהו מ':29" },
        { text: "הכל אני יכול בעזרתו של הנותן בי כוח.", ref: "פיליפים ד':13" },
        { text: "אשא עיניי אל ההרים, מאין יבוא עזרי? עזרי מעם יהוה, עושה שמיים וארץ.", ref: "תהילים קכ\"א:1-2" },
        { text: "אל תדאגו לשום דבר, אלא בכל דבר הציגו משאלותיכם לאלוהים בתפילה ובתחנונים ובהודיה.", ref: "פיליפים ד':6-7" },
        { text: "אל תירא כי עימך אני, אל תשתע כי אני אלוהיך. אימצתיך, אף עזרתיך, אף תמכתיך בימין צידקי.", ref: "ישעיהו מ\"א:10" },
        { text: "ברוב שרעפיי בקרבי, תנחומיך ישעשעו נפשי.", ref: "תהילים צ\"ד:19" },
        { text: "השליכו עליו את כל יהבכם, כי הוא דואג לכם.", ref: "הראשונה לפטרוס ה':7" },
        { text: "גם כי אלך בגיא צלמוות לא אירא רע כי אתה עימדי, שיבטך ומשענתך המה ינחמוני.", ref: "תהילים כ\"ג:4" },
        { text: "כי לא נתן לנו האלוהים רוח של פחד, אלא רוח של גבורה ואהבה ויישוב הדעת.", ref: "השנייה לטימותיוס א':7" },
        { text: "כי שבע יפול צדיק וקם, ורשעים ייכשלו ברעה.", ref: "משלי כ\"ד:16" },
        { text: "חסדי יהוה כי לא תמנו, כי לא כלו רחמיו. חדשים לבקרים, רבה אמונתך.", ref: "איכה ג':22-23" },
        { text: "אל תשמחי אויבתי לי, כי נפלתי קמתי, כי אשב בחושך יהוה אור לי.", ref: "מיכה ז':8" },
        { text: "קרוב יהוה לנשברי לב, ואת דכאי רוח יושיע.", ref: "תהילים ל\"ד:18" },
        { text: "לכן אם מישהו במשיח, הרי הוא בריאה חדשה; הישנות חלפו, והנה הכל נהיה חדש.", ref: "השנייה לקורינתים ה':17" },
        { text: "אתם מאלוהים, ילדיי, וניצחתם אותם, כי גדול אשר בכם מאשר בעולם.", ref: "הראשונה ליוחנן ד':4" },
        { text: "כי תעבור במים איתך אני, ובנהרות לא ישטפוך. כי תלך במו אש לא תיכווה, ולהבה לא תבער בך.", ref: "ישעיהו מ\"ג:2" },
        { text: "אלוהים לנו מחסה ועוז, עזרה בצרות נמצא מאוד.", ref: "תהילים מ\"ו:2" },
        { text: "מקצה הארץ אליך אקרא בעטוף ליבי, בצור ירום ממני תנחני.", ref: "תהילים ס\"א:3" },
        { text: "את אלה דיברתי אליכם למען יהיה לכם שלום בי. בעולם צפויה לכם צרה, אך התעודדו: אני ניצחתי את העולם.", ref: "יוחנן ט\"ז:33" }
    ],
    "tl": [
        { text: "Pumayapa kayo at kilalanin na ako ang Diyos.", ref: "Awit 46:10" },
        { text: "Ipaglalaban kayo ng Panginoon; kailangan lamang ninyong maging mahinahon.", ref: "Exodo 14:14" },
        { text: "Sa Diyos lamang matatagpuan ng aking kaluluwa ang kapahingahan; ang aking kaligtasan ay nagmumula sa kanya. Siya lamang ang aking bato at aking kaligtasan; siya ang aking muog, hindi ako matitinag.", ref: "Awit 62:1-2" },
        { text: "Lumapit kayo sa akin, kayong lahat na napapagod at nabibigatan, at bibigyan ko kayo ng kapahingahan.", ref: "Mateo 11:28" },
        { text: "Kapayapaan ang iniiwan ko sa inyo; ang aking kapayapaan ang ibinibigay ko sa inyo. Hindi ako nagbibigay sa inyo gaya ng ibinibigay ng sanlibutan. Huwag mabagabag ang inyong mga puso at huwag kayong matakot.", ref: "Juan 14:27" },
        { text: "Lagi kong inilalagay ang Panginoon sa aking harapan. Dahil siya ay nasa aking kanan, hindi ako matitinag.", ref: "Awit 16:8" },
        { text: "Walang pagsubok na dumating sa inyo na hindi pangkaraniwan sa tao. Ngunit tapat ang Diyos; hindi niya hahayaang subukin kayo nang higit sa inyong makakaya. Ngunit kapag kayo ay sinubok, magbibigay rin siya ng daan upang makatakas, upang ito ay inyong mapagtiisan.", ref: "1 Corinto 10:13" },
        { text: "Magpasakop nga kayo sa Diyos. Labanan ninyo ang diyablo, at lalayo siya sa inyo.", ref: "Santiago 4:7" },
        { text: "Ang mga sandatang ginagamit natin sa pakikipaglaban ay hindi mga sandata ng sanlibutan. Sa halip, mayroon silang kapangyarihan mula sa Diyos upang wasakin ang mga kuta.", ref: "2 Corinto 10:4" },
        { text: "Para sa kalayaan tayo'y pinalaya ni Cristo. Kaya't magpakatatag kayo, at huwag na kayong muling pasakop pamatok ng pagkaalipin.", ref: "Galacia 5:1" },
        { text: "Kaya't kung palalayain kayo ng Anak, kayo ay tunay na magiging malaya.", ref: "Juan 8:36" },
        { text: "Ikaw ang aking kanlungan at aking kalasag; inilagay ko ang aking pag-asa sa iyong salita.", ref: "Awit 119:114" },
        { text: "Maaaring manghina ang aking laman at ang aking puso, ngunit ang Diyos ang lakas ng aking puso at aking bahagi magpakailanman.", ref: "Awit 73:26" },
        { text: "Ngunit sinabi niya sa akin, 'Ang aking biyaya ay sapat na sa iyo, sapagkat ang aking kapangyarihan ay nagiging perpekto sa kahinaan.'", ref: "2 Corinto 12:9" },
        { text: "Ngunit ang mga umaasa sa Panginoon ay magpapanibago ng kanilang lakas. Sila ay paiilanglang sa mga pakpak na parang mga agila; sila ay tatakbo at hindi mapapagod, sila ay lalakad at hindi manghihina.", ref: "Isaias 40:31" },
        { text: "Siya ay nagbibigay ng lakas sa mga pagod at nagdaragdag ng kapangyarihan sa mga mahina.", ref: "Isaias 40:29" },
        { text: "Kaya kong gawin ang lahat ng ito sa pamamagitan niya na nagbibigay sa akin ng lakas.", ref: "Filipos 4:13" },
        { text: "Itinataas ko ang aking mga mata sa mga bundok—saan manggagaling ang aking tulong? Ang aking tulong ay nagmumula sa Panginoon, na Lumikha ng langit at lupa.", ref: "Awit 121:1-2" },
        { text: "Huwag kayong mabalisa tungkol sa anumang bagay, kundi sa bawat sitwasyon, sa pamamagitan ng panalangin at pagsamo, na may pagpapasalamat, iharap ninyo ang inyong mga kahilingan sa Diyos.", ref: "Filipos 4:6-7" },
        { text: "Kaya't huwag kang matakot, sapagkat ako'y sumasaiyo; huwag kang manlupaypay, sapagkat ako ang iyong Diyos. Palalakasin kita at tutulungan kita; aalalayan kita ng aking matuwid na kanang kamay.", ref: "Isaias 41:10" },
        { text: "Nang ang pagkabalisa ay matindi sa loob ko, ang iyong pag-aliw ay nagdulot sa akin ng kagalakan.", ref: "Awit 94:19" },
        { text: "Ipagkatiwala ninyo sa kanya ang lahat ng inyong mga kabalisahan sapagkat siya ay nagmamalasakit sa inyo.", ref: "1 Pedro 5:7" },
        { text: "Kahit na lumakad ako sa pinakamadilim na lambak, hindi ako matatakot sa kasamaan, sapagkat ikaw ay kasama ko; ang iyong pamalo at ang iyong tungkod, inaaliw nila ako.", ref: "Awit 23:4" },
        { text: "Sapagkat ang Espiritung ibinigay sa atin ng Diyos ay hindi nagpapaduwag sa atin, kundi nagbibigay ng kapangyarihan, pag-ibig at pagpipigil sa sarili.", ref: "2 Timoteo 1:7" },
        { text: "Sapagkat bagaman ang matuwid ay nabubuwal ng pitong ulit, sila ay muling bumabangon, ngunit ang masama ay natitisod pagdating ng kapahamakan.", ref: "Kawikaan 24:16" },
        { text: "Ang tapat na pag-ibig ng Panginoon ay hindi kailanman nagwawakas; ang kanyang mga awa ay hindi kailanman nauubos; ang mga ito ay bago tuwing umaga; dakila ang iyong katapatan.", ref: "Panaghoy 3:22-23" },
        { text: "Huwag kang magalak sa akin, aking kaaway! Bagaman ako'y nabuwal, ako'y babangon. Bagaman ako'y nakaupo sa kadiliman, ang Panginoon ang magiging aking liwanag.", ref: "Mikas 7:8" },
        { text: "Ang Panginoon ay malapit sa mga may wasak na puso at nagliligtas sa mga may durog na espiritu.", ref: "Awit 34:18" },
        { text: "Kaya't kung ang sinuman ay na kay Cristo, ang bagong nilalang ay dumating na: Ang luma ay lumipas na, ang bago ay narito na!", ref: "2 Corinto 5:17" },
        { text: "Kayong mga mahal kong anak, ay mula sa Diyos at napagtagumpayan ninyo sila, sapagkat ang nasa inyo ay mas dakila kaysa sa nasa sanlibutan.", ref: "1 Juan 4:4" },
        { text: "Kapag dumaan ka sa mga tubig, ako'y makakasama mo; at kapag dumaan ka sa mga ilog, hindi ka nila tatangayin. Kapag lumakad ka sa apoy, hindi ka masusunog; hindi ka tutupukin ng alab.", ref: "Isaias 43:2" },
        { text: "Ang Diyos ang ating kanlungan at lakas, laging nakahandang saklolo sa panahon ng kagipitan.", ref: "Awit 46:1" },
        { text: "Mula sa mga dulo ng daigdig ay tumatawag ako sa iyo, tumatawag ako habang nanlulupaypay ang aking puso; akayin mo ako sa batong mas mataas kaysa akin.", ref: "Awit 61:2" },
        { text: "Sinabi ko sa inyo ang mga bagay na ito, upang sa akin ay magkaroon kayo ng kapayapaan. Sa mundong ito ay magkakaroon kayo ng kapighatian. Ngunit lakasan ninyo ang inyong loob! Napagtagumpayan ko na ang sanlibutan.", ref: "Juan 16:33" }
    ],
    "it": [
        { text: "Fermatevi e sappiate che io sono Dio.", ref: "Salmi 46:10" },
        { text: "Il Signore combatterà per voi, e voi starete tranquilli.", ref: "Esodo 14:14" },
        { text: "Solo in Dio riposa l'anima mia; da lui viene la mia salvezza. Solo lui è la mia ròcca e la mia salvezza; egli è il mio rifugio, non potrò vacillare.", ref: "Salmi 62:1-2" },
        { text: "Venite a me, voi tutti che siete affaticati e oppressi, e io vi darò riposo.", ref: "Matteo 11:28" },
        { text: "Vi lascio pace; vi do la mia pace. Io non vi do come il mondo dà. Il vostro cuore non sia turbato e non si sgomenti.", ref: "Giovanni 14:27" },
        { text: "Io ho sempre posto il Signore davanti agli occhi miei; poiché egli è alla mia destra, io non sarò smosso.", ref: "Salmi 16:8" },
        { text: "Nessuna tentazione vi ha colti, che non sia stata umana; però Dio è fedele e non permetterà che siate tentati oltre le vostre forze.", ref: "1 Corinzi 10:13" },
        { text: "Sottomettetevi dunque a Dio; ma resistete al diavolo, ed egli fuggirà da voi.", ref: "Giacomo 4:7" },
        { text: "Infatti le armi della nostra guerra non sono carnali, ma hanno da Dio il potere di distruggere le fortezze.", ref: "2 Corinzi 10:4" },
        { text: "Cristo ci ha liberati perché fossimo liberi; state dunque saldi e non lasciatevi porre di nuovo sotto il giogo della schiavitù.", ref: "Galati 5:1" },
        { text: "Se dunque il Figlio vi farà liberi, sarete veramente liberi.", ref: "Giovanni 8:36" },
        { text: "Tu sei il mio rifugio e il mio scudo; io spero nella tua parola.", ref: "Salmi 119:114" },
        { text: "La mia carne e il mio cuore possono venir meno, ma Dio è la ròcca del mio cuore e la mia parte di retaggio, in eterno.", ref: "Salmi 73:26" },
        { text: "Ed egli mi ha detto: «La mia grazia ti basta, perché la mia potenza si dimostra perfetta nella debolezza».", ref: "2 Corinzi 12:9" },
        { text: "Ma quelli che sperano nel Signore acquistano nuove forze, si alzano a volo come aquile, corrono e non si stancano, camminano e non si affaticano.", ref: "Isaia 40:31" },
        { text: "Egli dà forza allo stanco e accresce il vigore a colui che è spossato.", ref: "Isaia 40:29" },
        { text: "Io posso ogni cosa in colui che mi fortifica.", ref: "Filippesi 4:13" },
        { text: "Alzo gli occhi verso i monti... Da dove mi verrà l'aiuto? Il mio aiuto vien dal Signore, che ha fatto il cielo e la terra.", ref: "Salmi 121:1-2" },
        { text: "Non angustiatevi di nulla, ma in ogni cosa fate conoscere le vostre richieste a Dio in preghiere e suppliche, accompagnate da ringraziamenti.", ref: "Filippesi 4:6-7" },
        { text: "Tu, non temere, perché io sono con te; non ti smarrire, perché io sono il tuo Dio; io ti fortifico, io ti soccorro, io ti sostengo con la destra della mia giustizia.", ref: "Isaia 41:10" },
        { text: "Quando ero turbato da grandi preoccupazioni, i tuoi conforti hanno alleviato l'anima mia.", ref: "Salmi 94:19" },
        { text: "Gettando su di lui ogni vostra preoccupazione, perché egli ha cura di voi.", ref: "1 Pietro 5:7" },
        { text: "Quand'anche camminassi nella valle dell'ombra della morte, io non temerei alcun male, perché tu sei con me; il tuo bastone e la tua verga mi dànno sicurezza.", ref: "Salmi 23:4" },
        { text: "Dio infatti ci ha dato uno spirito non di timidezza, ma di forza, d'amore e di autocontrollo.", ref: "2 Timoteo 1:7" },
        { text: "Perché il giusto cade sette volte e si rialza, ma gli empi sono travolti dalla sventura.", ref: "Proverbi 24:16" },
        { text: "È una grazia del Signore che non siamo stati interamente distrutti; le sue compassioni infatti non sono esaurite. Si rinnovano ogni mattina. Grande è la tua fedeltà!", ref: "Lamentazioni 3:22-23" },
        { text: "Non rallegrarti di me, o mia nemica! Se sono caduta, mi rialzerò; se siedo nelle tenebre, il Signore è la mia luce.", ref: "Michea 7:8" },
        { text: "Il Signore è vicino a quelli che hanno il cuore afflitto, salva gli umili di spirito.", ref: "Salmi 34:18" },
        { text: "Se dunque uno è in Cristo, egli è una nuova creatura; le cose vecchie sono passate: ecco, sono diventate nuove.", ref: "2 Corinzi 5:17" },
        { text: "Voi siete da Dio, figlioli, e li avete vinti, perché colui che è in voi è più grande di colui che è nel mondo.", ref: "1 Giovanni 4:4" },
        { text: "Quando passerai attraverso le acque, io sarò con te; o attraverserai i fiumi, non ti sommergeranno; quando camminerai nel fuoco, non ne sarai bruciato e la fiamma non ti consumerà.", ref: "Isaia 43:2" },
        { text: "Dio è per noi un rifugio e una forza, un aiuto sempre pronto nelle difficoltà.", ref: "Salmi 46:1" },
        { text: "Dall'estremità della terra io grido a te, con il cuore affranto; guidami tu alla ròcca ch'è troppo alta per me.", ref: "Salmi 61:2" },
        { text: "Vi ho detto queste cose, affinché abbiate pace in me. Nel mondo avrete tribolazione; ma fatevi coraggio, io ho vinto il mondo.", ref: "Giovanni 16:33" }
    ],
    "ko": [
        { text: "이르시기를 너희는 가만히 있어 내가 하나님 됨을 알지어다.", ref: "시편 46:10" },
        { text: "여호와께서 너희를 위하여 싸우시리니 너희는 가만히 있을지니라.", ref: "출애굽기 14:14" },
        { text: "나의 영혼이 잠잠히 하나님만 바람이여 나의 구원이 그에게서 나오는도다 오직 그만이 나의 반석이시요 나의 구원이시요 나의 요새이시니 내가 크게 흔들리지 아니하리로다.", ref: "시편 62:1-2" },
        { text: "수고하고 무거운 짐 진 자들아 다 내게로 오라 내가 너희를 쉬게 하리라.", ref: "마태복음 11:28" },
        { text: "평안을 너희에게 끼치노니 곧 나의 평안을 너희에게 주노라 내가 너희에게 주는 것은 세상이 주는 것과 같지 아니하니라 너희는 마음에 근심하지도 말고 두려워하지도 말라.", ref: "요한복음 14:27" },
        { text: "내가 여호와를 항상 내 앞에 모심이여 그가 나의 오른쪽에 계시므로 내가 흔들리지 아니하리로다.", ref: "시편 16:8" },
        { text: "사람이 감당할 시험 밖에는 너희가 당한 것이 없나니 오직 하나님은 미쁘사 너희가 감당하지 못할 시험 당함을 허락하지 아니하시고 시험 당할 즈음에 또한 피할 길을 내사 너희로 능히 감당하게 하시느니라.", ref: "고린도전서 10:13" },
        { text: "그런즉 너희는 하나님께 복종할지어다 마귀를 대적하라 그리하면 너희를 피하리라.", ref: "야고보서 4:7" },
        { text: "우리의 싸우는 무기는 육신에 속한 것이 아니요 오직 어떤 견고한 진도 무너뜨리는 하나님의 능력이라.", ref: "고린도후서 10:4" },
        { text: "그리스도께서 우리를 자유롭게 하려고 자유를 주셨으니 그러므로 굳건하게 서서 다시는 종의 멍에를 메지 말라.", ref: "갈라디아서 5:1" },
        { text: "그러므로 아들이 너희를 자유롭게 하면 너희가 참으로 자유로우리라.", ref: "요한복음 8:36" },
        { text: "주는 나의 은신처요 방패시라 내가 주의 말씀을 바라이나이다.", ref: "시편 119:114" },
        { text: "내 육체와 마음은 쇠약하나 하나님은 내 마음의 반석이시요 영원한 분깃이시라.", ref: "시편 73:26" },
        { text: "나에게 이르시기를 내 은혜가 네게 족하도다 이는 내 능력이 약한 데서 온전하여짐이라 하신지라.", ref: "고린도후서 12:9" },
        { text: "오직 여호와를 앙망하는 자는 새 힘을 얻으리니 독수리가 날개치며 올라감 같을 것이요 달음박질하여도 곤비하지 아니하겠고 걸어가도 피곤하지 아니하리로다.", ref: "이사야 40:31" },
        { text: "피곤한 자에게는 능력을 주시며 무능한 자에게는 힘을 더하시나니.", ref: "이사야 40:29" },
        { text: "내게 능력 주시는 자 안에서 내가 모든 것을 할 수 있느니라.", ref: "빌립보서 4:13" },
        { text: "내가 산을 향하여 눈을 들리라 나의 도움이 어디서 올까 나의 도움은 천지를 지으신 여호와에게서로다.", ref: "시편 121:1-2" },
        { text: "아무 것도 염려하지 말고 다만 모든 일에 기도와 간구로, 너희 구할 것을 감사함으로 하나님께 아뢰라.", ref: "빌립보서 4:6-7" },
        { text: "두려워하지 말라 내가 너와 함께 함이라 놀라지 말라 나는 네 하나님이 됨이라 내가 너를 굳세게 하리라 참으로 너를 도와 주리라 참으로 나의 의로운 오른손으로 너를 붙들리라.", ref: "이사야 41:10" },
        { text: "내 속에 근심이 많을 때에 주의 위안이 내 영혼을 즐겁게 하시나이다.", ref: "시편 94:19" },
        { text: "너희 염려를 다 주께 맡기라 이는 그가 너희를 돌보심이라.", ref: "베드로전서 5:7" },
        { text: "내가 사망의 음침한 골짜기로 다닐지라도 해를 두려워하지 않을 것은 주께서 나와 함께 하심이라 주의 지팡이와 막대기가 나를 안위하시나이다.", ref: "시편 23:4" },
        { text: "하나님이 우리에게 주신 것은 두려워하는 마음이 아니요 오직 능력과 사랑과 절제하는 마음이니.", ref: "디모데후서 1:7" },
        { text: "대저 의인은 일곱 번 넘어질지라도 다시 일어나려니와 악인은 재앙으로 말미암아 엎드러지느니라.", ref: "잠언 24:16" },
        { text: "여호와의 인자와 긍휼이 무궁하시므로 우리가 진멸되지 아니함이니이다 이것들이 아침마다 새로우니 주의 성실하심이 크시도소이다.", ref: "애가 3:22-23" },
        { text: "나의 대적이여 나로 말미암아 기뻐하지 말지어다 나는 엎드러질지라도 일어날 것이요 어두운 데에 앉을지라도 여호와께서 나의 빛이 되실 것임이로다.", ref: "미가 7:8" },
        { text: "여호와는 마음이 상한 자를 가까이 하시고 충심으로 통회하는 자를 구원하시는도다.", ref: "시편 34:18" },
        { text: "그런즉 누구든지 그리스도 안에 있으면 새로운 피조물이라 이전 것은 지나갔으니 보라 새 것이 되었도다.", ref: "고린도후서 5:17" },
        { text: "자녀들아 너희는 하나님께 속하였고 또 그들을 이기었나니 이는 너희 안에 계신 이가 세상에 있는 자보다 크심이라.", ref: "요한일서 4:4" },
        { text: "네가 물 가운데로 지날 때에 내가 너와 함께 할 것이라 강을 건널 때에 물이 너를 침몰하지 못할 것이며 네가 불 가운데로 지날 때에 타지도 아니할 것이요 불꽃이 너를 사르지도 못하리니.", ref: "이사야 43:2" },
        { text: "하나님은 우리의 피난처시요 힘이시니 환난 중에 만날 큰 도움이시라.", ref: "시편 46:1" },
        { text: "내 마음이 약해 질 때에 땅 끝에서부터 주께 부르짖으오리니 나보다 높은 바위에 나를 인도하소서.", ref: "시편 61:2" },
        { text: "이것을 너희에게 이르는 것은 너희로 내 안에서 평안을 누리게 하려 함이라 세상에서는 너희가 환난을 당하나 담대하라 내가 세상을 이기었노라.", ref: "요한복음 16:33" }
    ],
    "pl": [
        { text: "Zatrzymajcie się i uznajcie, że Ja jestem Bogiem.", ref: "Psalm 46:11" },
        { text: "Pan będzie walczył za was, a wy będziecie spokojni.", ref: "Księga Wyjścia 14:14" },
        { text: "Tylko w Bogu uspokaja się moja dusza, od Niego pochodzi moje zbawienie. Tylko On jest moją opoką i zbawieniem moim, twierdzą moją, więc się nie zachwieję.", ref: "Psalm 62:2-3" },
        { text: "Przyjdźcie do Mnie wszyscy, którzy utrudzeni i obciążeni jesteście, a Ja was pokrzepię.", ref: "Ewangelia Mateusza 11:28" },
        { text: "Pokój zostawiam wam, pokój mój daję wam. Nie tak jak daje świat, Ja wam daję. Niech się nie trwoży serce wasze ani się nie lęka.", ref: "Ewangelia Jana 14:27" },
        { text: "Stawiam sobie zawsze Pana przed oczy; gdy On jest po mojej prawicy, nie zachwieję się.", ref: "Psalm 16:8" },
        { text: "Nie spotkała was żadna pokusa, która by przekraczała ludzkie siły. Bóg jest wierny i nie pozwoli, byście byli kuszeni ponad to, co potraficie znieść. Wraz z pokusą da wam też drogę wyjścia, abyście mogli ją przetrwać.", ref: "1 Koryntian 10:13" },
        { text: "Bądźcie więc poddani Bogu, przeciwstawiajcie się natomiast diabłu, a ucieknie od was.", ref: "List Jakuba 4:7" },
        { text: "Oręż naszego bojowania nie jest z ciała, lecz ma moc od Boga do burzenia twierdz.", ref: "2 Koryntian 10:4" },
        { text: "Ku wolności wyswobodził nas Chrystus. A zatem trwajcie w niej i nie poddawajcie się na nowo pod jarzmo niewoli.", ref: "List do Galatów 5:1" },
        { text: "Jeśli więc Syn was wyzwoli, będziecie prawdziwie wolni.", ref: "Ewangelia Jana 8:36" },
        { text: "Tyś moją ucieczką i tarczą moją, pokładam nadzieję w Twoim słowie.", ref: "Psalm 119:114" },
        { text: "Choćby ciało moje i serce omdlewało, Bóg jest opoką serca mojego i moim działem na wieki.", ref: "Psalm 73:26" },
        { text: "Lecz On mi powiedział: Wystarczy ci mojej łaski, albowiem moc w słabości się doskonali.", ref: "2 Koryntian 12:9" },
        { text: "Lecz ci, którzy ufają Panu, nabierają nowej siły, wzbijają się na skrzydłach jak orły, biegną, a nie słabną, idą, a nie ustają.", ref: "Izajasza 40:31" },
        { text: "On dodaje sił zmęczonemu i pomnaża moc bezsilnego.", ref: "Izajasza 40:29" },
        { text: "Wszystko mogę w Tym, który mnie umacnia.", ref: "List do Filipian 4:13" },
        { text: "Wznoszę swe oczy ku górom: skądże nadejdzie mi pomoc? Pomoc moja od Pana, który stworzył niebo i ziemię.", ref: "Psalm 121:1-2" },
        { text: "O nic się już nie martwcie, ale w każdej sprawie wasze prośby przedstawiajcie Bogu w modlitwie i błaganiu z dziękczynieniem.", ref: "List do Filipian 4:6-7" },
        { text: "Nie lękaj się, bo Ja jestem z tobą; nie trwóż się, bom Ja twoim Bogiem. Umacniam cię, a także wspomagam.", ref: "Izajasza 41:10" },
        { text: "Gdy się mnożą troski w moim sercu, Twoje pociechy rozweselają moją duszę.", ref: "Psalm 94:19" },
        { text: "Wszystkie wasze troski przerzućcie na Niego, gdyż On się o was troszczy.", ref: "1 Piotra 5:7" },
        { text: "Chociażbym przechodził przez ciemną dolinę, zła się nie ulęknę, bo Ty jesteś ze mną. Twój kij i laska pasterska są moim pocieszeniem.", ref: "Psalm 23:4" },
        { text: "Albowiem nie dał nam Bóg ducha bojaźni, ale mocy i miłości, i trzeźwego myślenia.", ref: "2 Tymoteusza 1:7" },
        { text: "Bo choć sprawiedliwy siedem razy upadnie, to jednak znów się podniesie; lecz niegodziwcy potykają się w nieszczęściu.", ref: "Księga Przysłów 24:16" },
        { text: "Niewyczerpane są dary łaski Pana, Jego miłosierdzie nie ustaje. Każdego ranka jest nowe – wielka jest Twoja wierność.", ref: "Lamentacje 3:22-23" },
        { text: "Nie ciesz się z mego powodu, moja nieprzyjaciółko! Choć upadłem, powstanę; choć siedzę w ciemnościach, Pan jest moim światłem.", ref: "Księga Micheasza 7:8" },
        { text: "Pan jest blisko ludzi skruszonych w sercu, wybawia złamanych na duchu.", ref: "Psalm 34:19" },
        { text: "Tak więc, jeśli ktoś jest w Chrystusie, nowym jest stworzeniem. Stare przeminęło, oto wszystko stało się nowe.", ref: "2 Koryntian 5:17" },
        { text: "Dzieci, wy jesteście z Boga i zwyciężyliście ich, ponieważ Ten, który jest w was, jest większy niż ten, który jest w świecie.", ref: "1 Jana 4:4" },
        { text: "Gdy pójdziesz przez wody, Ja będę z tobą; i gdy przez rzeki, nie zatopią cię. Gdy pójdziesz przez ogień, nie spalisz się, a płomień nie strawi cię.", ref: "Izajasza 43:2" },
        { text: "Bóg jest naszą ucieczką i mocą, niezawodną pomocą w utrapieniach.", ref: "Psalm 46:2" },
        { text: "Z krańców ziemi wołam do Ciebie, gdy słabnie moje serce; wyprowadź mnie na skałę, która jest dla mnie za wysoka.", ref: "Psalm 61:3" },
        { text: "To wam powiedziałem, abyście pokój we Mnie mieli. Na świecie doznacie ucisku, ale miejcie odwagę: Jam zwyciężył świat.", ref: "Ewangelia Jana 16:33" }
    ],
    "sw": [
        { text: "Tulia, ujue ya kuwa mimi ni Mungu.", ref: "Zaburi 46:10" },
        { text: "Bwana atawapigania, nanyi mtanyamaza kimya.", ref: "Kutoka 14:14" },
        { text: "Nafsi yangu inamngoja Mungu peke yake kwa kimya; wokovu wangu hutoka kwake. Yeye peke yake ndiye mwamba wangu na wokovu wangu; ngome yangu, sitatikisika sana.", ref: "Zaburi 62:1-2" },
        { text: "Njooni kwangu, ninyi nyote msumbukao na wenye kulemewa na mizigo, nami nitawapumzisha.", ref: "Mathayo 11:28" },
        { text: "Amani nawaachieni; amani yangu nawapa. Siwapi ninyi kama ulimwengu utoavyo. Mioyo yenu isifadhaike, wala isiogope.", ref: "Yohana 14:27" },
        { text: "Nimemweka Bwana mbele yangu daima; kwa kuwa yuko upande wangu wa kuume, sitatikisika.", ref: "Zaburi 16:8" },
        { text: "Jaribu halikuwapata ninyi isipokuwa lililo kawaida ya wanadamu. Lakini Mungu ni mwaminifu; hatawaacha mjaribiwe kupita mwezavyo. Bali pamoja na jaribu, atafanya na mlango wa kutokea, ili mweze kustahimili.", ref: "1 Wakorintho 10:13" },
        { text: "Basi mtiini Mungu. Mpingeni Ibilisi, naye atawakimbia ninyi.", ref: "Yakobo 4:7" },
        { text: "Kwa maana silaha za vita vyetu si za mwili, bali zina uwezo katika Mungu hata kuangusha ngome.", ref: "2 Wakorintho 10:4" },
        { text: "Kristo alituweka huru ili tuwe huru kweli. Basi, simameni imara wala msinaswe tena katika nira ya utumwa.", ref: "Wagalatia 5:1" },
        { text: "Basi Mwana akiwaweka huru, mtakuwa huru kweli kweli.", ref: "Yohana 8:36" },
        { text: "Wewe ndiwe sitara yangu na ngao yangu; ninalitumainia neno lako.", ref: "Zaburi 119:114" },
        { text: "Mwili wangu na moyo wangu vinashindwa; bali Mungu ni mwamba wa moyo wangu, na fungu langu milele.", ref: "Zaburi 73:26" },
        { text: "Lakini aliniambia, 'Neema yangu inakutosha, kwa maana uweza wangu hukamilishwa katika udhaifu.'", ref: "2 Wakorintho 12:9" },
        { text: "Bali wao wamngojeao Bwana watapata nguvu mpya; watapaa juu kwa mbawa kama tai; watapiga mbio, wala hawatachoka; watatembea, wala hawatazimia.", ref: "Isaya 40:31" },
        { text: "Yeye huwapa nguvu wazimiao, na kumwongezea nguvu yule asiye na uwezo.", ref: "Isaya 40:29" },
        { text: "Nayaweza mambo yote katika yeye anitiaye nguvu.", ref: "Wafilipi 4:13" },
        { text: "Nitayainua macho yangu niitazame milima—msaada wangu utatoka wapi? Msaada wangu u katika Bwana, aliyezifanya mbingu na nchi.", ref: "Zaburi 121:1-2" },
        { text: "Msijisumbue kwa neno lo lote, bali katika kila neno kwa kusali na kuomba, pamoja na kushukuru, haja zenu na zijulikane na Mungu.", ref: "Wafilipi 4:6-7" },
        { text: "Usiogope, kwa maana mimi ni pamoja nawe; usifadhaike, kwa maana mimi ni Mungu wako. Nitakutia nguvu, naam, nitakusaidia; nitakushika kwa mkono wangu wa kuume wa haki.", ref: "Isaya 41:10" },
        { text: "Wakati mawazo yalipokuwa mengi ndani yangu, faraja zako ziliifurahisha nafsi yangu.", ref: "Zaburi 94:19" },
        { text: "Mtwikeni yeye fadhaa zenu zote, kwa maana yeye hujishughulisha sana kwa ajili yenu.", ref: "1 Petro 5:7" },
        { text: "Naam, nijapopita kati ya bonde la uvuli wa mauti, sitaogopa mabaya, kwa maana wewe upo pamoja nami; gongo lako na fimbo yako vyanifariji.", ref: "Zaburi 23:4" },
        { text: "Kwa maana Mungu hakutupa roho ya woga, bali ya nguvu, na ya upendo, na ya kiasi.", ref: "2 Timotheo 1:7" },
        { text: "Kwa maana mwenye haki huanguka mara saba, akasimama tena; bali wasio haki hukwazwa na maafa.", ref: "Mithali 24:16" },
        { text: "Kwa huruma za Bwana hatuangamii, kwa kuwa huruma zake hazikomi. Ni mpya kila asubuhi; uaminifu wako ni mkuu.", ref: "Maombolezo 3:22-23" },
        { text: "Usifurahi juu yangu, ee adui yangu! Niangukapo, nitasimama tena; niketipo gizani, Bwana atakuwa nuru kwangu.", ref: "Mika 7:8" },
        { text: "Bwana yu karibu na waliovunjika moyo, na kuwaokoa waliopondeka roho.", ref: "Zaburi 34:18" },
        { text: "Kwa hiyo, mtu akiwa ndani ya Kristo amekuwa kiumbe kipya; ya kale yamepita, tazama, yamekuwa mapya.", ref: "2 Wakorintho 5:17" },
        { text: "Ninyi, watoto wadogo, mwatokana na Mungu, nanyi mmewashinda; kwa sababu yeye aliye ndani yenu ni mkuu kuliko aliye katika ulimwengu.", ref: "1 Yohana 4:4" },
        { text: "Upitapo katika maji mengi mimi nitakuwa pamoja nawe; na katika mito, haitakugharikisha. Uendapo katika moto, hutateketea; wala mwali wa moto hautakuunguza.", ref: "Isaya 43:2" },
        { text: "Mungu kwetu sisi ni kimbilio na nguvu, msaada utakaoonekana tele wakati wa mateso.", ref: "Zaburi 46:1" },
        { text: "Toka mwisho wa nchi nitakulilia, moyo wangu uzimiapo; uniongoze mwambani ulio mrefu kuliko mimi.", ref: "Zaburi 61:2" },
        { text: "Hayo nimewaambieni mpate kuwa na amani ndani yangu. Ulimwenguni mnayo dhiki; lakini jipeni moyo, mimi nimeushinda ulimwengu.", ref: "Yohana 16:33" }
    ],
    "fa": [
        { text: "آرام بگیرید و بدانید که من خدا هستم.", ref: "مزمور 46:10" },
        { text: "خداوند برای شما خواهد جنگید، و شما فقط باید آرام باشید.", ref: "خروج 14:14" },
        { text: "جان من تنها در خدا آرام می‌گیرد؛ نجات من از جانب اوست. او تنها صخره و نجات من است؛ او قلعه من است، هرگز تزلزل نخواهم یافت.", ref: "مزمور 62:1-2" },
        { text: "نزد من بیایید ای تمامی زحمتکشان و گرانباران، و من به شما آرامش خواهم داد.", ref: "متی 11:28" },
        { text: "آرامش خود را برای شما می‌گذارم؛ آرامش خود را به شما می‌دهم. من آن را آنگونه که جهان می‌دهد به شما نمی‌دهم. دل‌های شما مضطرب و هراسان نباشد.", ref: "یوحنا 14:27" },
        { text: "چشمان خود را همیشه بر خداوند دوخته‌ام. با بودن او در سمت راستم، متزلزل نخواهم شد.", ref: "مزمور 16:8" },
        { text: "هیچ آزمایشی جز آنچه برای بشر معمول است بر شما نرسیده است. و خدا وفادار است؛ او نخواهد گذاشت بیش از توان خود وسوسه شوید. بلکه در هنگام وسوسه، راه گریزی نیز فراهم می‌کند تا بتوانید آن را تحمل کنید.", ref: "اول قرنتیان 10:13" },
        { text: "پس خود را تسلیم خدا کنید. در برابر ابلیس مقاومت کنید، و او از شما خواهد گریخت.", ref: "یعقوب 4:7" },
        { text: "زیرا سلاح‌های جنگ ما جسمانی نیستند، بلکه در خدا قدرت دارند تا قلعه‌ها را ویران کنند.", ref: "دوم قرنتیان 10:4" },
        { text: "مسیح ما را آزاد کرد تا آزاد باشیم. پس استوار بمانید و نگذارید دوباره یوغ بردگی بر گردن شما نهاده شود.", ref: "غلاطیان 5:1" },
        { text: "بنابراین اگر پسر شما را آزاد کند، براستی آزاد خواهید بود.", ref: "یوحنا 8:36" },
        { text: "تو پناهگاه و سپر من هستی؛ من به کلام تو امید بسته‌ام.", ref: "مزمور 119:114" },
        { text: "ممکن است جسم و دل من ضعف یابند، اما خدا صخره دل من و نصیب من تا ابدالآباد است.", ref: "مزمور 73:26" },
        { text: "اما او به من گفت: «فیض من برای تو کافی است، زیرا قدرت من در ضعف کامل می‌شود.»", ref: "دوم قرنتیان 12:9" },
        { text: "اما کسانی که به خداوند امید می‌بندند، نیروی تازه می‌یابند. آنها مانند عقاب‌ها بال خواهند گشود؛ خواهند دوید و خسته نخواهند شد، راه خواهند رفت و ناتوان نخواهند گردید.", ref: "اشعیا 40:31" },
        { text: "او به خستگان قدرت می‌بخشد و نیروی ضعیفان را افزون می‌کند.", ref: "اشعیا 40:29" },
        { text: "من می‌توانم همه کارها را از طریق او که به من قدرت می‌بخشد انجام دهم.", ref: "فیلیپیان 4:13" },
        { text: "چشمان خود را به کوه‌ها برمی‌افرازم—یاری من از کجا می‌آید؟ یاری من از جانب خداوند می‌آید، آفریننده آسمان و زمین.", ref: "مزمور 121:1-2" },
        { text: "برای هیچ چیز نگران نباشید، بلکه در هر شرایطی، با دعا و التماس، همراه با شکرگزاری، درخواست‌های خود را به خدا ارائه دهید. و آرامش خدا که فراتر از هر فهمی است، دل‌ها و ذهن‌های شما را حفظ خواهد کرد.", ref: "فیلیپیان 4:6-7" },
        { text: "پس نترسید، زیرا من با شما هستم؛ هراسان نباشید، زیرا من خدای شما هستم. من شما را تقویت خواهم کرد و به شما یاری خواهم رساند؛ من شما را با دست راست عادلانه خود نگه خواهم داشت.", ref: "اشعیا 41:10" },
        { text: "وقتی نگرانی در درونم بسیار بود، تسلی تو به من شادی بخشید.", ref: "مزمور 94:19" },
        { text: "تمام نگرانی‌های خود را به او بسپارید، زیرا او به شما اهمیت می‌دهد.", ref: "اول پطرس 5:7" },
        { text: "حتی اگر از تاریک‌ترین دره عبور کنم، از هیچ بدی نخواهم ترسید، زیرا تو با من هستی؛ عصا و چوبدستی تو، آنها مرا تسلی می‌دهند.", ref: "مزمور 23:4" },
        { text: "زیرا روحی که خدا به ما داده است، ما را ترسو نمی‌سازد، بلکه به ما قدرت، محبت و خویشتنداری می‌بخشد.", ref: "دوم تیموتائوس 1:7" },
        { text: "زیرا اگرچه مرد عادل هفت بار بیفتد، دوباره برمی‌خیزد، اما شریران هنگام بروز فاجعه می‌لغزند.", ref: "امثال 24:16" },
        { text: "به دلیل محبت‌های بی‌کران خداوند ما از بین نمی‌رویم، زیرا رحمت‌های او پایان‌ناپذیر است. آنها هر بامداد تازه می‌شوند؛ وفاداری تو عظیم است.", ref: "مراثی 3:22-23" },
        { text: "ای دشمن من، بر من شادی مکن! اگرچه افتاده‌ام، اما برخواهم خاست. اگرچه در تاریکی نشسته‌ام، اما خداوند نور من خواهد بود.", ref: "میکاه 7:8" },
        { text: "خداوند به دل‌شکستگان نزدیک است و کسانی را که روحی خرد شده دارند نجات می‌دهد.", ref: "مزمور 34:18" },
        { text: "بنابراین، اگر کسی در مسیح باشد، او یک خلقت تازه است: چیزهای کهنه درگذشته‌اند؛ اینک، همه چیز تازه شده است!", ref: "دوم قرنتیان 5:17" },
        { text: "شما ای فرزندان عزیز، از خدا هستید و بر آنها غلبه کرده‌اید، زیرا کسی که در شماست، بزرگتر از کسی است که در جهان است.", ref: "اول یوحنا 4:4" },
        { text: "وقتی از آب‌ها عبور می‌کنی، من با تو خواهم بود؛ و وقتی از رودخانه‌ها می‌گذری، تو را نخواهند برد. وقتی در آتش راه می‌روی، نخواهی سوخت؛ شعله‌ها تو را نخواهند سوزاند.", ref: "اشعیا 43:2" },
        { text: "خدا پناهگاه و قدرت ماست، یاری‌رسانی همیشگی در زمان سختی.", ref: "مزمور 46:1" },
        { text: "از کرانه‌های زمین تو را می‌خوانم، در حالی که قلبم ضعیف می‌شود تو را می‌خوانم؛ مرا به صخره‌ای هدایت کن که از من بلندتر است.", ref: "مزمور 61:2" },
        { text: "من این چیزها را به شما گفته‌ام تا در من آرامش داشته باشید. در این جهان دچار سختی خواهید شد. اما شجاع باشید! من بر جهان غلبه کرده‌ام.", ref: "یوحنا 16:33" }
    ],
    "ms": [
        { text: "Diamlah dan ketahuilah bahawa Akulah Allah.", ref: "Mazmur 46:10" },
        { text: "TUHAN akan berperang untuk kamu, dan kamu hanya perlu berdiam diri.", ref: "Keluaran 14:14" },
        { text: "Hanya dekat Allah saja aku tenang, dari pada-Nyalah keselamatanku. Hanya Dialah gunung batuku dan keselamatanku, kota bentengku, aku tidak akan goyah.", ref: "Mazmur 62:1-2" },
        { text: "Marilah kepada-Ku, semua yang letih lesu dan berbeban berat, Aku akan memberi kelegaan kepadamu.", ref: "Matius 11:28" },
        { text: "Damai sejahtera Kutinggalkan bagimu. Damai sejahtera-Ku Kuberikan kepadamu, dan apa yang Kuberikan tidak seperti yang diberikan oleh dunia kepadamu. Janganlah gelisah dan gentar hatimu.", ref: "Yohanes 14:27" },
        { text: "Aku senantiasa memandang kepada TUHAN; kerana Ia berdiri di sebelah kananku, aku tidak goyah.", ref: "Mazmur 16:8" },
        { text: "Pencubaan-pencubaan yang kamu alami ialah pencubaan-pencubaan biasa, yang tidak melebihi kekuatan manusia. Sebab Allah setia dan kerana itu Ia tidak akan membiarkan kamu dicubai melampaui kekuatanmu.", ref: "1 Korintus 10:13" },
        { text: "Kerana itu tunduklah kepada Allah, dan lawanlah Iblis, maka ia akan lari dari padamu!", ref: "Yakobus 4:7" },
        { text: "Kerana senjata peperangan kami bukanlah senjata duniawi, melainkan senjata yang penuh kuasa Allah untuk meruntuhkan kubu-kubu kuat.", ref: "2 Korintus 10:4" },
        { text: "Kristus telah membebaskan kita supaya kita benar-benar bebas. Oleh itu berdirilah teguh dan jangan biarkan diri anda dibebani lagi oleh kuk perhambaan.", ref: "Galatia 5:1" },
        { text: "Jadi jika Anak membebaskan kamu, kamu benar-benar bebas.", ref: "Yohanes 8:36" },
        { text: "Engkaulah tempat perlindunganku dan perisaiku; aku menaruh harapan pada firman-Mu.", ref: "Mazmur 119:114" },
        { text: "Sekalipun tubuhku dan hatiku menjadi lemah, Allah adalah gunung batu hatiku dan bahagianku selama-lamanya.", ref: "Mazmur 73:26" },
        { text: "Tetapi Dia berkata kepadaku, 'Kasih kurnia-Ku cukup bagimu, kerana kuasa-Ku menjadi sempurna dalam kelemahan.'", ref: "2 Korintus 12:9" },
        { text: "Tetapi orang yang menanti-nantikan TUHAN akan mendapat kekuatan baru. Mereka akan terbang tinggi seperti burung rajawali; mereka akan berlari dan tidak menjadi lelah, mereka akan berjalan dan tidak menjadi lesu.", ref: "Yesaya 40:31" },
        { text: "Dia memberikan kekuatan kepada yang lelah dan menambah kuasa kepada yang lemah.", ref: "Yesaya 40:29" },
        { text: "Segala perkara dapat kutanggung di dalam Dia yang memberi kekuatan kepadaku.", ref: "Filipi 4:13" },
        { text: "Aku melayangkan mataku ke gunung-gunung; dari manakah datangnya pertolonganku? Pertolonganku datang dari TUHAN, yang menjadikan langit dan bumi.", ref: "Mazmur 121:1-2" },
        { text: "Janganlah hendaknya kamu kuatir tentang apa pun juga, tetapi nyatakanlah dalam segala hal keinginanmu kepada Allah dalam doa dan permohonan dengan ucapan syukur. Damai sejahtera Allah, yang melampaui segala akal, akan memelihara hati dan fikiranmu.", ref: "Filipi 4:6-7" },
        { text: "Janganlah takut, sebab Aku menyertai engkau, janganlah bimbang, sebab Aku ini Allahmu; Aku akan meneguhkan, bahkan akan menolong engkau; Aku akan memegang engkau dengan tangan kanan-Ku yang membawa kemenangan.", ref: "Yesaya 41:10" },
        { text: "Apabila kecemasan bertambah banyak di dalam batinku, penghiburan-Mu menggembirakan jiwaku.", ref: "Mazmur 94:19" },
        { text: "Serahkanlah segala kekuatiranmu kepada-Nya, sebab Ia yang memelihara kamu.", ref: "1 Petrus 5:7" },
        { text: "Sekalipun aku berjalan dalam lembah kekelaman, aku tidak takut bahaya, sebab Engkau besertaku; gada-Mu dan tongkat-Mu, itulah yang menghibur aku.", ref: "Mazmur 23:4" },
        { text: "Sebab Allah memberikan kepada kita bukan roh ketakutan, melainkan roh yang membangkitkan kekuatan, kasih dan ketertiban.", ref: "2 Timotius 1:7" },
        { text: "Sebab orang benar jatuh tujuh kali, namun ia bangun kembali, tetapi orang fasik akan roboh dalam bencana.", ref: "Amsal 24:16" },
        { text: "Tak berkesudahan kasih setia TUHAN, tak habis-habisnya rahmat-Nya, selalu baru tiap pagi; besar kesetiaan-Mu!", ref: "Ratapan 3:22-23" },
        { text: "Janganlah bersukacita atas aku, hai musuhku! Sekalipun aku jatuh, aku akan bangun pula. Sekalipun aku duduk dalam gelap, TUHAN akan menjadi terangku.", ref: "Mikha 7:8" },
        { text: "TUHAN itu dekat kepada orang-orang yang patah hati, dan Ia menyelamatkan orang-orang yang remuk jiwanya.", ref: "Mazmur 34:18" },
        { text: "Jadi siapa yang ada di dalam Kristus, ia adalah ciptaan baru: yang lama sudah berlalu, sesungguhnya yang baru sudah datang.", ref: "2 Korintus 5:17" },
        { text: "Kamu berasal dari Allah, anak-anakku, dan kamu telah mengalahkan nabi-nabi palsu itu; sebab Roh yang ada di dalam kamu lebih besar daripada roh yang ada di dalam dunia.", ref: "1 Yohanes 4:4" },
        { text: "Apabila engkau menyeberangi air, Aku akan menyertai engkau, atau menyeberangi sungai-sungai, engkau tidak akan dihanyutkan. Apabila engkau berjalan melalui api, engkau tidak akan dihanguskan, dan nyala api tidak akan membakar engkau.", ref: "Yesaya 43:2" },
        { text: "Allah itu bagi kita tempat perlindungan dan kekuatan, sebagai penolong dalam kesesakan sangat terbukti.", ref: "Mazmur 46:1" },
        { text: "Dari hujung bumi aku berseru kepada-Mu, apabila hatiku lemah lesu; tuntunlah aku ke gunung batu yang terlalu tinggi bagiku.", ref: "Mazmur 61:2" },
        { text: "Semuanya ini Kukatakan kepadamu, supaya kamu beroleh damai sejahtera dalam Aku. Dalam dunia kamu menderita penganiayaan, tetapi kuatkanlah hatimu, Aku telah mengalahkan dunia.", ref: "Yohanes 16:33" }
    ],
    "ur": [
        { text: "خاموش رہو، اور جان لو کہ میں خدا ہوں۔", ref: "زبور 46:10" },
        { text: "خداوند تمہاری طرف سے لڑے گا؛ تمہیں بس خاموش رہنے کی ضرورت ہے۔", ref: "خروج 14:14" },
        { text: "میری جان کو صرف خدا ہی میں سکون ملتا ہے؛ میری نجات اسی کی طرف سے ہے۔ وہ اکیلا ہی میری چٹان اور میری نجات ہے؛ وہ میرا قلعہ ہے، میں کبھی نہیں ڈگمگاؤں گا۔", ref: "زبور 62:1-2" },
        { text: "اے محنت کشو اور بوجھ تلے دبے ہوئے لوگو، میرے پاس آؤ، اور میں تمہیں آرام دوں گا۔", ref: "متی 11:28" },
        { text: "میں تمہارے لیے اطمینان چھوڑے جاتا ہوں؛ میں تمہیں اپنا اطمینان دیتا ہوں۔ میں تمہیں اس طرح نہیں دیتا جیسے دنیا دیتی ہے۔ تمہارے دل نہ گھبرائیں اور نہ ڈریں۔", ref: "یوحنا 14:27" },
        { text: "میں نے خداوند کو ہمیشہ اپنے سامنے رکھا ہے۔ چونکہ وہ میرے داہنے ہاتھ پر ہے، میں نہیں ڈگمگاؤں گا۔", ref: "زبور 16:8" },
        { text: "تم پر کوئی ایسی آزمائش نہیں آئی جو انسان کی برداشت سے باہر ہو۔ خدا وفادار ہے؛ وہ تمہیں تمہاری طاقت سے زیادہ آزمائش میں پڑنے نہیں دے گا۔ بلکہ آزمائش کے وقت وہ نکلنے کا راستہ بھی فراہم کرے گا۔", ref: "1 کرنتھیوں 10:13" },
        { text: "پس اپنے آپ کو خدا کے تابع کرو۔ شیطان کا مقابلہ کرو، تو وہ تمہارے پاس سے بھاگ جائے گا۔", ref: "یعقوب 4:7" },
        { text: "کیونکہ ہماری جنگ کے ہتھیار دنیاوی نہیں، بلکہ ان میں خدا کی قدرت ہے جو مضبوط قلعوں کو ڈھا سکتی ہے۔", ref: "2 کرنتھیوں 10:4" },
        { text: "آزادی کے لیے مسیح نے ہمیں آزاد کیا ہے۔ پس مضبوطی سے کھڑے رہو اور خود کو دوبارہ غلامی کے جوئے میں نہ جُتنے دو۔", ref: "گلتیوں 5:1" },
        { text: "پس اگر بیٹا تمہیں آزاد کرے گا تو تم واقعی آزاد ہو گے۔", ref: "یوحنا 8:36" },
        { text: "تو میری پناہ اور میری ڈھال ہے؛ میں نے تیرے کلام پر امید رکھی ہے۔", ref: "زبور 119:114" },
        { text: "میرا جسم اور میرا دل زوال پذیر ہو سکتے ہیں، لیکن خدا میرے دل کی چٹان اور ہمیشہ کے لیے میرا حصہ ہے۔", ref: "زبور 73:26" },
        { text: "لیکن اس نے مجھ سے کہا، 'میرا فضل تیرے لیے کافی ہے، کیونکہ میری قدرت کمزوری میں کامل ہوتی ہے۔'", ref: "2 کرنتھیوں 12:9" },
        { text: "لیکن جو خداوند پر امید رکھتے ہیں وہ اپنی طاقت کو نیا کریں گے۔ وہ عقابوں کی طرح پرواز کریں گے؛ وہ دوڑیں گے اور تھکیں گے نہیں، وہ چلیں گے اور نڈھال نہیں ہوں گے۔", ref: "یسعیاہ 40:31" },
        { text: "وہ تھکے ماندے کو طاقت دیتا ہے اور کمزور کی قوت بڑھاتا ہے۔", ref: "یسعیاہ 40:29" },
        { text: "میں اس کے وسیلے سے جو مجھے طاقت بخشتا ہے، سب کچھ کر سکتا ہوں۔", ref: "فلپیوں 4:13" },
        { text: "میں اپنی آنکھیں پہاڑوں کی طرف اٹھاتا ہوں—میری مدد کہاں سے آتی ہے؟ میری مدد خداوند کی طرف سے آتی ہے، جس نے آسمان اور زمین کو بنایا۔", ref: "زبور 121:1-2" },
        { text: "کسی بات کی فکر نہ کرو، بلکہ ہر حال میں، دعا اور التجا کے ساتھ، شکرگزاری کرتے ہوئے، اپنی درخواستیں خدا کے سامنے پیش کرو۔ اور خدا کا اطمینان، جو سمجھ سے بالاتر ہے، تمہارے دلوں اور ذہنوں کی حفاظت کرے گا۔", ref: "فلپیوں 4:6-7" },
        { text: "پس مت ڈر، کیونکہ میں تیرے ساتھ ہوں؛ ہراساں نہ ہو، کیونکہ میں تیرا خدا ہوں۔ میں تجھے مضبوط کروں گا اور تیری مدد کروں گا؛ میں تجھے اپنے راستباز داہنے ہاتھ سے سنبھالوں گا۔", ref: "یسعیاہ 41:10" },
        { text: "جب میرے اندر بے چینی بہت بڑھ گئی، تو تیری تسلی نے میری جان کو خوشی دی۔", ref: "زبور 94:19" },
        { text: "اپنی تمام تر فکریں اسی پر ڈال دو کیونکہ اسے تمہاری فکر ہے۔", ref: "1 پطرس 5:7" },
        { text: "اگرچہ میں موت کے سائے کی وادی میں سے گزروں، تو بھی کسی برائی سے نہیں ڈروں گا، کیونکہ تو میرے ساتھ ہے؛ تیرا عصا اور تیری لاٹھی مجھے تسلی دیتے ہیں۔", ref: "زبور 23:4" },
        { text: "کیونکہ خدا نے ہمیں بزدلی کی روح نہیں دی، بلکہ قدرت، محبت اور خود پر قابو پانے کی روح دی ہے۔", ref: "2 تیمتھیس 1:7" },
        { text: "کیونکہ صادق شخص اگرچہ سات بار گرے، تو بھی وہ دوبارہ اٹھ کھڑا ہوتا ہے، لیکن شریر مصیبت آنے پر ٹھوکر کھاتے ہیں۔", ref: "امثال 24:16" },
        { text: "خداوند کی بے پناہ محبت کے باعث ہم فنا نہیں ہوئے، کیونکہ اس کی رحمتیں کبھی ختم نہیں ہوتیں۔ وہ ہر صبح نئی ہوتی ہیں؛ تیری وفاداری عظیم ہے۔", ref: "نوحہ 3:22-23" },
        { text: "اے میرے دشمن، مجھ پر خوشی نہ منا! اگر میں گر جاؤں، تو دوبارہ اٹھوں گا۔ اگرچہ میں اندھیرے میں بیٹھا ہوں، لیکن خداوند میری روشنی ہوگا۔", ref: "میکاہ 7:8" },
        { text: "خداوند ٹوٹے ہوئے دل والوں کے قریب ہے اور ان کو بچاتا ہے جن کی روح کچلی گئی ہو۔", ref: "زبور 34:18" },
        { text: "پس اگر کوئی مسیح میں ہے، تو وہ نیا مخلوق ہے: پرانی چیزیں گزر گئیں؛ دیکھو، سب کچھ نیا ہو گیا ہے!", ref: "2 کرنتھیوں 5:17" },
        { text: "اے پیارے بچو، تم خدا کی طرف سے ہو اور تم نے ان پر غالب آ گئے ہو، کیونکہ جو تمہارے اندر ہے، وہ اس سے بڑا ہے جو دنیا میں ہے۔", ref: "1 یوحنا 4:4" },
        { text: "جب تو پانیوں میں سے گزرے گا تو میں تیرے ساتھ ہوں گا؛ اور جب ندیوں میں سے گزرے گا، تو وہ تجھے نہیں بہائیں گی۔ جب تو آگ میں چلے گا تو جلے گا نہیں؛ اور شعلے تجھے نہیں جھلسائیں گے۔", ref: "یسعیاہ 43:2" },
        { text: "خدا ہماری پناہ اور طاقت ہے، مصیبت میں ہر وقت ملنے والی مدد۔", ref: "زبور 46:1" },
        { text: "زمین کی انتہا سے میں تجھے پکارتا ہوں، جب میرا دل گھبراتا ہے؛ مجھے اس چٹان پر لے چل جو مجھ سے بلند ہے۔", ref: "زبور 61:2" },
        { text: "میں نے یہ باتیں تم سے اس لیے کہی ہیں، کہ تم مجھ میں اطمینان پاؤ۔ دنیا میں تمہیں مصیبت کا سامنا کرنا پڑے گا۔ لیکن حوصلہ رکھو! میں نے دنیا پر فتح پا لی ہے۔", ref: "یوحنا 16:33" }
    ],
    "uk": [
        { text: "Вгамуйтесь та пізнайте, що Я — Бог.", ref: "Псалом 46:11" },
        { text: "Господь боротиметься за вас, а ви будьте спокійні.", ref: "Вихід 14:14" },
        { text: "Тільки в Бозі спочиває душа моя, від Нього спасіння моє. Тільки Він — твердиня моя і спасіння моє, мій захист, я не похитнуся.", ref: "Псалом 62:2-3" },
        { text: "Прийдіть до Мене, всі струджені та обтяжені, і Я заспокою вас.", ref: "Матвія 11:28" },
        { text: "Мир залишаю вам; Мій мир Я даю вам. Не так, як світ дає, Я даю вам. Хай не тривожиться серце ваше і не лякається.", ref: "Івана 14:27" },
        { text: "Уявляю я Господа перед собою постійно; бо Він праворуч мене, — і я не похитнуся.", ref: "Псалом 16:8" },
        { text: "Вас спіткала спокуса, яка не є більшою за людську. І вірний Бог, Який не попустить, щоб ви випробовувалися понад міру, але при спокусі дасть і вихід, щоб ви могли її перенести.", ref: "1 Коринтян 10:13" },
        { text: "Отже, підкоріться Богові. Противтеся дияволові, і він утече від вас.", ref: "Якова 4:7" },
        { text: "Зброя нашої боротьби не тілесна, але сильна Богом на зруйнування твердинь.", ref: "2 Коринтян 10:4" },
        { text: "Для свободи Христос визволив нас. Отже, стійте і не піддавайтеся знову під ярмо рабства.", ref: "Галатів 5:1" },
        { text: "Отже, якщо Син визволить вас, то справді будете вільними.", ref: "Івана 8:36" },
        { text: "Ти — мій захист і мій щит; я надіюсь на Твоє слово.", ref: "Псалом 119:114" },
        { text: "Знемагає тіло моє і серце моє, але Бог — твердиня серця мого і спадщина моя навіки.", ref: "Псалом 73:26" },
        { text: "Але Він сказав мені: «Досить тобі Моєї благодаті, бо сила Моя здійснюється в немочі».", ref: "2 Коринтян 12:9" },
        { text: "А ті, що надіються на Господа, відновлять сили. Вони піднімуть крила, як орли, побіжать — і не втомляться, підуть — і не знеможуться.", ref: "Ісаї 40:31" },
        { text: "Він дає втомленому силу і знеможеному примножує міць.", ref: "Ісаї 40:29" },
        { text: "Усе можу в Тому, Хто мене зміцнює.", ref: "Филип'ян 4:13" },
        { text: "Свої очі я зводжу на гори, звідки прийде мені допомога. Моя допомога від Господа, Який створив небо і землю.", ref: "Псалом 121:1-2" },
        { text: "Ні про що не турбуйтесь, але в усьому через молитву та благання з подякою відкривайте ваші прохання Богові. І мир Божий, який перевищує всякий розум, збереже ваші серця і ваші думки.", ref: "Филип'ян 4:6-7" },
        { text: "Не бійся, бо Я з тобою; не лякайся, бо Я — твій Бог. Я зміцню тебе і допоможу тобі; підтримаю тебе правицею правди Моєї.", ref: "Ісаї 41:10" },
        { text: "Коли в моєму серці множаться тривоги, Твої втіхи звеселяють мою душу.", ref: "Псалом 94:19" },
        { text: "Усі ваші турботи покладіть на Нього, бо Він дбає про вас.", ref: "1 Петра 5:7" },
        { text: "Навіть якщо я піду долиною смертної тіні, не злякаюся зла, бо Ти зі мною; Твій жезл і Твій посох — вони мене втішають.", ref: "Псалом 23:4" },
        { text: "Бо Бог дав нам духа не страху, але сили, любові та здорового глузду.", ref: "2 Тимофія 1:7" },
        { text: "Бо праведник сім разів упаде — і підніметься, а нечестиві спіткнуться в біді.", ref: "Притчі 24:16" },
        { text: "Милість Господня не вичерпується, милосердя Його не має кінця. Воно оновлюється кожного ранку; велика Твоя вірність!", ref: "Плач Єремії 3:22-23" },
        { text: "Не радій з мене, вороге мій! Хоч я впав, та встану. Хоч сиджу в темряві, Господь буде моїм світлом.", ref: "Михея 7:8" },
        { text: "Близький Господь до тих, у кого розбите серце, і спасає пригнічених духом.", ref: "Псалом 34:19" },
        { text: "Отже, хто в Христі, той нове створіння: старе минуло, тепер усе нове!", ref: "2 Коринтян 5:17" },
        { text: "Дітоньки, ви від Бога і перемогли їх, бо Той, Хто у вас, більший за того, хто у світі.", ref: "1 Івана 4:4" },
        { text: "Коли переходитимеш через води, Я буду з тобою; і через ріки — вони не затоплять тебе. Коли підеш через вогонь, не обпечешся, і полум'я не спалить тебе.", ref: "Ісаї 43:2" },
        { text: "Бог нам пристановище і сила, надійний помічник у скорботах.", ref: "Псалом 46:2" },
        { text: "Від кінців землі взиваю до Тебе, коли омліває моє серце; виведи мене на скелю, яка для мене зависока.", ref: "Псалом 61:3" },
        { text: "Це сказав Я вам, щоб у Мені ви мали мир. У світі матимете скорботу, але мужайтесь: Я переміг світ.", ref: "Івана 16:33" }
    ]
};