/**
 * TSH Global Scripture Engine
 * Contains 34 verses translated into 16 major languages.
 */

const scriptures = {
    "en": [
        { text: "Be still, and know that I am God.", ref: "Psalm 46:10" },
        { text: "The Lord will fight for you; you need only to be still.", ref: "Exodus 14:14" },
        { text: "Truly my soul finds rest in God; my salvation comes from him. Truly he is my rock and my salvation; he is my fortress, I will never be shaken.", ref: "Psalm 62:1-2" },
        { text: "Come to me, all you who are weary and burdened, and I will give you rest.", ref: "Matthew 11:28" },
        { text: "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.", ref: "John 14:27" },
        { text: "I keep my eyes always on the Lord. With him at my right hand, I will not be shaken.", ref: "Psalm 16:8" },
        { text: "No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear. But when you are tempted, he will also provide a way out so that you can endure it.", ref: "1 Corinthians 10:13" },
        { text: "Submit yourselves, then, to God. Resist the devil, and he will flee from you.", ref: "James 4:7" },
        { text: "The weapons we fight with are not the weapons of the world. On the contrary, they have divine power to demolish strongholds.", ref: "2 Corinthians 10:4" },
        { text: "It is for freedom that Christ has set us free. Stand firm, then, and do not let yourselves be burdened again by a yoke of slavery.", ref: "Galatians 5:1" },
        { text: "So if the Son sets you free, you will be free indeed.", ref: "John 8:36" },
        { text: "You are my refuge and my shield; I have put my hope in your word.", ref: "Psalm 119:114" },
        { text: "My flesh and my heart may fail, but God is the strength of my heart and my portion forever.", ref: "Psalm 73:26" },
        { text: "But he said to me, 'My grace is sufficient for you, for my power is made perfect in weakness.'", ref: "2 Corinthians 12:9" },
        { text: "But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.", ref: "Isaiah 40:31" },
        { text: "He gives strength to the weary and increases the power of the weak.", ref: "Isaiah 40:29" },
        { text: "I can do all this through him who gives me strength.", ref: "Philippians 4:13" },
        { text: "I lift up my eyes to the mountains—where does my help come from? My help comes from the Lord, the Maker of heaven and earth.", ref: "Psalm 121:1-2" },
        { text: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds.", ref: "Philippians 4:6-7" },
        { text: "So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.", ref: "Isaiah 41:10" },
        { text: "When anxiety was great within me, your consolation brought me joy.", ref: "Psalm 94:19" },
        { text: "Cast all your anxiety on him because he cares for you.", ref: "1 Peter 5:7" },
        { text: "Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me.", ref: "Psalm 23:4" },
        { text: "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.", ref: "2 Timothy 1:7" },
        { text: "For though the righteous fall seven times, they rise again, but the wicked stumble when calamity strikes.", ref: "Proverbs 24:16" },
        { text: "The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness.", ref: "Lamentations 3:22-23" },
        { text: "Do not gloat over me, my enemy! Though I have fallen, I will rise. Though I sit in darkness, the Lord will be my light.", ref: "Micah 7:8" },
        { text: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", ref: "Psalm 34:18" },
        { text: "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!", ref: "2 Corinthians 5:17" },
        { text: "You, dear children, are from God and have overcome them, because the one who is in you is greater than the one who is in the world.", ref: "1 John 4:4" },
        { text: "When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you. When you walk through the fire, you will not be burned; the flames will not set you ablaze.", ref: "Isaiah 43:2" },
        { text: "God is our refuge and strength, an ever-present help in trouble.", ref: "Psalm 46:1" },
        { text: "From the ends of the earth I call to you, I call as my heart grows faint; lead me to the rock that is higher than I.", ref: "Psalm 61:2" },
        { text: "I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world.", ref: "John 16:33" }
    ],
    "es": [
        { text: "Estad quietos, y conoced que yo soy Dios.", ref: "Salmos 46:10" },
        { text: "Jehová peleará por vosotros, y vosotros estaréis tranquilos.", ref: "Éxodo 14:14" },
        { text: "En Dios solamente está acallada mi alma; De él viene mi salvación. Él solamente es mi roca y mi salvación; Es mi refugio, no resbalaré mucho.", ref: "Salmos 62:1-2" },
        { text: "Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.", ref: "Mateo 11:28" },
        { text: "La paz os dejo, mi paz os doy; yo no os la doy como el mundo la da. No se turbe vuestro corazón, ni tenga miedo.", ref: "Juan 14:27" },
        { text: "A Jehová he puesto siempre delante de mí; Porque está a mi diestra, no seré conmovido.", ref: "Salmos 16:8" },
        { text: "No os ha sobrevenido ninguna tentación que no sea humana; pero fiel es Dios, que no os dejará ser tentados más de lo que podéis resistir, sino que dará también juntamente con la tentación la salida, para que podáis soportar.", ref: "1 Corintios 10:13" },
        { text: "Someteos, pues, a Dios; resistid al diablo, y huirá de vosotros.", ref: "Santiago 4:7" },
        { text: "Porque las armas de nuestra milicia no son carnales, sino poderosas en Dios para la destrucción de fortalezas.", ref: "2 Corintios 10:4" },
        { text: "Estad, pues, firmes en la libertad con que Cristo nos hizo libres, y no estéis otra vez sujetos al yugo de esclavitud.", ref: "Gálatas 5:1" },
        { text: "Así que, si el Hijo os libertare, seréis verdaderamente libres.", ref: "Juan 8:36" },
        { text: "Mi escondedero y mi escudo eres tú; En tu palabra he esperado.", ref: "Salmos 119:114" },
        { text: "Mi carne y mi corazón desfallecen; Mas la roca de mi corazón y mi porción es Dios para siempre.", ref: "Salmos 73:26" },
        { text: "Y me ha dicho: Bástate mi gracia; porque mi poder se perfecciona en la debilidad.", ref: "2 Corintios 12:9" },
        { text: "Pero los que esperan a Jehová tendrán nuevas fuerzas; levantarán alas como las águilas; correrán, y no se cansarán; caminarán, y no se fatigarán.", ref: "Isaías 40:31" },
        { text: "Él da esfuerzo al cansado, y multiplica las fuerzas al que no tiene ningunas.", ref: "Isaías 40:29" },
        { text: "Todo lo puedo en Cristo que me fortalece.", ref: "Filipenses 4:13" },
        { text: "Alzaré mis ojos a los montes; ¿De dónde vendrá mi socorro? Mi socorro viene de Jehová, Que hizo los cielos y la tierra.", ref: "Salmos 121:1-2" },
        { text: "Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios en toda oración y ruego, con acción de gracias. Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús.", ref: "Filipenses 4:6-7" },
        { text: "No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo; siempre te ayudaré, siempre te sustentaré con la diestra de mi justicia.", ref: "Isaías 41:10" },
        { text: "En la multitud de mis pensamientos dentro de mí, Tus consolaciones alegraban mi alma.", ref: "Salmos 94:19" },
        { text: "Echando toda vuestra ansiedad sobre él, porque él tiene cuidado de vosotros.", ref: "1 Pedro 5:7" },
        { text: "Aunque ande en valle de sombra de muerte, No temeré mal alguno, porque tú estarás conmigo; Tu vara y tu cayado me infundirán aliento.", ref: "Salmos 23:4" },
        { text: "Porque no nos ha dado Dios espíritu de cobardía, sino de poder, de amor y de dominio propio.", ref: "2 Timoteo 1:7" },
        { text: "Porque siete veces cae el justo, y vuelve a levantarse; Mas los impíos caerán en el mal.", ref: "Proverbios 24:16" },
        { text: "Por la misericordia de Jehová no hemos sido consumidos, porque nunca decayeron sus misericordias. Nuevas son cada mañana; grande es tu fidelidad.", ref: "Lamentaciones 3:22-23" },
        { text: "Tú, enemiga mía, no te alegres de mí, porque aunque caí, me levantaré; aunque more en tinieblas, Jehová será mi luz.", ref: "Miqueas 7:8" },
        { text: "Cercano está Jehová a los quebrantados de corazón; Y salva a los contritos de espíritu.", ref: "Salmos 34:18" },
        { text: "De modo que si alguno está en Cristo, nueva criatura es; las cosas viejas pasaron; he aquí todas son hechas nuevas.", ref: "2 Corintios 5:17" },
        { text: "Hijitos, vosotros sois de Dios, y los habéis vencido; porque mayor es el que está en vosotros, que el que está en el mundo.", ref: "1 Juan 4:4" },
        { text: "Cuando pases por las aguas, yo estaré contigo; y si por los ríos, no te anegarán. Cuando pases por el fuego, no te quemarás, ni la llama arderá en ti.", ref: "Isaías 43:2" },
        { text: "Dios es nuestro amparo y fortaleza, Nuestro pronto auxilio en las tribulaciones.", ref: "Salmos 46:1" },
        { text: "Desde el cabo de la tierra clamaré a ti, cuando mi corazón desmayare. Llévame a la roca que es más alta que yo.", ref: "Salmos 61:2" },
        { text: "Estas cosas os he hablado para que en mí tengáis paz. En el mundo tendréis aflicción; pero confiad, yo he vencido al mundo.", ref: "Juan 16:33" }
    ],
    "fr": [
        { text: "Arrêtez, et sachez que je suis Dieu.", ref: "Psaumes 46:10" },
        { text: "L'Éternel combattra pour vous; et vous, gardez le silence.", ref: "Exode 14:14" },
        { text: "Oui, c'est en Dieu que mon âme se confie; De lui vient mon salut. Oui, c'est lui qui est mon rocher et mon salut; Ma haute retraite: je ne chancellerai guère.", ref: "Psaumes 62:1-2" },
        { text: "Venez à moi, vous tous qui êtes fatigués et chargés, et je vous donnerai du repos.", ref: "Matthieu 11:28" },
        { text: "Je vous laisse la paix, je vous donne ma paix. Je ne vous donne pas comme le monde donne. Que votre coeur ne se trouble point, et ne s'alarme point.", ref: "Jean 14:27" },
        { text: "J'ai constamment l'Éternel sous mes yeux; Quand il est à ma droite, je ne chancelle pas.", ref: "Psaumes 16:8" },
        { text: "Aucune tentation ne vous est survenue qui n'ait été humaine, et Dieu, qui est fidèle, ne permettra pas que vous soyez tentés au delà de vos forces; mais avec la tentation il préparera aussi le moyen d'en sortir.", ref: "1 Corinthiens 10:13" },
        { text: "Soumettez-vous donc à Dieu; résistez au diable, et il fuira loin de vous.", ref: "Jacques 4:7" },
        { text: "Car les armes avec lesquelles nous combattons ne sont pas charnelles; mais elles sont puissantes, par la vertu de Dieu, pour renverser des forteresses.", ref: "2 Corinthiens 10:4" },
        { text: "C'est pour la liberté que Christ nous a affranchis. Demeurez donc fermes, et ne vous laissez pas mettre de nouveau sous le joug de la servitude.", ref: "Galates 5:1" },
        { text: "Si donc le Fils vous affranchit, vous serez réellement libres.", ref: "Jean 8:36" },
        { text: "Tu es mon asile et mon bouclier; J'espère en ta promesse.", ref: "Psaumes 119:114" },
        { text: "Ma chair et mon coeur peuvent se consumer: Dieu sera toujours le rocher de mon coeur et mon partage.", ref: "Psaumes 73:26" },
        { text: "Et il m'a dit: Ma grâce te suffit, car ma puissance s'accomplit dans la faiblesse.", ref: "2 Corinthiens 12:9" },
        { text: "Mais ceux qui se confient en l'Éternel renouvellent leur force. Ils prennent le vol comme les aigles; Ils courent, et ne se lassent point, Ils marchent, et ne se fatiguent point.", ref: "Ésaïe 40:31" },
        { text: "Il donne de la force à celui qui est fatigué, Et il augmente la vigueur de celui qui tombe en défaillance.", ref: "Ésaïe 40:29" },
        { text: "Je puis tout par celui qui me fortifie.", ref: "Philippiens 4:13" },
        { text: "Je lève mes yeux vers les montagnes... D'où me viendra le secours? Le secours me vient de l'Éternel, Qui a fait les cieux et la terre.", ref: "Psaumes 121:1-2" },
        { text: "Ne vous inquiétez de rien; mais en toute chose faites connaître vos besoins à Dieu par des prières et des supplications, avec des actions de grâces. Et la paix de Dieu, qui surpasse toute intelligence, gardera vos coeurs et vos pensées.", ref: "Philippiens 4:6-7" },
        { text: "Ne crains rien, car je suis avec toi; Ne promène pas des regards inquiets, car je suis ton Dieu; Je te fortifie, je viens à ton secours, Je te soutiens de ma droite triomphante.", ref: "Ésaïe 41:10" },
        { text: "Quand les pensées s'agitent en foule au dedans de moi, Tes consolations réjouissent mon âme.", ref: "Psaumes 94:19" },
        { text: "Et déchargez-vous sur lui de tous vos soucis, car lui-même prend soin de vous.", ref: "1 Pierre 5:7" },
        { text: "Quand je marche dans la vallée de l'ombre de la mort, Je ne crains aucun mal, car tu es avec moi: Ta houlette et ton bâton me rassurent.", ref: "Psaumes 23:4" },
        { text: "Car ce n'est pas un esprit de timidité que Dieu nous a donné, mais un esprit de force, d'amour et de sagesse.", ref: "2 Timothée 1:7" },
        { text: "Car sept fois le juste tombe, et il se relève, Mais les méchants sont précipités dans le malheur.", ref: "Proverbes 24:16" },
        { text: "Les bontés de l'Éternel ne sont pas épuisées, Ses compassions ne sont pas à leur terme; Elles se renouvellent chaque matin. Oh! que ta fidélité est grande!", ref: "Lamentations 3:22-23" },
        { text: "Ne te réjouis pas à mon sujet, mon ennemie! Car si je suis tombée, je me relèverai; Si je suis assise dans les ténèbres, L'Éternel sera ma lumière.", ref: "Michée 7:8" },
        { text: "L'Éternel est près de ceux qui ont le coeur brisé, Et il sauve ceux qui ont l'esprit dans l'abattement.", ref: "Psaumes 34:18" },
        { text: "Si quelqu'un est en Christ, il est une nouvelle créature. Les choses anciennes sont passées; voici, toutes choses sont devenues nouvelles.", ref: "2 Corinthiens 5:17" },
        { text: "Vous, petits enfants, vous êtes de Dieu, et vous les avez vaincus, parce que celui qui est en vous est plus grand que celui qui est dans le monde.", ref: "1 Jean 4:4" },
        { text: "Si tu traverses les eaux, je serai avec toi; Et les fleuves, ils ne te submergeront point; Si tu marches dans le feu, tu ne te brûleras pas, Et la flamme ne t'embrasera pas.", ref: "Ésaïe 43:2" },
        { text: "Dieu est pour nous un refuge et un appui, Un secours qui ne manque jamais dans la détresse.", ref: "Psaumes 46:1" },
        { text: "Du bout de la terre je crie à toi, dans l'abattement de mon coeur; Conduis-moi sur le rocher que je ne puis atteindre!", ref: "Psaumes 61:2" },
        { text: "Je vous ai dit ces choses, afin que vous ayez la paix en moi. Vous aurez des tribulations dans le monde; mais prenez courage, j'ai vaincu le monde.", ref: "Jean 16:33" }
    ],
    "de": [
        { text: "Seid stille und erkennet, dass ich Gott bin.", ref: "Psalm 46:10" },
        { text: "Der Herr wird für euch streiten, und ihr werdet stille sein.", ref: "2 Mose 14:14" },
        { text: "Meine Seele ist stille zu Gott, der mir hilft. Denn er ist mein Fels, meine Hilfe, mein Schutz, dass ich gewiss nicht fallen werde.", ref: "Psalm 62:2-3" },
        { text: "Kommt her zu mir, alle, die ihr mühselig und beladen seid; ich will euch erquicken.", ref: "Matthäus 11:28" },
        { text: "Den Frieden lasse ich euch, meinen Frieden gebe ich euch. Nicht gebe ich euch, wie die Welt gibt. Euer Herz erschrecke nicht und fürchte sich nicht.", ref: "Johannes 14:27" },
        { text: "Ich habe den Herrn allezeit vor Augen; weil er mir zur Rechten ist, wanke ich nicht.", ref: "Psalm 16:8" },
        { text: "Bisher hat euch nur menschliche Versuchung getroffen. Aber Gott ist treu, der euch nicht versuchen lässt über eure Kraft, sondern macht, dass die Versuchung so ein Ende nimmt, dass ihr's ertragen könnt.", ref: "1 Korinther 10:13" },
        { text: "So seid nun Gott untertan. Widersteht dem Teufel, so flieht er von euch.", ref: "Jakobus 4:7" },
        { text: "Denn die Waffen unsres Kampfes sind nicht fleischlich, sondern mächtig im Dienste Gottes, Festungen zu zerstören.", ref: "2 Korinther 10:4" },
        { text: "Zur Freiheit hat uns Christus befreit! So steht nun fest und lasst euch nicht wieder das Joch der Knechtschaft auflegen!", ref: "Galater 5:1" },
        { text: "Wenn euch nun der Sohn frei macht, so seid ihr wirklich frei.", ref: "Johannes 8:36" },
        { text: "Du bist mein Schirm und Schild; ich hoffe auf dein Wort.", ref: "Psalm 119:114" },
        { text: "Wenn mir gleich Leib und Seele verschmachtet, so bist du doch, Gott, allezeit meines Herzens Trost und mein Teil.", ref: "Psalm 73:26" },
        { text: "Und er hat zu mir gesagt: Lass dir an meiner Gnade genügen; denn meine Kraft ist in den Schwachen mächtig.", ref: "2 Korinther 12:9" },
        { text: "Aber die auf den Herrn harren, kriegen neue Kraft, dass sie auffahren mit Flügeln wie Adler, dass sie laufen und nicht matt werden, dass sie wandeln und nicht müde werden.", ref: "Jesaja 40:31" },
        { text: "Er gibt dem Müden Kraft, und Stärke genug dem Unvermögenden.", ref: "Jesaja 40:29" },
        { text: "Ich vermag alles durch den, der mich mächtig macht.", ref: "Philipper 4:13" },
        { text: "Ich hebe meine Augen auf zu den Bergen. Woher kommt mir Hilfe? Meine Hilfe kommt vom Herrn, der Himmel und Erde gemacht hat.", ref: "Psalm 121:1-2" },
        { text: "Sorgt euch um nichts, sondern in allen Dingen lasst eure Bitten in Gebet und Flehen mit Danksagung vor Gott kundwerden! Und der Friede Gottes, der höher ist als alle Vernunft, bewahre eure Herzen und Sinne in Christus Jesus.", ref: "Philipper 4:6-7" },
        { text: "Fürchte dich nicht, ich bin mit dir; weiche nicht, denn ich bin dein Gott. Ich stärke dich, ich helfe dir auch, ich halte dich durch die rechte Hand meiner Gerechtigkeit.", ref: "Jesaja 41:10" },
        { text: "Ich hatte viel Bekümmernis in meinem Herzen, aber deine Tröstungen erquickten meine Seele.", ref: "Psalm 94:19" },
        { text: "Alle eure Sorge werft auf ihn; denn er sorgt für euch.", ref: "1 Petrus 5:7" },
        { text: "Und ob ich schon wanderte im finstern Tal, fürchte ich kein Unglück; denn du bist bei mir, dein Stecken und Stab trösten mich.", ref: "Psalm 23:4" },
        { text: "Denn Gott hat uns nicht gegeben den Geist der Furcht, sondern der Kraft und der Liebe und der Besonnenheit.", ref: "2 Timotheus 1:7" },
        { text: "Denn ein Gerechter fällt siebenmal und steht wieder auf, aber die Gottlosen stürzen nieder im Unglück.", ref: "Sprüche 24:16" },
        { text: "Die Güte des Herrn ist's, dass wir nicht gar aus sind, seine Barmherzigkeit hat noch kein Ende, sondern sie ist alle Morgen neu, und deine Treue ist groß.", ref: "Klagelieder 3:22-23" },
        { text: "Freue dich nicht über mich, meine Feindin! Wenn ich auch darniederliege, so werde ich doch wieder aufstehen; und wenn ich auch im Finstern sitze, so ist doch der Herr mein Licht.", ref: "Micha 7:8" },
        { text: "Der Herr ist nahe denen, die zerbrochenen Herzens sind, und hilft denen, die ein zerschlagenes Gemüt haben.", ref: "Psalm 34:19" },
        { text: "Darum: Ist jemand in Christus, so ist er eine neue Kreatur; das Alte ist vergangen, siehe, Neues ist geworden.", ref: "2 Korinther 5:17" },
        { text: "Kinder, ihr seid von Gott und habt jene überwunden; denn der in euch ist, ist größer als der, der in der Welt ist.", ref: "1 Johannes 4:4" },
        { text: "Wenn du durch Wasser gehst, will ich bei dir sein, dass dich die Ströme nicht ersäufen sollen; und wenn du ins Feuer gehst, sollst du nicht brennen, und die Flamme soll dich nicht versengen.", ref: "Jesaja 43:2" },
        { text: "Gott ist unsre Zuversicht und Stärke, eine Hilfe in den großen Nöten, die uns getroffen haben.", ref: "Psalm 46:2" },
        { text: "Vom Ende der Erde rufe ich zu dir, da mein Herz in Ängsten ist: Führe mich auf den Felsen, der mir zu hoch ist!", ref: "Psalm 61:3" },
        { text: "Dies habe ich mit euch geredet, damit ihr in mir Frieden habt. In der Welt habt ihr Angst; aber seid getrost, ich habe die Welt überwunden.", ref: "Johannes 16:33" }
    ],
    "zh": [
        { text: "你们要休息，要知道我是神！", ref: "诗篇 46:10" },
        { text: "耶和华必为你们争战；你们只管静默，不要作声。", ref: "出埃及记 14:14" },
        { text: "我的心默默无声，专等候神；我的救恩是从他而来。惟独他是我的磐石，我的拯救；他是我的高台，我必不很动摇。", ref: "诗篇 62:1-2" },
        { text: "凡劳苦担重担的人可以到我这里来，我就使你们得安息。", ref: "马太福音 11:28" },
        { text: "我留下平安给你们；我将我的平安赐给你们。我所赐的，不像世人所赐的。你们心里不要忧愁，也不要胆怯。", ref: "约翰福音 14:27" },
        { text: "我将耶和华常摆在我面前，因他在我右边，我便不致摇动。", ref: "诗篇 16:8" },
        { text: "你们所遇见的试探，无非是人所能受的。神是信实的，必不叫你们受试探过于所能受的；在受试探的时候，总要给你们开一条出路，叫你们能忍受得住。", ref: "哥林多前书 10:13" },
        { text: "故此，你们要顺服神。务要抵挡魔鬼，魔鬼就必离开你们逃跑了。", ref: "雅各书 4:7" },
        { text: "我们争战的兵器本不是属血气的，乃是在神面前有能力，可以攻破坚固的营垒。", ref: "哥林多后书 10:4" },
        { text: "基督释放了我们，叫我们得以自由。所以要站立得稳，不要再被奴仆的轭挟制。", ref: "加拉太书 5:1" },
        { text: "所以天父的儿子若叫你们自由，你们就真自由了。", ref: "约翰福音 8:36" },
        { text: "你是我藏身之处，又是我的盾牌；我甚仰望你的话语。", ref: "诗篇 119:114" },
        { text: "我的肉体和我的心肠衰退；但神是我心里的力量，又是我的福分，直到永远。", ref: "诗篇 73:26" },
        { text: "他对我说：我的恩典够你用的，因为我的能力是在人的软弱上显得完全。", ref: "哥林多后书 12:9" },
        { text: "但那等候耶和华的必重新得力。他们必如鹰展翅上腾；他们奔跑却不困倦，行走却不疲乏。", ref: "以赛亚书 40:31" },
        { text: "疲乏的，他赐能力；软弱的，他加力量。", ref: "以赛亚书 40:29" },
        { text: "我靠着那加给我力量的，凡事都能做。", ref: "腓立比书 4:13" },
        { text: "我要向山举目；我的帮助从何而来？我的帮助从造天地的耶和华而来。", ref: "诗篇 121:1-2" },
        { text: "应当一无挂虑，只要凡事藉着祷告、祈求，和感谢，将你们所要的告诉神。神所赐、出人意外的平安必在基督耶稣里保守你们的心怀意念。", ref: "腓立比书 4:6-7" },
        { text: "你不要害怕，因为我与你同在；不要惊惶，因为我是你的神。我必坚固你，我必帮助你；我必用我公义的右手扶持你。", ref: "以赛亚书 41:10" },
        { text: "我心里多忧多疑，你安慰我，就使我欢乐。", ref: "诗篇 94:19" },
        { text: "你们要将一切的忧虑卸给神，因为他顾念你们。", ref: "彼得前书 5:7" },
        { text: "我虽然行过死荫的幽谷，也不怕遭害，因为你与我同在；你的杖，你的竿，都安慰我。", ref: "诗篇 23:4" },
        { text: "因为神赐给我们，不是胆怯的心，乃是刚强、仁爱、谨守的心。", ref: "提摩太后书 1:7" },
        { text: "因为义人虽七次跌倒，仍必兴起；恶人却被祸患倾倒。", ref: "箴言 24:16" },
        { text: "我们不致消灭，是出于耶和华诸般的慈爱；是因他的怜悯不致断绝。每早晨，这都是新的；你的诚实极其广大！", ref: "耶利米哀歌 3:22-23" },
        { text: "我的仇敌啊，不要向我夸耀。我跌倒，却要漫起；我坐在黑暗里，耶和华却作我的光。", ref: "弥迦书 7:8" },
        { text: "耶和华靠近伤心的人，拯救灵性痛悔的人。", ref: "诗篇 34:18" },
        { text: "若有人在基督里，他就是新造的人，旧事已过，都变成新的了。", ref: "哥林多后书 5:17" },
        { text: "小子们哪，你们是属神的，并且胜了他们；因为那在你们里面的，比那在世界上的更大。", ref: "约翰一书 4:4" },
        { text: "你从水中经过，我必与你同在；你趟过江河，水必不漫过你；你从火中行过，必不被烧，火焰也不着在你身上。", ref: "以赛亚书 43:2" },
        { text: "神是我们的避难所，是我们的力量，是我们在患难中随时的帮助。", ref: "诗篇 46:1" },
        { text: "我心里发昏的时候，我要从地极呼求你。求你领我到那比我更高的磐石！", ref: "诗篇 61:2" },
        { text: "我将这些事告诉你们，是要叫你们在我里面有平安。在世上，你们有苦难；但你们可以放心，我已经胜了世界。", ref: "约翰福音 16:33" }
    ],
    "hi": [
        { text: "चुपचाप रहो, और जान लो कि मैं ही परमेश्वर हूँ।", ref: "भजन संहिता 46:10" },
        { text: "यहोवा आप ही तुम्हारे लिये लड़ेगा; तुम चुपचाप रहो।", ref: "निर्गमन 14:14" },
        { text: "सचमुच मेरी आत्मा परमेश्वर की ओर शान्ति से ताकती है; मेरा उद्धार उसी से होता है। सचमुच वही मेरी चट्टान और मेरा उद्धार है, वह मेरा गढ़ है, मैं बहुत न डिगूंगा।", ref: "भजन संहिता 62:1-2" },
        { text: "हे सब परिश्रम करने वालों और बोझ से दबे हुए लोगों, मेरे पास आओ; मैं तुम्हें विश्राम दूंगा।", ref: "मत्ती 11:28" },
        { text: "मैं तुम्हें शान्ति दिए जाता हूँ, अपनी शान्ति मैं तुम्हें देता हूँ; जैसे संसार देता है, मैं तुम्हें नहीं देता: तुम्हारा मन व्याकुल न हो और न डरे।", ref: "यूहन्ना 14:27" },
        { text: "मैं ने यहोवा को निरन्तर अपने सम्मुख रखा है: इसलिये कि वह मेरे दाहिने हाथ रहता है, मैं न डिगूंगा।", ref: "भजन संहिता 16:8" },
        { text: "तुम किसी ऐसी परीक्षा में नहीं पड़े, जो मनुष्य के सहने से बाहर हो: और परमेश्वर सच्चा है: वह तुम्हें सामर्थ से बाहर परीक्षा में न पड़ने देगा, बरन परीक्षा के साथ निकास भी करेगा, कि तुम सह सको।", ref: "1 कुरिन्थियों 10:13" },
        { text: "इसलिये परमेश्वर के आधीन हो जाओ; और शैतान का साम्हना करो, तो वह तुम्हारे पास से भाग निकलेगा।", ref: "याकूब 4:7" },
        { text: "क्योंकि हमारी लड़ाई के हथियार शारीरिक नहीं, पर गढ़ों को ढा देने के लिये परमेश्वर के द्वारा सामर्थी हैं।", ref: "2 कुरिन्थियों 10:4" },
        { text: "मसीह ने स्वतंत्रता के लिये हमें स्वतंत्र किया है; सो इसी में स्थिर रहो, और दासत्व के जूए में फिर से न जुतो।", ref: "गलातियों 5:1" },
        { text: "इसलिये यदि पुत्र तुम्हें स्वतंत्र करेगा, तो सचमुच तुम स्वतंत्र हो जाओगे।", ref: "यूहन्ना 8:36" },
        { text: "तू मेरी आड़ और मेरी ढाल है; मेरी आशा तेरे वचन पर है।", ref: "भजन संहिता 119:114" },
        { text: "मेरा हृदय और मेरा शरीर दोनों क्षीण होते जाते हैं, परन्तु परमेश्वर सर्वदा के लिये मेरे हृदय की चट्टान और मेरा भाग है।", ref: "भजन संहिता 73:26" },
        { text: "उस ने मुझ से कहा, मेरा अनुग्रह तेरे लिये बहुत है; क्योंकि मेरी सामर्थ निर्बलता में सिद्ध होती है।", ref: "2 कुरिन्थियों 12:9" },
        { text: "परन्तु जो यहोवा की बाट जोहते हैं, वे नया बल प्राप्त करते जाएंगे, वे उकाबों की नाईं उड़ेंगे, वे दौड़ेंगे और श्रमित न होंगे, चलेंगे और थकित न होंगे।", ref: "यशायाह 40:31" },
        { text: "वह थके हुए को बल देता है और शक्तिहीन को बहुत सामर्थ देता है।", ref: "यशायाह 40:29" },
        { text: "जो मुझे सामर्थ देता है उस में मैं सब कुछ कर सकता हूँ।", ref: "फिलिप्पियों 4:13" },
        { text: "मैं अपनी आंखें पर्वतों की ओर लगाऊंगा; मुझे सहायता कहां से मिलेगी? मेरी सहायता यहोवा की ओर से होती है, जो आकाश और पृथ्वी का कर्त्ता है।", ref: "भजन संहिता 121:1-2" },
        { text: "किसी बात की चिन्ता मत करो; परन्तु हर एक बात में तुम्हारे निवेदन, प्रार्थना और बिनती के द्वारा धन्यवाद के साथ परमेश्वर के सम्मुख उपस्थित किए जाएं। तब परमेश्वर की शान्ति, जो समझ से बिलकुल परे है, तुम्हारे हृदय और तुम्हारे विचारों को मसीह यीशु में सुरक्षित रखेगी।", ref: "फिलिप्पियों 4:6-7" },
        { text: "मत डर, क्योंकि मैं तेरे संग हूँ, इधर उधर मत ताक, क्योंकि मैं तेरा परमेश्वर हूँ; मैं तुझे दृढ़ करूंगा और तेरी सहायता करूंगा, अपने धर्ममय दाहिने हाथ से मैं तुझे सम्हाले रहूंगा।", ref: "यशायाह 41:10" },
        { text: "जब मेरे मन में बहुत सी चिन्ताएं होती हैं, तब तेरी दी हुई शान्ति से मेरे प्राण को सुख मिलता है।", ref: "भजन संहिता 94:19" },
        { text: "अपनी सारी चिन्ता उसी पर डाल दो, क्योंकि उस को तुम्हारा ध्यान है।", ref: "1 पतरस 5:7" },
        { text: "चाहे मैं घोर अन्धकार से भरी हुई तराई में होकर चलूं, तौभी हानि से न डरूंगा, क्योंकि तू मेरे साथ रहता है; तेरे सोंटे और तेरी लाठी से मुझे शान्ति मिलती है।", ref: "भजन संहिता 23:4" },
        { text: "क्योंकि परमेश्वर ने हमें भय की नहीं पर सामर्थ, और प्रेम, और संयम की आत्मा दी है।", ref: "2 तीमुथियुस 1:7" },
        { text: "क्योंकि धर्मी सात बार गिरकर फिर उठ खड़ा होता है, परन्तु दुष्ट लोग विपत्ति में गिरकर पड़े ही रहते हैं।", ref: "नीतिवचन 24:16" },
        { text: "यहोवा की करुणा तो कभी समाप्त नहीं होती, और न उसकी दया का कभी अन्त होता है; वे प्रति भोर नई होती रहती हैं; तेरी सच्चाई महान है।", ref: "विलापगीत 3:22-23" },
        { text: "हे मेरी बैरिन, मुझ पर मत हंस! यद्यपि मैं गिर गया हूँ, तौभी उठूंगा; यद्यपि मैं अन्धकार में बैठा हूँ, तौभी यहोवा मेरे लिये ज्योति होगा।", ref: "मीका 7:8" },
        { text: "यहोवा टूटे मन वालों के समीप रहता है, और पिसे हुए लोगों का उद्धार करता है।", ref: "भजन संहिता 34:18" },
        { text: "सो यदि कोई मसीह में है तो वह नई सृष्टि है: पुरानी बातें बीत गई हैं; देखो, सब बातें नई हो गई हैं।", ref: "2 कुरिन्थियों 5:17" },
        { text: "हे बालको, तुम परमेश्वर के हो, और तुम ने उन पर जय पाई है; क्योंकि जो तुम में है वह उस से जो संसार में है, बड़ा है।", ref: "1 यूहन्ना 4:4" },
        { text: "जब तू जल में होकर जाए, मैं तेरे संग संग रहूंगा और जब तू नदियों में होकर चले, तब वे तुझे न डुबा सकेंगी; जब तू आग में चले तब तुझे आंच न लगेगी, और उसकी लौ तुझे न जला सकेगी।", ref: "यशायाह 43:2" },
        { text: "परमेश्वर हमारा शरणस्थान और बल है, संकट में अति सहज से मिलने वाला सहायक।", ref: "भजन संहिता 46:1" },
        { text: "जब मेरा हृदय व्याकुल होने लगे, तब मैं पृथ्वी की छोर से भी तुझे पुकारूंगा; जो चट्टान मेरे लिये बहुत ऊंची है, उस पर तू मुझे ले चल।", ref: "भजन संहिता 61:2" },
        { text: "मैं ने ये बातें तुम से इसलिये कही हैं, कि तुम्हें मुझ में शान्ति मिले। संसार में तुम्हें क्लेश होता है, परन्तु ढाढ़स बांधो, मैं ने संसार को जीत लिया है।", ref: "यूहन्ना 16:33" }
    ],
    "ar": [
        { text: "كفوا واعلموا أني أنا الله.", ref: "المزامير 46:10" },
        { text: "الرب يقاتل عنكم وأنتم تصمتون.", ref: "الخروج 14:14" },
        { text: "إنما لله انتظرت نفسي، من قبله خلاصي. إنما هو صخرتي وخلاصي، ملجإي، لا أتزعزع كثيراً.", ref: "المزامير 62:1-2" },
        { text: "تعالوا إلي يا جميع المتعبين والثقيلي الأحمال، وأنا أريحكم.", ref: "متى 11:28" },
        { text: "سلاماً أترك لكم، سلامي أعطيكم. ليس كما يعطي العالم أعطيكم أنا. لا تضطرب قلوبكم ولا ترهب.", ref: "يوحنا 14:27" },
        { text: "جعلت الرب أمامي في كل حين، لأنه عن يميني فلا أتزعزع.", ref: "المزامير 16:8" },
        { text: "لم تصبكم تجربة إلا بشرية. ولكن الله أمين، الذي لا يدعكم تجربون فوق ما تستطيعون، بل سيجعل مع التجربة المنفذ، لتستطيعوا أن تحتملوا.", ref: "1 كورنثوس 10:13" },
        { text: "فاخضعوا لله. قاوموا إبليس فيهرب منكم.", ref: "يعقوب 4:7" },
        { text: "إذ أسلحة محاربتنا ليست جسدية، بل قادرة بالله على هدم حصون.", ref: "2 كورنثوس 10:4" },
        { text: "فاثبتوا إذاً في الحرية التي قد حررنا المسيح بها، ولا ترتبكوا أيضاً بنير عبودية.", ref: "غلاطية 5:1" },
        { text: "فإن حرركم الابن فبالحقيقة تكونون أحراراً.", ref: "يوحنا 8:36" },
        { text: "ستري ومجني أنت. كلامك انتظرت.", ref: "المزامير 119:114" },
        { text: "قد فني لحمي وقلبي. صخرة قلبي ونصيبي الله إلى الدهر.", ref: "المزامير 73:26" },
        { text: "فقال لي: تكفيك نعمتي، لأن قوتي في الضعف تكمل.", ref: "2 كورنثوس 12:9" },
        { text: "وأما منتظرو الرب فيجددون قوة. يرفعون أجنحة كالنسور. يركضون ولا يتعبون. يمشون ولا يعيون.", ref: "إشعياء 40:31" },
        { text: "يعطي المعيي قدرة، ولعديم القوة يكثر شدة.", ref: "إشعياء 40:29" },
        { text: "أستطيع كل شيء في المسيح الذي يقويني.", ref: "فيلبي 4:13" },
        { text: "أرفع عيني إلى الجبال، من حيث يأتي عوني. معونتي من عند الرب صانع السماوات والأرض.", ref: "المزامير 121:1-2" },
        { text: "لا تهتموا بشيء، بل في كل شيء بالصلاة والدعاء مع الشكر، لتعلم طلباتكم لدى الله. وسلام الله الذي يفوق كل عقل، يحفظ قلوبكم وأفكاركم في المسيح يسوع.", ref: "فيلبي 4:6-7" },
        { text: "لا تخف لأني معك. لا تتلفت لأني إلهك. قد أيدتك وأعنتك وعضدتك بيمين بري.", ref: "إشعياء 41:10" },
        { text: "عند كثرة همومي في داخلي، تعزياتك تلذذ نفسي.", ref: "المزامير 94:19" },
        { text: "ملقين كل همكم عليه، لأنه هو يعتني بكم.", ref: "1 بطرس 5:7" },
        { text: "أيضاً إذا سرت في وادي ظل الموت لا أخاف شراً، لأنك أنت معي. عصاك وعكازك هما يعزيانني.", ref: "المزامير 23:4" },
        { text: "لأن الله لم يعطنا روح الفشل، بل روح القوة والمحبة والنصح.", ref: "2 تيموثاوس 1:7" },
        { text: "لأن الصديق يسقط سبع مرات ويقوم، أما الأشرار فيعثرون بالشر.", ref: "الأمثال 24:16" },
        { text: "إنه من إحسانات الرب أننا لم نفن، لأن مراحمه لا تزول. هي جديدة في كل صباح. كثيرة أمانتك.", ref: "مراثي إرميا 3:22-23" },
        { text: "لا تشمتي بي يا عدوتي. إذا سقطت أقوم. إذا جلست في الظلمة فالرب نور لي.", ref: "ميخا 7:8" },
        { text: "قريب هو الرب من المنكسري القلوب، ويخلص المنسحقي الروح.", ref: "المزامير 34:18" },
        { text: "إذًا إن كان أحد في المسيح فهو خليقة جديدة. الأشياء العتيقة قد مضت. هوذا الكل قد صار جديداً.", ref: "2 كورنثوس 5:17" },
        { text: "أنتم من الله أيها الأولاد وقد غلبتموهم، لأن الذي فيكم أعظم من الذي في العالم.", ref: "1 يوحنا 4:4" },
        { text: "إذا اجتزت في المياه فأنا معك، وفي الأنهار فلا تغمرك. إذا مشيت في النار فلا تلذع، واللهيب لا يحرقك.", ref: "إشعياء 43:2" },
        { text: "الله لنا ملجأ وقوة. عوناً في الضيقات وجد شديداً.", ref: "المزامير 46:1" },
        { text: "من أقصى الأرض أصرخ إليك إذا غشي على قلبي. إلى صخرة أرفع مني تهديني.", ref: "المزامير 61:2" },
        { text: "قد كلمتكم بهذا ليكون لكم فيّ سلام. في العالم سيكون لكم ضيق، ولكن ثقوا: أنا قد غلبت العالم.", ref: "يوحنا 16:33" }
    ],
    "pt": [
        { text: "Aquietai-vos, e sabei que eu sou Deus.", ref: "Salmos 46:10" },
        { text: "O Senhor pelejará por vós, e vós vos calareis.", ref: "Êxodo 14:14" },
        { text: "Somente em Deus, ó minha alma, espera silenciosa; dele vem a minha salvação. Só ele é a minha rocha e a minha salvação; é a minha defesa; não serei grandemente abalado.", ref: "Salmos 62:1-2" },
        { text: "Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei.", ref: "Mateus 11:28" },
        { text: "Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize.", ref: "João 14:27" },
        { text: "Tenho posto o Senhor continuamente diante de mim; por isso que ele está à minha mão direita, nunca vacilarei.", ref: "Salmos 16:8" },
        { text: "Não vos sobreveio tentação, senão humana; mas fiel é Deus, que não vos deixará tentar acima do que podeis, antes com a tentação dará também o escape, para que a possais suportar.", ref: "1 Coríntios 10:13" },
        { text: "Sujeitai-vos, pois, a Deus, resisti ao diabo, e ele fugirá de vós.", ref: "Tiago 4:7" },
        { text: "Porque as armas da nossa milícia não são carnais, mas sim poderosas em Deus para destruição das fortalezas.", ref: "2 Coríntios 10:4" },
        { text: "Estai, pois, firmes na liberdade com que Cristo nos libertou, e não torneis a meter-vos debaixo do jugo da servidão.", ref: "Gálatas 5:1" },
        { text: "Se, pois, o Filho vos libertar, verdadeiramente sereis livres.", ref: "João 8:36" },
        { text: "Tu és o meu refúgio e o meu escudo; espero na tua palavra.", ref: "Salmos 119:114" },
        { text: "A minha carne e o meu coração desfalecem; mas Deus é a fortaleza do meu coração, e a minha porção para sempre.", ref: "Salmos 73:26" },
        { text: "E disse-me: A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza.", ref: "2 Coríntios 12:9" },
        { text: "Mas os que esperam no Senhor renovarão as forças, subirão com asas como águias; correrão, e não se cansarão; caminharão, e não se fatigarão.", ref: "Isaías 40:31" },
        { text: "Dá força ao cansado, e multiplica as forças ao que não tem nenhum vigor.", ref: "Isaías 40:29" },
        { text: "Posso todas as coisas em Cristo que me fortalece.", ref: "Filipenses 4:13" },
        { text: "Elevo os olhos para os montes: de onde me virá o socorro? O meu socorro vem do Senhor, que fez os céus e a terra.", ref: "Salmos 121:1-2" },
        { text: "Não andeis ansiosos por coisa alguma; antes em tudo sejam os vossos pedidos conhecidos diante de Deus pela oração e súplica com ação de graças. E a paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos pensamentos em Cristo Jesus.", ref: "Filipenses 4:6-7" },
        { text: "Não temas, porque eu sou contigo; não te assombres, porque eu sou teu Deus; eu te fortaleço, e te ajudo, e te sustento com a destra da minha justiça.", ref: "Isaías 41:10" },
        { text: "Multiplicando-se dentro de mim os meus cuidados, as tuas consolações recrearam a minha alma.", ref: "Salmos 94:19" },
        { text: "Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.", ref: "1 Pedro 5:7" },
        { text: "Ainda que eu andasse pelo vale da sombra da morte, não temeria mal algum, porque tu estás comigo; a tua vara e o teu cajado me consolam.", ref: "Salmos 23:4" },
        { text: "Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação.", ref: "2 Timóteo 1:7" },
        { text: "Porque sete vezes cairá o justo, e se levantará; mas os ímpios tropeçarão no mal.", ref: "Provérbios 24:16" },
        { text: "As misericórdias do Senhor são a causa de não sermos consumidos, porque as suas misericórdias não têm fim; renovam-se cada manhã. Grande é a tua fidelidade.", ref: "Lamentações 3:22-23" },
        { text: "Ó inimiga minha, não te alegres a meu respeito; ainda que eu tenha caído, levantar-me-ei; se morar nas trevas, o Senhor será a minha luz.", ref: "Miquéias 7:8" },
        { text: "Perto está o Senhor dos que têm o coração quebrantado, e salva os contritos de espírito.", ref: "Salmos 34:18" },
        { text: "Assim que, se alguém está em Cristo, nova criatura é; as coisas velhas já passaram; eis que tudo se fez novo.", ref: "2 Coríntios 5:17" },
        { text: "Filhinhos, sois de Deus, e já os tendes vencido; porque maior é o que está em vós do que o que está no mundo.", ref: "1 João 4:4" },
        { text: "Quando passares pelas águas estarei contigo, e quando pelos rios, eles não te submergirão; quando passares pelo fogo, não te queimarás, nem a chama arderá em ti.", ref: "Isaías 43:2" },
        { text: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.", ref: "Salmos 46:1" },
        { text: "Desde o fim da terra clamarei a ti, quando o meu coração estiver desmaiado; leva-me para a rocha que é mais alta do que eu.", ref: "Salmos 61:2" },
        { text: "Tenho-vos dito isto, para que em mim tenhais paz; no mundo tereis aflições, mas tende bom ânimo, eu venci o mundo.", ref: "João 16:33" }
    ],
    "ru": [
        { text: "Остановитесь и познайте, что Я - Бог.", ref: "Псалтирь 45:11" },
        { text: "Господь будет поборать за вас, а вы будьте спокойны.", ref: "Исход 14:14" },
        { text: "Только в Боге успокаивается душа моя: от Него спасение мое. Только Он - твердыня моя, спасение мое, убежище мое: не поколеблюсь более.", ref: "Псалтирь 61:2-3" },
        { text: "Придите ко Мне все труждающиеся и обремененные, и Я успокою вас.", ref: "От Матфея 11:28" },
        { text: "Мир оставляю вам, мир Мой даю вам; не так, как мир дает, Я даю вам. Да не смущается сердце ваше и да не устрашается.", ref: "От Иоанна 14:27" },
        { text: "Всегда видел я пред собою Господа, ибо Он одесную меня; не поколеблюсь.", ref: "Псалтирь 15:8" },
        { text: "Вас постигло искушение не иное, как человеческое; и верен Бог, Который не попустит вам быть искушаемыми сверх сил, но при искушении даст и облегчение, так чтобы вы могли перенести.", ref: "1 Коринфянам 10:13" },
        { text: "Итак покоритесь Богу; противостаньте диаволу, и убежит от вас.", ref: "Иакова 4:7" },
        { text: "Оружия воинствования нашего не плотские, но сильные Богом на разрушение твердынь.", ref: "2 Коринфянам 10:4" },
        { text: "Итак стойте в свободе, которую даровал нам Христос, и не подвергайтесь опять игу рабства.", ref: "Галатам 5:1" },
        { text: "Итак, если Сын освободит вас, то истинно свободны будете.", ref: "От Иоанна 8:36" },
        { text: "Ты покров мой и щит мой; на слово Твое уповаю.", ref: "Псалтирь 118:114" },
        { text: "Изнемогает плоть моя и сердце мое: Бог твердыня сердца моего и часть моя вовек.", ref: "Псалтирь 72:26" },
        { text: "Но Господь сказал мне: 'довольно для тебя благодати Моей, ибо сила Моя совершается в немощи'.", ref: "2 Коринфянам 12:9" },
        { text: "А надеющиеся на Господа обновят силы: поднимут крылья, как орлы, потекут - и не устанут, пойдут - и не утомятся.", ref: "Исаия 40:31" },
        { text: "Он дает утомленному силу, и изнемогшему дарует крепость.", ref: "Исаия 40:29" },
        { text: "Все могу в укрепляющем меня Иисусе Христе.", ref: "Филиппийцам 4:13" },
        { text: "Воздвигаю очи мои к горам, откуда придет помощь моя. Помощь моя от Господа, сотворившего небо и землю.", ref: "Псалтирь 120:1-2" },
        { text: "Не заботьтесь ни о чем, но всегда в молитве и прошении с благодарением открывайте свои желания пред Богом, и мир Божий, который превыше всякого ума, соблюдет сердца ваши и помышления ваши во Христе Иисусе.", ref: "Филиппийцам 4:6-7" },
        { text: "Не бойся, ибо Я с тобою; не смущайся, ибо Я Бог твой; Я укреплю тебя, и помогу тебе, и поддержу тебя десницею правды Моей.", ref: "Исаия 41:10" },
        { text: "При умножении скорбей моих в сердце моем, утешения Твои услаждают душу мою.", ref: "Псалтирь 93:19" },
        { text: "Все заботы ваши возложите на Него, ибо Он печется о вас.", ref: "1 Петра 5:7" },
        { text: "Если я пойду и долиною смертной тени, не убоюсь зла, потому что Ты со мной; Твой жезл и Твой посох - они успокаивают меня.", ref: "Псалтирь 22:4" },
        { text: "Ибо дал нам Бог духа не боязни, но силы и любви и целомудрия.", ref: "2 Тимофею 1:7" },
        { text: "Ибо семь раз упадет праведник, и встанет; а нечестивые впадут в погибель.", ref: "Притчи 24:16" },
        { text: "По милости Господа мы не исчезли, ибо милосердие Его не истощилось. Оно обновляется каждое утро; велика верность Твоя!", ref: "Плач Иеремии 3:22-23" },
        { text: "Не радуйся о мне, неприятельница моя! хотя я упал, но встану; хотя я во мраке, но Господь свет для меня.", ref: "Михей 7:8" },
        { text: "Близок Господь к сокрушенным сердцем и смиренных духом спасет.", ref: "Псалтирь 33:19" },
        { text: "Итак, кто во Христе, тот новая тварь; древнее прошло, теперь все новое.", ref: "2 Коринфянам 5:17" },
        { text: "Дети! вы от Бога, и победили их; ибо Тот, Кто в вас, больше того, кто в мире.", ref: "1 Иоанна 4:4" },
        { text: "Будешь ли переходить через воды, Я с тобою, - через реки ли, они не потопят тебя; пойдешь ли через огонь, не обожжешься, и пламя не опалит тебя.", ref: "Исаия 43:2" },
        { text: "Бог нам прибежище и сила, скорый помощник в бедах.", ref: "Псалтирь 45:2" },
        { text: "От конца земли взываю к Тебе в унынии сердца моего; возведи меня на скалу, для меня недосягаемую.", ref: "Псалтирь 60:3" },
        { text: "Сие сказал Я вам, чтобы вы имели во Мне мир. В мире будете иметь скорбь; но мужайтесь: Я победил мир.", ref: "От Иоанна 16:33" }
    ],
    "ja": [
        { text: "静まって、わたしが神であることを知れ。", ref: "詩篇 46:10" },
        { text: "主があなたがたのために戦われる。あなたがたは黙っていなければならない。", ref: "出エジプト記 14:14" },
        { text: "私の魂は黙って神を待ち望む。私の救いは神から来る。神は私の岩、私の救い、私の砦。私は決して揺るがされない。", ref: "詩篇 62:1-2" },
        { text: "すべて疲れた人、重荷を負っている人は私のところに来なさい。私があなたがたを休ませてあげます。", ref: "マタイの福音書 11:28" },
        { text: "私はあなたがたに平安を残します。私の平安をあなたがたに与えます。世が与えるように、私はあなたがたに与えるのではありません。心を騒がせてはなりません。恐れてはなりません。", ref: "ヨハネの福音書 14:27" },
        { text: "私はいつも主を私の前に置いています。主が私の右におられるので、私は揺るがされません。", ref: "詩篇 16:8" },
        { text: "あなたがたが経験した試練はみな、人の知らないものではありません。神は真実な方です。あなたがたを耐えられない試練に遭わせることはなさいません。試練と共に、それに耐えられるよう、逃れる道も備えてくださいます。", ref: "コリント人への手紙 第一 10:13" },
        { text: "ですから、神に従いなさい。そして、悪魔に立ち向かいなさい。そうすれば、悪魔はあなたがたから逃げ去ります。", ref: "ヤコブの手紙 4:7" },
        { text: "私たちの戦いの武器は、肉のものではなく、神の御前で要塞を打ち破るほどに力のあるものです。", ref: "コリント人への手紙 第二 10:4" },
        { text: "キリストは、自由を得させるために、私たちを解放してくださいました。ですから、堅く立って、再び奴隷のくびきを負わされないようにしなさい。", ref: "ガラテヤ人への手紙 5:1" },
        { text: "ですから、子があなたがたを自由にするなら、あなたがたは本当に自由になるのです。", ref: "ヨハネの福音書 8:36" },
        { text: "あなたは私の隠れ場、私の盾。私はあなたのみことばを待ち望みます。", ref: "詩篇 119:114" },
        { text: "私の肉と私の心は衰え果てます。しかし、神はとこしえに私の心の岩、私の分です。", ref: "詩篇 73:26" },
        { text: "しかし、主は私に言われました。「私の恵みはあなたに十分である。力は弱さの中でこそ十分に発揮されるのだ。」", ref: "コリント人への手紙 第二 12:9" },
        { text: "しかし、主を待ち望む者は新しく力を得、鷲のように翼を広げて上ることができる。走っても弱らず、歩いても疲れない。", ref: "イザヤ書 40:31" },
        { text: "疲れた者には力を与え、精力のない者には活気をつける。", ref: "イザヤ書 40:29" },
        { text: "私は、私を強くしてくださる方によって、どんなことでもできるのです。", ref: "ピリピ人への手紙 4:13" },
        { text: "私は山に向かって目を上げる。私の助けは、どこから来るのだろうか。私の助けは、天地を造られた主から来る。", ref: "詩篇 121:1-2" },
        { text: "何も思い煩わないで、あらゆるばあいに、感謝をもってささげる祈りと願いによって、あなたがたの願い事を神に知っていただきなさい。そうすれば、人のすべての理解を超えた神の平安が、あなたがたの心と思いをキリスト・イエスにあって守ってくれます。", ref: "ピリピ人への手紙 4:6-7" },
        { text: "恐れるな。私があなたとともにいるからだ。たじろぐな。私があなたの神だからだ。私はあなたを強くし、あなたを助け、私の義の右の手で、あなたを守る。", ref: "イザヤ書 41:10" },
        { text: "私のうちで、思い煩いが増すときに、あなたの慰めが、私のたましいを喜ばせます。", ref: "詩篇 94:19" },
        { text: "あなたがたの思い煩いを、いっさい神にゆだねなさい。神があなたがたのことを心配してくださるからです。", ref: "ペテロの手紙 第一 5:7" },
        { text: "たとい、死の陰の谷を歩くことがあっても、私はわざわいを恐れません。あなたが私とともにおられますから。あなたのむちとあなたの杖、それが私の慰めです。", ref: "詩篇 23:4" },
        { text: "神が私たちに与えてくださったものは、おくびょうの霊ではなく、力と愛と慎みとの霊です。", ref: "テモテへの手紙 第二 1:7" },
        { text: "正しい者は七度倒れても、また起き上がるからだ。悪者はわざわいによって滅びる。", ref: "箴言 24:16" },
        { text: "私たちが滅びうせなかったのは、主の恵みによる。主のあわれみは尽きないからだ。それは朝ごとに新しい。あなたの真実は大きい。", ref: "哀歌 3:22-23" },
        { text: "私の敵よ。私のことで喜ぶな。私は倒れても、また起き上がる。暗やみにすわっていても、主は私の光である。", ref: "ミカ書 7:8" },
        { text: "主は心の打ち砕かれた者の近くにおられ、霊の砕かれた者を救われる。", ref: "詩篇 34:18" },
        { text: "だれでもキリストのうちにあるなら、その人は新しく造られた者です。古いものは過ぎ去って、見よ、すべてが新しくなりました。", ref: "コリント人への手紙 第二 5:17" },
        { text: "子どもたちよ。あなたがたは神から出た者です。そして彼らに勝ったのです。あなたがたのうちにおられる方が、この世のうちにいる、あの者よりも力があるからです。", ref: "ヨハネの手紙 第一 4:4" },
        { text: "あなたが水の中を過ぎるときも、私はあなたとともにおり、川を渡るときも、あなたは押し流されない。火の中を歩いても焼かれず、炎はあなたに燃えつかない。", ref: "イザヤ書 43:2" },
        { text: "神はわれらの避け所、また力。苦しむとき、そこにある助け。", ref: "詩篇 46:1" },
        { text: "私の心が衰え果てるとき、私は地の果てからあなたに呼ばわります。私のために、高すぎる岩の上に私を導いてください。", ref: "詩篇 61:2" },
        { text: "私がこれらのことをあなたがたに話したのは、あなたがたが私にあって平安を持つためです。あなたがたは、世にあっては患難があります。しかし、勇敢でありなさい。私はすでに世に勝ったのです。", ref: "ヨハネの福音書 16:33" }
    ],
    "he": [
        { text: "הַרְפּוּ וּדְעוּ כִּי־אָנֹכִי אֱלֹהִים.", ref: "תהילים מ\"ו 11" },
        { text: "יְהוָה יִלָּחֵם לָכֶם; וְאַתֶּם תַּחֲרִשׁוּן.", ref: "שמות י\"ד 14" },
        { text: "אַךְ אֶל־אֱלֹהִים דּוּמִיָּה נַפְשִׁי; מִמֶּנּוּ יְשׁוּעָתִי. אַךְ־הוּא צוּרִי וִישׁוּעָתִי; מִשְׂגַּבִּי לֹא־אֶמּוֹט רַבָּה.", ref: "תהילים ס\"ב 2-3" },
        { text: "בּוֹאוּ אֵלַי כָּל הָעֲמֵלִים וְהָעֲמוּסִים, וַאֲנִי אַנִיחַ לָכֶם.", ref: "מתי י\"א 28" },
        { text: "שָׁלוֹם אֲנִי מַשְׁאִיר לָכֶם, אֶת שְׁלוֹמִי אֲנִי נוֹתֵן לָכֶם. לֹא כְּמוֹ שֶׁהָעוֹלָם נוֹתֵן אֲנִי נוֹתֵן לָכֶם. אַל יִבָּהֵל לְבַבְכֶם וְאַל יִירָא.", ref: "יוחנן י\"ד 27" },
        { text: "שִׁוִּיתִי יְהוָה לְנֶגְדִּי תָמִיד; כִּי מִימִינִי בַּל־אֶמּוֹט.", ref: "תהילים ט\"ז 8" },
        { text: "לֹא בָּא עֲלֵיכֶם נִסָּיוֹן שֶׁאֵינֶנּוּ כְּדֶרֶךְ בְּנֵי אָדָם; וְנֶאֱמָן הָאֱלֹהִים שֶׁלֹּא יַנִּיחַ לָכֶם לְהִתְנַסּוֹת לְמַעְלָה מִיְּכָלְתְּכֶם, אֶלָּא עִם הַנִּסָּיוֹן יָכִין גַּם אֶת דֶּרֶךְ הַמִּפְלָט כְּדֵי שֶׁתּוּכְלוּ לַעֲמֹד בּוֹ.", ref: "הראשונה אל הקורינתים י' 13" },
        { text: "הִכָּנְעוּ אֵפוֹא לִפְנֵי הָאֱלֹהִים. הִתְיַצְּבוּ נֶגֶד הַשָֹטָן וְהוּא יִבְרַח מִפְּנֵיכֶם.", ref: "יעקב ד' 7" },
        { text: "כִּי כְּלֵי מִלְחַמְתֵּנוּ אֵינָם בְּשָׂרִיִּים, אֶלָּא יֵשׁ בָּהֶם כֹּחַ מֵאֵת הָאֱלֹהִים לַהֲרִיסַת מִבְצָרִים.", ref: "השנייה אל הקורינתים י' 4" },
        { text: "לַחֵרוּת שִׁחְרֵר אוֹתָנוּ הַמָּשִׁיחַ. עַל כֵּן עִמְדוּ יַצִּיבִים וְאַל תִּכָּנְעוּ שׁוּב תַּחַת עֹל הָעַבְדוּת.", ref: "האיגרת אל הגלטים ה' 1" },
        { text: "לָכֵן אִם הַבֵּן יְשַׁחְרֵר אֶתְכֶם, בֶּאֱמֶת תִּהְיוּ בְּנֵי חוֹרִין.", ref: "יוחנן ח' 36" },
        { text: "סִתְרִי וּמָגִנִּי אָתָּה; לִדְבָרְךָ יִחָלְתִּי.", ref: "תהילים קִי\"ט 114" },
        { text: "כָּלָה שְׁאֵרִי וּלְבָבִי; צוּר־לְבָבִי וְחֶלְקִי אֱלֹהִים לְעוֹלָם.", ref: "תהילים ע\"ג 26" },
        { text: "וְהוּא אָמַר אֵלַי: חַסְדִּי מַסְפִּיק לְךָ, כִּי גְּבוּרָתִי נִשְׁלֶמֶת בַּחֻלְשָׁה.", ref: "השנייה אל הקורינתים י\"ב 9" },
        { text: "וְקוֹיֵ יְהוָה יַחֲלִיפוּ כֹחַ; יַעֲלוּ אֵבֶר כַּנְּשָׁרִים, יָרוּצוּ וְלֹא יִיגָעוּ, יֵלְכוּ וְלֹא יִיעָפוּ.", ref: "ישעיהו מ' 31" },
        { text: "נֹתֵן לַיָּעֵף כֹּחַ; וּלְאֵין אוֹנִים עָצְמָה יַרְבֶּה.", ref: "ישעיהו מ' 29" },
        { text: "הַכֹּל אֲנִי יָכוֹל בְּעֶזְרָתוֹ שֶׁל הַנּוֹתֵן בִּי כֹּחַ.", ref: "האיגרת אל הפיליפים ד' 13" },
        { text: "אֶשָּׂא עֵינַי אֶל־הֶהָרִים; מֵאַיִן יָבֹא עֶזְרִי. עֶזְרִי מֵעִם יְהוָה; עֹשֵׂה שָׁמַיִם וָאָרֶץ.", ref: "תהילים קכ\"א 1-2" },
        { text: "אַל תִּדְאֲגוּ לְשׁוּם דָּבָר, אֶלָּא בְּכָל דָּבָר הַצִּיגוּ בַּקָּשׁוֹתֵיכֶם לֵאלֹהִים בִּתְפִלָּה וּבְתַחֲנוּנִים וּבְהוֹדָיָה. וּשְׁלוֹם אֱלֹהִים, שֶׁנִּשְׂגָּב מִכָּל שֵׂכֶל, יִנְצֹר אֶת לְבַבְכֶם וְאֶת מַחְשְׁבוֹתֵיכֶם בַּמָּשִׁיחַ יֵשׁוּעַ.", ref: "האיגרת אל הפיליפים ד' 6-7" },
        { text: "אַל־תִּירָא כִּי עִמְּךָ־אָנִי; אַל־תִּשְׁתָּע כִּי־אֲנִי אֱלֹהֶיךָ; אִמַּצְתִּיךָ אַף־עֲזַרְתִּיךָ, אַף־תְּמַכְתִּיךָ בִּימִין צִדְקִי.", ref: "ישעיהו מ\"א 10" },
        { text: "בְּרֹב שַׂרְעַפַּי בְּקִרְבִּי; תַּנְחוּמֶיךָ יְשַׁעַשְׁעוּ נַפְשִׁי.", ref: "תהילים צ\"ד 19" },
        { text: "הַשְׁלִיכוּ עָלָיו אֶת כָּל יְהַבְכֶם, כִּי הוּא דּוֹאֵג לָכֶם.", ref: "הראשונה של כיפא ה' 7" },
        { text: "גַּם כִּי־אֵלֵךְ בְּגֵיא צַלְמָוֶת לֹא־אִירָא רָע, כִּי־אַתָּה עִמָּדִי; שִׁבְטְךָ וּמִשְׁעַנְתֶּךָ, הֵמָּה יְנַחֲמֻנִי.", ref: "תהילים כ\"ג 4" },
        { text: "כִּי הָאֱלֹהִים לֹא נָתַן לָנוּ רוּחַ שֶׁל פַּחַד, אֶלָּא רוּחַ שֶׁל גְּבוּרָה וְאַהֲבָה וְיִשּׁוּב הַדַּעַת.", ref: "השנייה אל טימותיאוס א' 7" },
        { text: "כִּי שֶׁבַע יִפּוֹל צַדִּיק וָקָם; וּרְשָׁעִים יִכָּשְׁלוּ בְרָעָה.", ref: "משלי כ\"ד 16" },
        { text: "חַסְדֵי יְהוָה כִּי לֹא־תָמְנוּ, כִּי לֹא־כָלוּ רַחֲמָיו. חֲדָשִׁים לַבְּקָרִים; רַבָּה אֱמוּנָתֶךָ.", ref: "איכה ג' 22-23" },
        { text: "אַל־תִּשְׂמְחִי אֹיַבְתִּי לִי; כִּי נָפַלְתִּי קָמְתִּי, כִּי־אֵשֵׁב בַּחֹשֶׁךְ יְהוָה אוֹר לִי.", ref: "מיכה ז' 8" },
        { text: "קָרוֹב יְהוָה לְנִשְׁבְּרֵי־לֵב; וְאֶת־דַּכְּאֵי־רוּחַ יוֹשִׁיעַ.", ref: "תהילים ל\"ד 19" },
        { text: "לְפִיכָךְ מִי שֶׁבַּמָּשִׁיחַ הוּא בְּרִיאָה חֲדָשָׁה; הַיְשָׁנוֹת עָבְרוּ, הִנֵּה נִהְיוּ חֲדָשׁוֹת.", ref: "השנייה אל הקורינתים ה' 17" },
        { text: "אַתֶּם, יְלָדַי, מֵאֱלֹהִים אַתֶּם וְנִצַּחְתֶּם אוֹתָם, שֶׁכֵּן הַנִּמְצָא בָּכֶם גָּדוֹל מִזֶּה שֶׁנִּמְצָא בָּעוֹלָם.", ref: "הראשונה של יוחנן ד' 4" },
        { text: "כִּי־תַעֲבֹר בַּמַּיִם אִתְּךָ־אָנִי, וּבַנְּהָרוֹת לֹא יִשְׁטְפוּךָ; כִּי־תֵלֵךְ בְּמוֹ־אֵשׁ לֹא תִכָּוֶה, וְלֶהָבָה לֹא תִבְעַר־בָּךְ.", ref: "ישעיהו מ\"ג 2" },
        { text: "אֱלֹהִים לָנוּ מַחֲסֶה וָעֹז; עֶזְרָה בְצָרוֹת נִמְצָא מְאֹד.", ref: "תהילים מ\"ו 2" },
        { text: "מִקְצֵה הָאָרֶץ אֵלֶיךָ אֶקְרָא בַּעֲטֹף לִבִּי; בְּצוּר־יָרוּם מִמֶּנִּי תַנְחֵנִי.", ref: "תהילים ס\"א 3" },
        { text: "דִּבַּרְתִּי אֲלֵיכֶם אֶת הַדְּבָרִים הָאֵלֶּה כְּדֵי שֶׁבִּי יִהְיֶה לָכֶם שָׁלוֹם. בָּעוֹלָם יֵשׁ לָכֶם צָרָה, אַךְ הִתְעוֹדְדוּ: אֲנִי נִצַּחְתִּי אֶת הָעוֹלָם.", ref: "יוחנן ט\"ז 33" }
    ],
    "tl": [
        { text: "Kayo'y magsitigil, at kilalanin ninyo na ako ang Dios.", ref: "Mga Awit 46:10" },
        { text: "Ipakikipaglaban kayo ng Panginoon, at kayo'y tatahimik.", ref: "Exodo 14:14" },
        { text: "Sa Dios lamang naghihintay ng tahimik ang aking kaluluwa; mula sa kaniya ay ang aking kaligtasan. Siya lamang ang aking malaking bato at aking kaligtasan: siya ang aking matayog na moog; hindi ako lubhang makikilos.", ref: "Mga Awit 62:1-2" },
        { text: "Magsiparito sa akin, kayong lahat na nangapapagal at nangabibigatang lubha, at kayo'y aking papagpapahingahin.", ref: "Mateo 11:28" },
        { text: "Ang kapayapaan ay iniiwan ko sa inyo; ang aking kapayapaan ay ibinibigay ko sa inyo: hindi gaya ng ibinibigay ng sanglibutan, ang ibinibigay ko sa inyo. Huwag magulumihanan ang inyong puso, ni matakot man.", ref: "Juan 14:27" },
        { text: "Aking inilagay na lagi ang Panginoon sa harap ko: sapagka't siya'y nasa aking kanan, hindi ako makikilos.", ref: "Mga Awit 16:8" },
        { text: "Hindi dumating sa inyo ang anomang tukso kundi yaong matitiis ng tao: datapuwa't tapat ang Dios, na hindi niya itutulot na kayo'y tuksuhin ng higit sa inyong makakaya; kundi kalakip din ng tukso ay gagawin naman ang paraan ng pagilag, upang ito'y inyong matiis.", ref: "1 Corinto 10:13" },
        { text: "Pasakop nga kayo sa Dios; datapuwa't magsilaban kayo sa diablo, at tatakas siya sa inyo.", ref: "Santiago 4:7" },
        { text: "Sapagka't ang mga sandata ng aming pakikilaban ay hindi ukol sa laman, kundi kapangyarihan ng Dios sa ikagigiba ng mga kuta.", ref: "2 Corinto 10:4" },
        { text: "Sa kalayaan ay pinalaya tayo ni Cristo: magsitibay nga kayo, at huwag na kayong pasakop na muli sa pamatok ng pagkaalipin.", ref: "Galacia 5:1" },
        { text: "Kung palayain nga kayo ng Anak, kayo'y magiging tunay na laya.", ref: "Juan 8:36" },
        { text: "Ikaw ang aking kublihang dako at aking kalasag: ako'y umaasa sa iyong salita.", ref: "Mga Awit 119:114" },
        { text: "Ang aking laman at ang aking puso ay nanglulupaypay: nguni't ang Dios ay kalakasan ng aking puso at aking bahagi magpakailan man.", ref: "Mga Awit 73:26" },
        { text: "At sinabi niya sa akin, Ang aking biyaya ay sapat na sa iyo: sapagka't ang aking kapangyarihan ay nagiging sakdal sa kahinaan.", ref: "2 Corinto 12:9" },
        { text: "Nguni't silang nangaghihintay sa Panginoon ay mangagbabagong lakas; sila'y paiilanglang na may mga pakpak na parang mga aguila; sila'y magsisitakbo, at hindi mangapapagod; sila'y magsisilakad, at hindi manganghihina.", ref: "Isaias 40:31" },
        { text: "Siya'y nagbibigay ng lakas sa mahina; at sa kaniya na walang kapangyarihan ay dinadagdagan niya ng kalakasan.", ref: "Isaias 40:29" },
        { text: "Lahat ng mga bagay ay aking magagawa doon sa nagpapalakas sa akin.", ref: "Filipos 4:13" },
        { text: "Aking ititingin ang aking mga mata sa mga bundok: saan manggagaling ang aking saklolo? Ang aking saklolo ay nanggagaling sa Panginoon, na gumawa ng langit at lupa.", ref: "Mga Awit 121:1-2" },
        { text: "Huwag kayong mangabalisa sa anomang bagay; kundi sa lahat ng mga bagay sa pamamagitan ng pananalangin at daing na may pagpapasalamat ay ipakilala ninyo ang inyong mga kahilingan sa Dios. At ang kapayapaan ng Dios, na di masayod ng pagiisip, ay magiingat ng inyong mga puso at ng inyong mga pagiisip kay Cristo Jesus.", ref: "Filipos 4:6-7" },
        { text: "Huwag kang matakot, sapagka't ako'y sumasaiyo; huwag kang manglupaypay, sapagka't ako'y iyong Dios; aking palalakasin ka; oo, aking tutulungan ka; oo, aking aalalayan ka ng kanang kamay ng aking katuwiran.", ref: "Isaias 41:10" },
        { text: "Sa karamihan ng aking mga pagiisip sa loob ko ang iyong mga pangaliw ay nagpapasaya sa aking kaluluwa.", ref: "Mga Awit 94:19" },
        { text: "Na inyong ilagak sa kaniya ang lahat ng inyong kabalisahan, sapagka't kayo'y ipinagmamalasakit niya.", ref: "1 Pedro 5:7" },
        { text: "Oo, bagaman ako'y lumalakad sa libis ng lilim ng kamatayan, wala akong katatakutang kasamaan; sapagka't ikaw ay sumasa akin: ang iyong pamalo at ang iyong tungkod, ay nagsisiaw sa akin.", ref: "Mga Awit 23:4" },
        { text: "Sapagka't hindi tayo binigyan ng Dios ng espiritu ng katakutan; kundi ng kapangyarihan at ng pagibig at ng kahusayan.", ref: "2 Timoteo 1:7" },
        { text: "Sapagka't ang matuwid ay nabubuwal na makapito, at bumabangong muli: nguni't ang masama ay nabubuwal sa kasamaan.", ref: "Mga Kawikaan 24:16" },
        { text: "Sa mga kaawaan ng Panginoon ay hindi tayo nalipol, sapagka't ang kaniyang mga habag ay hindi nauubos. Mga bago tuwing umaga; dakila ang iyong pagtatapat.", ref: "Mga Panaghoy 3:22-23" },
        { text: "Huwag kang magalak laban sa akin, Oh kaaway ko: pagka ako'y nabuwal, ako'y babangon; pagka ako'y naupo sa kadiliman, ang Panginoon ay magiging ilaw ko.", ref: "Mikas 7:8" },
        { text: "Ang Panginoon ay malapit sa kanila na may bagbag na puso, at inililigtas ang mga may pagsisising diwa.", ref: "Mga Awit 34:18" },
        { text: "Kaya't kung ang sinoman ay na kay Cristo, siya'y bagong nilalang: ang mga dating bagay ay nagsilipas na; narito, sila'y pawang naging mga bago.", ref: "2 Corinto 5:17" },
        { text: "Kayo'y sa Dios, mumunti kong mga anak, at inyong dinaig sila: sapagka't lalong dakila siyang nasa inyo kay sa nasa sanglibutan.", ref: "1 Juan 4:4" },
        { text: "Pagka ikaw ay dumaan sa tubig, ako'y sasa iyo; at sa mga ilog ay hindi ka aapawan: pagka ikaw ay lumakad sa apoy, hindi ka masusunog; o magniningas man ang alab sa iyo.", ref: "Isaias 43:2" },
        { text: "Ang Dios ay ating ampunan at kalakasan, saklolong handa sa kabagabagan.", ref: "Mga Awit 46:1" },
        { text: "Mula sa wakas ng lupa ay tatawag ako sa iyo, pagka nanglupaypay ang aking puso: patnubayan mo ako sa malaking bato na lalong mataas kay sa akin.", ref: "Mga Awit 61:2" },
        { text: "Ang mga bagay na ito ay sinalita ko sa inyo, upang kayo'y magkaroon sa akin ng kapayapaan. Sa sanglibutan ay mayroon kayong kapighatian: nguni't laksan ninyo ang inyong loob; aking dinaig ang sanglibutan.", ref: "Juan 16:33" }
    ],
    "it": [
        { text: "Fermatevi, dice, e riconoscete che io sono Dio.", ref: "Salmi 46:10" },
        { text: "Il Signore combatterà per voi, e voi ve ne starete tranquilli.", ref: "Esodo 14:14" },
        { text: "Solo in Dio riposa la mia anima; da lui viene la mia salvezza. Egli solo è la mia rocca e la mia salvezza; egli è il mio rifugio; io non potrò vacillare.", ref: "Salmi 62:1-2" },
        { text: "Venite a me, voi tutti che siete affaticati e oppressi, e io vi darò riposo.", ref: "Matteo 11:28" },
        { text: "Vi lascio pace; vi do la mia pace. Io non vi do come il mondo dà. Il vostro cuore non sia turbato e non si sgomenti.", ref: "Giovanni 14:27" },
        { text: "Io ho sempre posto il Signore davanti agli occhi miei; poiché egli è alla mia destra, io non sarò punto smosso.", ref: "Salmi 16:8" },
        { text: "Nessuna tentazione vi ha còlti, che non sia stata umana; però Dio è fedele e non permetterà che siate tentati oltre le vostre forze; ma con la tentazione vi darà anche la via d'uscirne, affinché la possiate sopportare.", ref: "1 Corinzi 10:13" },
        { text: "Sottomettetevi dunque a Dio; ma resistete al diavolo, ed egli fuggirà da voi.", ref: "Giacomo 4:7" },
        { text: "Infatti le armi della nostra guerra non sono carnali, ma hanno da Dio il potere di distruggere le fortezze.", ref: "2 Corinzi 10:4" },
        { text: "Cristo ci ha liberati perché fossimo liberi; state dunque saldi e non vi lasciate porre di nuovo sotto il giogo della schiavitù.", ref: "Galati 5:1" },
        { text: "Se dunque il Figlio vi farà liberi, sarete veramente liberi.", ref: "Giovanni 8:36" },
        { text: "Tu sei il mio rifugio e il mio scudo; io spero nella tua parola.", ref: "Salmi 119:114" },
        { text: "La mia carne e il mio cuore possono venir meno, ma Dio è la rocca del mio cuore e la mia parte di retaggio, in eterno.", ref: "Salmi 73:26" },
        { text: "Ed egli mi ha detto: La mia grazia ti basta, perché la mia potenza si dimostra perfetta nella debolezza.", ref: "2 Corinzi 12:9" },
        { text: "Ma quelli che sperano nel Signore acquistano nuove forze, si alzano a volo come aquile, corrono e non si stancano, camminano e non si affaticano.", ref: "Isaia 40:31" },
        { text: "Egli dà forza allo stanco e accresce il vigore a colui che è spossato.", ref: "Isaia 40:29" },
        { text: "Io posso ogni cosa in colui che mi fortifica.", ref: "Filippesi 4:13" },
        { text: "Alzo gli occhi verso i monti... Da dove mi verrà l'aiuto? Il mio aiuto vien dal Signore, che ha fatto il cielo e la terra.", ref: "Salmi 121:1-2" },
        { text: "Non angustiatevi di nulla, ma in ogni cosa fate conoscere le vostre richieste a Dio in preghiere e suppliche, accompagnate da ringraziamenti. E la pace di Dio, che supera ogni intelligenza, custodirà i vostri cuori e i vostri pensieri in Cristo Gesù.", ref: "Filippesi 4:6-7" },
        { text: "Tu, non temere, perché io sono con te; non ti smarrire, perché io sono il tuo Dio; io ti fortifico, io ti soccorro, io ti sostengo con la destra della mia giustizia.", ref: "Isaia 41:10" },
        { text: "Quando ero turbato da grandi preoccupazioni, i tuoi conforti hanno alleviato l'anima mia.", ref: "Salmi 94:19" },
        { text: "Gettando su di lui ogni vostra preoccupazione, perché egli ha cura di voi.", ref: "1 Pietro 5:7" },
        { text: "Quand'anche camminassi nella valle dell'ombra della morte, io non temerei alcun male, perché tu sei con me; il tuo bastone e la tua verga mi dànno sicurezza.", ref: "Salmi 23:4" },
        { text: "Dio infatti ci ha dato uno spirito non di timidezza, ma di forza, d'amore e di autocontrollo.", ref: "2 Timoteo 1:7" },
        { text: "Perché il giusto cade sette volte e si rialza, ma gli empi sono travolti dalla sventura.", ref: "Proverbi 24:16" },
        { text: "È una grazia del Signore che non siamo stati interamente distrutti; le sue compassioni infatti non sono esaurite; si rinnovano ogni mattina. Grande è la tua fedeltà!", ref: "Lamentazioni 3:22-23" },
        { text: "Non rallegrarti di me, o mia nemica! Se sono caduta, mi rialzerò; se siedo nelle tenebre, il Signore è la mia luce.", ref: "Michea 7:8" },
        { text: "Il Signore è vicino a quelli che hanno il cuore afflitto, salva gli umili di spirito.", ref: "Salmi 34:18" },
        { text: "Se dunque uno è in Cristo, egli è una nuova creatura; le cose vecchie sono passate: ecco, sono diventate nuove.", ref: "2 Corinzi 5:17" },
        { text: "Voi siete da Dio, figlioli, e li avete vinti, perché colui che è in voi è più grande di colui che è nel mondo.", ref: "1 Giovanni 4:4" },
        { text: "Quando passerai per delle acque, io sarò con te; o per dei fiumi, non ti sommergeranno; quando camminerai nel fuoco, non ne sarai bruciato, e la fiamma non ti consumerà.", ref: "Isaia 43:2" },
        { text: "Dio è per noi un rifugio e una forza, un aiuto sempre pronto nelle difficoltà.", ref: "Salmi 46:1" },
        { text: "Dall'estremità della terra io grido a te, mentre il mio cuore viene meno. Guidami sulla rocca che per me è troppo alta.", ref: "Salmi 61:2" },
        { text: "Vi ho detto queste cose, affinché abbiate pace in me. Nel mondo avrete tribolazione; ma fatevi coraggio, io ho vinto il mondo.", ref: "Giovanni 16:33" }
    ],
    "ko": [
        { text: "이르시기를 너희는 가만히 있어 내가 하나님 됨을 알지어다.", ref: "시편 46:10" },
        { text: "여호와께서 너희를 위하여 싸우시리니 너희는 가만히 있을지니라.", ref: "출애굽기 14:14" },
        { text: "나의 영혼이 잠잠히 하나님만 바람이여 나의 구원이 그에게서 나오는도다. 오직 그만이 나의 반석이시요 나의 구원이시요 나의 요새이시니 내가 크게 흔들리지 아니하리로다.", ref: "시편 62:1-2" },
        { text: "수고하고 무거운 짐 진 자들아 다 내게로 오라 내가 너희를 쉬게 하리라.", ref: "마태복음 11:28" },
        { text: "평안을 너희에게 끼치노니 곧 나의 평안을 너희에게 주노라 내가 너희에게 주는 것은 세상이 주는 것과 같지 아니하니라 너희는 마음에 근심하지도 말고 두려워하지도 말라.", ref: "요한복음 14:27" },
        { text: "내가 여호와를 항상 내 앞에 모심이여 그가 나의 오른쪽에 계시므로 내가 흔들리지 아니하리로다.", ref: "시편 16:8" },
        { text: "사람이 감당할 시험 밖에는 너희가 당한 것이 없나니 오직 하나님은 미쁘사 너희가 감당하지 못할 시험 당함을 허락하지 아니하시고 시험 당할 즈음에 또한 피할 길을 내사 너희로 능히 감당하게 하시느니라.", ref: "고린도전서 10:13" },
        { text: "그런즉 너희는 하나님께 복종할지어다 마귀를 대적하라 그리하면 너희를 피하리라.", ref: "야고보서 4:7" },
        { text: "우리의 싸우는 무기는 육신에 속한 것이 아니요 오직 어떤 견고한 진도 무너뜨리는 하나님의 능력이라.", ref: "고린도후서 10:4" },
        { text: "그리스도께서 우리를 자유롭게 하려고 자유를 주셨으니 그러므로 굳건하게 서서 다시는 종의 멍에를 메지 말라.", ref: "갈라디아서 5:1" },
        { text: "그러므로 아들이 너희를 자유롭게 하면 너희가 참으로 자유로우리라.", ref: "요한복음 8:36" },
        { text: "주는 나의 은신처요 방패시라 내가 주의 말씀을 바라나이다.", ref: "시편 119:114" },
        { text: "내 육체와 마음은 쇠약하나 하나님은 내 마음의 반석이시요 영원한 분깃이시라.", ref: "시편 73:26" },
        { text: "나에게 이르시기를 내 은혜가 네게 족하도다 이는 내 능력이 약한 데서 온전하여짐이라 하신지라.", ref: "고린도후서 12:9" },
        { text: "오직 여호와를 앙망하는 자는 새 힘을 얻으리니 독수리가 날개치며 올라감 같을 것이요 달음박질하여도 곤비하지 아니하겠고 걸어가도 피곤하지 아니하리로다.", ref: "이사야 40:31" },
        { text: "피곤한 자에게는 능력을 주시며 무능한 자에게는 힘을 더하시나니.", ref: "이사야 40:29" },
        { text: "내게 능력 주시는 자 안에서 내가 모든 것을 할 수 있느니라.", ref: "빌립보서 4:13" },
        { text: "내가 산을 향하여 눈을 들리라 나의 도움이 어디서 올까 나의 도움은 천지를 지으신 여호와에게서로다.", ref: "시편 121:1-2" },
        { text: "아무 것도 염려하지 말고 다만 모든 일에 기도와 간구로, 너희 구할 것을 감사함으로 하나님께 아뢰라. 그리하면 모든 지각에 뛰어난 하나님의 평강이 그리스도 예수 안에서 너희 마음과 생각을 지키시리라.", ref: "빌립보서 4:6-7" },
        { text: "두려워하지 말라 내가 너와 함께 함이라 놀라지 말라 나는 네 하나님이 됨이라 내가 너를 굳세게 하리라 참으로 너를 도와 주리라 참으로 나의 의로운 오른손으로 너를 붙들리라.", ref: "이사야 41:10" },
        { text: "내 속에 근심이 많을 때에 주의 위안이 내 영혼을 즐겁게 하시나이다.", ref: "시편 94:19" },
        { text: "너희 염려를 다 주께 맡기라 이는 그가 너희를 돌보심이라.", ref: "베드로전서 5:7" },
        { text: "내가 사망의 음침한 골짜기로 다닐지라도 해를 두려워하지 않을 것은 주께서 나와 함께 하심이라 주의 지팡이와 막대기가 나를 안위하시나이다.", ref: "시편 23:4" },
        { text: "하나님이 우리에게 주신 것은 두려워하는 마음이 아니요 오직 능력과 사랑과 절제하는 마음이니.", ref: "디모데후서 1:7" },
        { text: "대저 의인은 일곱 번 넘어질지라도 다시 일어나려니와 악인은 재앙으로 말미암아 엎드러지느니라.", ref: "잠언 24:16" },
        { text: "여호와의 인자와 긍휼이 무궁하시므로 우리가 진멸되지 아니함이니이다 이것들이 아침마다 새로우니 주의 성실하심이 크시도소이다.", ref: "예레미야 애가 3:22-23" },
        { text: "나의 대적이여 나로 말미암아 기뻐하지 말지어다 나는 엎드러질지라도 일어날 것이요 어두운 데에 앉을지라도 여호와께서 나의 빛이 되실 것임이로다.", ref: "미가 7:8" },
        { text: "여호와는 마음이 상한 자를 가까이 하시고 충심으로 통회하는 자를 구원하시는도다.", ref: "시편 34:18" },
        { text: "그런즉 누구든지 그리스도 안에 있으면 새로운 피조물이라 이전 것은 지나갔으니 보라 새 것이 되었도다.", ref: "고린도후서 5:17" },
        { text: "자녀들아 너희는 하나님께 속하였고 또 그들을 이기었나니 이는 너희 안에 계신 이가 세상에 있는 자보다 크심이라.", ref: "요한1서 4:4" },
        { text: "네가 물 가운데로 지날 때에 내가 너와 함께 할 것이라 강을 건널 때에 물이 너를 침몰하지 못할 것이며 네가 불 가운데로 지날 때에 타지도 아니할 것이요 불꽃이 너를 사르지도 못하리니.", ref: "이사야 43:2" },
        { text: "하나님은 우리의 피난처시요 힘이시니 환난 중에 만날 큰 도움이시라.", ref: "시편 46:1" },
        { text: "내 마음이 약해 질 때에 땅 끝에서부터 주께 부르짖으오리니 나보다 높은 바위에 나를 인도하소서.", ref: "시편 61:2" },
        { text: "이것을 너희에게 이르는 것은 너희로 내 안에서 평안을 누리게 하려 함이라 세상에서는 너희가 환난을 당하나 담대하라 내가 세상을 이기었노라.", ref: "요한복음 16:33" }
    ],
    "pl": [
        { text: "Zatrzymajcie się i uznajcie, że Ja jestem Bogiem.", ref: "Psalm 46:11" },
        { text: "Pan będzie walczył za was, a wy będziecie spokojni.", ref: "Księga Wyjścia 14:14" },
        { text: "Tylko w Bogu spokój znajduje ma dusza, od Niego przychodzi moje zbawienie. Tylko On jest opoką i zbawieniem moim, On moją twierdzą, więc się nie zachwieję.", ref: "Psalm 62:2-3" },
        { text: "Przyjdźcie do Mnie wszyscy, którzy utrudzeni i obciążeni jesteście, a Ja was pokrzepię.", ref: "Ewangelia Mateusza 11:28" },
        { text: "Pokój zostawiam wam, pokój mój daję wam. Nie tak jak daje świat, Ja wam daję. Niech się nie trwoży serce wasze ani się lęka.", ref: "Ewangelia Jana 14:27" },
        { text: "Stawiam sobie zawsze Pana przed oczy, nie zachwieję się, bo On jest po mojej prawicy.", ref: "Psalm 16:8" },
        { text: "Pokusa nie nawiedziła was większa od tej, która zwykła nawiedzać ludzi. Wierny jest Bóg i nie pozwoli was kusić ponad to, co potraficie znieść, lecz zsyłając pokusę, wskaże sposób jej pokonania, abyście mogli przetrwać.", ref: "1 List do Koryntian 10:13" },
        { text: "Bądźcie więc poddani Bogu, przeciwstawiajcie się natomiast diabłu, a ucieknie od was.", ref: "List Jakuba 4:7" },
        { text: "Oręż bojowania naszego nie jest z ciała, lecz posiada moc burzenia, dla Boga, twierdz warownych.", ref: "2 List do Koryntian 10:4" },
        { text: "Ku wolności wyswobodził nas Chrystus. A zatem trwajcie w niej i nie poddawajcie się na nowo pod jarzmo niewoli.", ref: "List do Galatów 5:1" },
        { text: "Jeżeli więc Syn was wyzwoli, wówczas będziecie rzeczywiście wolni.", ref: "Ewangelia Jana 8:36" },
        { text: "Ty jesteś moją osłoną i moją tarczą: pokładam ufność w Twoim słowie.", ref: "Psalm 119:114" },
        { text: "Niszczeje moje ciało i serce, Bóg jest opoką mego serca i mym działem na wieki.", ref: "Psalm 73:26" },
        { text: "Lecz On mi powiedział: Wystarczy ci mojej łaski. Moc bowiem w słabości się doskonali.", ref: "2 List do Koryntian 12:9" },
        { text: "Lecz ci, co zaufali Panu, odzyskują siły, otrzymują skrzydła jak orły: biegną bez zmęczenia, bez znużenia idą.", ref: "Księga Izajasza 40:31" },
        { text: "On dodaje mocy zmęczonemu i pomnaża siły omdlałego.", ref: "Księga Izajasza 40:29" },
        { text: "Wszystko mogę w Tym, który mnie umacnia.", ref: "List do Filipian 4:13" },
        { text: "Wznoszę swe oczy ku górom: Skąd nadejdzie mi pomoc? Pomoc mi przyjdzie od Pana, co stworzył niebo i ziemię.", ref: "Psalm 121:1-2" },
        { text: "O nic się już zbytnio nie troskajcie, ale w każdej sprawie wasze prośby przedstawiajcie Bogu w modlitwie i błaganiu z dziękczynieniem. A pokój Boży, który przewyższa wszelki umysł, będzie strzegł waszych serc i myśli w Chrystusie Jezusie.", ref: "List do Filipian 4:6-7" },
        { text: "Nie lękaj się, bo Ja jestem z tobą; nie trwóż się, bom Ja twoim Bogiem. Umacniam cię, jeszcze i wspomagam, podtrzymuję cię moją prawicą sprawiedliwą.", ref: "Księga Izajasza 41:10" },
        { text: "Kiedy się mnożą we mnie utrapienia, Twoje pociechy orzeźwiają moją duszę.", ref: "Psalm 94:19" },
        { text: "Wszystkie troski wasze przerzućcie na Niego, gdyż Jemu zależy na was.", ref: "1 List Piotra 5:7" },
        { text: "Chociażbym chodził ciemną doliną, zła się nie ulęknę, bo Ty jesteś ze mną. Twój kij i Twoja laska są tym, co mnie pociesza.", ref: "Psalm 23:4" },
        { text: "Albowiem nie dał nam Bóg ducha bojaźni, ale mocy i miłości, i trzeźwego myślenia.", ref: "2 List do Tymoteusza 1:7" },
        { text: "Bo sprawiedliwy siódmy raz upadnie i wstanie, a występni w nieszczęściu upadają.", ref: "Księga Przysłów 24:16" },
        { text: "Nie wyczerpała się litość Pana, miłość nie zgasła. Odnawia się ona co rano: ogromna jest Twoja wierność.", ref: "Lamentacje 3:22-23" },
        { text: "Nie ciesz się z mego powodu, moja nieprzyjaciółko! Choć upadłem, powstanę; choć siedzę w ciemności, Pan jest moim światłem.", ref: "Księga Micheasza 7:8" },
        { text: "Pan jest blisko skruszonych w sercu i zbawia złamanych na duchu.", ref: "Psalm 34:19" },
        { text: "Jeżeli więc ktoś pozostaje w Chrystusie, jest nowym stworzeniem. To, co dawne, minęło, a oto stało się nowe.", ref: "2 List do Koryntian 5:17" },
        { text: "Wy, dzieci, jesteście z Boga i zwyciężyliście ich, ponieważ większy jest Ten, który w was jest, od tego, który jest w świecie.", ref: "1 List Jana 4:4" },
        { text: "Gdy pójdziesz przez wody, Ja będę z tobą, i gdy przez rzeki, nie zatopią ciebie. Gdy pójdziesz przez ogień, nie spłoniesz, i nie opali cię płomień.", ref: "Księga Izajasza 43:2" },
        { text: "Bóg jest dla nas ucieczką i mocą: łatwo znaleźć u Niego pomoc w trudnościach.", ref: "Psalm 46:2" },
        { text: "Z krańców ziemi wołam do Ciebie, gdy słabnie moje serce: wprowadź mnie na skałę, która dla mnie jest za wysoka.", ref: "Psalm 61:3" },
        { text: "To wam powiedziałem, abyście pokój we Mnie mieli. Na świecie doznacie ucisku, ale miejcie odwagę: Jam zwyciężył świat.", ref: "Ewangelia Jana 16:33" }
    ],
    "sw": [
        { text: "Acheni, mjue ya kuwa mimi ni Mungu.", ref: "Zaburi 46:10" },
        { text: "Bwana atawapigania, nanyi mtanyamaza kimya.", ref: "Kutoka 14:14" },
        { text: "Nafsi yangu inamngoja Mungu peke yake kwa kimya, Wokovu wangu hutoka kwake. Yeye tu ndiye mwamba wangu na wokovu wangu, Ngome yangu, sitatikisika sana.", ref: "Zaburi 62:1-2" },
        { text: "Njooni kwangu, ninyi nyote msumbukao na wenye kulemewa na mizigo, nami nitawapumzisha.", ref: "Mathayo 11:28" },
        { text: "Amani nawaachieni; amani yangu nawapa; niwapavyo mimi sivyo kama ulimwengu utoavyo. Msifadhaike mioyoni mwenu, wala msiwe na woga.", ref: "Yohana 14:27" },
        { text: "Nimemweka Bwana mbele yangu daima, Kwa kuwa yuko mkono wangu wa kuume sitaondoshwa.", ref: "Zaburi 16:8" },
        { text: "Jaribu halikuwapata ninyi, isipokuwa lililo kawaida ya wanadamu; ila Mungu ni mwaminifu; ambaye hatawaacha mjaribiwe kupita mwezavyo; lakini pamoja na lile jaribu atafanya na mlango wa kutokea, ili mweze kustahimili.", ref: "1 Wakorintho 10:13" },
        { text: "Basi mtiini Mungu. Mpingeni Shetani, naye atawakimbia.", ref: "Yakobo 4:7" },
        { text: "Maana silaha za vita vyetu si za mwili, bali zina uwezo katika Mungu hata kuangusha ngome.", ref: "2 Wakorintho 10:4" },
        { text: "Katika ungwana huo Kristo alituungwanisha; basi simameni imara, wala msinaswe tena chini ya kongwa la utumwa.", ref: "Wagalatia 5:1" },
        { text: "Basi Mwana akiwaweka huru, mtakuwa huru kweli kweli.", ref: "Yohana 8:36" },
        { text: "Wewe ndiwe sitara yangu na ngao yangu, Nimeingojea neno lako.", ref: "Zaburi 119:114" },
        { text: "Mwili wangu na moyo wangu huzimia, Bali Mungu ndiye mwamba wa moyo wangu na sehemu yangu milele.", ref: "Zaburi 73:26" },
        { text: "Naye akaniambia, Neema yangu yakutosha; maana uweza wangu hutimilika katika udhaifu.", ref: "2 Wakorintho 12:9" },
        { text: "Bali wao wamngojeao Bwana watapata nguvu mpya; watapanda juu kwa mbawa kama tai; watapiga mbio, wala hawatachoka; watatembea, wala hawatazimia.", ref: "Isaya 40:31" },
        { text: "Huwapa nguvu wazimiao, humwongezea nguvu yeye asiyekuwa na uwezo.", ref: "Isaya 40:29" },
        { text: "Nayaweza mambo yote katika yeye anitiaye nguvu.", ref: "Wafilipi 4:13" },
        { text: "Nainua macho yangu niitazame milima, Msaada wangu utatoka wapi? Msaada wangu u katika Bwana, Aliyezifanya mbingu na nchi.", ref: "Zaburi 121:1-2" },
        { text: "Msijisumbue kwa neno lolote; bali katika kila neno kwa kusali na kuomba, pamoja na kushukuru, haja zenu na zijulikane na Mungu. Na amani ya Mungu, ipitayo akili zote, itawahifadhi mioyo yenu na nia zenu katika Kristo Yesu.", ref: "Wafilipi 4:6-7" },
        { text: "Usiogope, kwa maana mimi ni pamoja nawe; usifadhaike, kwa maana mimi ni Mungu wako; nitakutia nguvu, naam, nitakusaidia, naam, nitakushika kwa mkono wa kuume wa haki yangu.", ref: "Isaya 41:10" },
        { text: "Katika wingi wa mawazo yangu ndani yangu, Faraja zako zaifurahisha nafsi yangu.", ref: "Zaburi 94:19" },
        { text: "Huku mkimtwika yeye fadhaa zenu zote, kwa maana yeye hujishughulisha sana kwa ajili yenu.", ref: "1 Petro 5:7" },
        { text: "Naam, nijapopita kati ya bonde la uvuli wa mauti, Sitaogopa mabaya; Kwa maana Wewe upo pamoja nami, Gongo lako na fimbo yako vyanifariji.", ref: "Zaburi 23:4" },
        { text: "Maana Mungu hakutupa roho ya woga, bali ya nguvu na ya upendo na ya moyo wa kiasi.", ref: "2 Timotheo 1:7" },
        { text: "Kwa maana mwenye haki huanguka mara saba akaondoka tena; Bali wasio haki hukwazwa na uovu.", ref: "Mithali 24:16" },
        { text: "Ni huruma za Bwana kwamba hatuangamii, Kwa kuwa rehema zake hazikomi. Ni mpya kila asubuhi; Uaminifu wako ni mkuu.", ref: "Maombolezo 3:22-23" },
        { text: "Usifurahi juu yangu, Ee adui yangu; niangukapo, nitasimama tena; nikaapo gizani, Bwana atakuwa nuru kwangu.", ref: "Mika 7:8" },
        { text: "Bwana yu karibu nao waliovunjika moyo, Na waliopondeka roho huwaokoa.", ref: "Zaburi 34:18" },
        { text: "Hata imekuwa, mtu akiwa ndani ya Kristo amekuwa kiumbe kipya; ya kale yamepita tazama! Yamekuwa mapya.", ref: "2 Wakorintho 5:17" },
        { text: "Ninyi, watoto wadogo, mwatokana na Mungu nanyi mmewashinda, kwa sababu yeye aliye ndani yenu ni mkuu kuliko yeye aliye katika dunia.", ref: "1 Yohana 4:4" },
        { text: "Upitapo katika maji mengi nitakuwa pamoja nawe; na katika mito, haitakugharikisha; uendapo katika moto, hutateketea; wala mwali wa moto hautakuunguza.", ref: "Isaya 43:2" },
        { text: "Mungu kwetu sisi ni kimbilio na nguvu, Msaada utakaoonekana tele wakati wa mateso.", ref: "Zaburi 46:1" },
        { text: "Tokea mwisho wa nchi nitakulilia, Moyo wangu unapozimia; Uniongoze mwambani, palipo juu kuliko mimi.", ref: "Zaburi 61:2" },
        { text: "Hayo nimewaambieni mpate kuwa na amani ndani yangu. Ulimwenguni mnayo dhiki; lakini jipeni moyo; mimi nimeushinda ulimwengu.", ref: "Yohana 16:33" }
    ]
};
